In [1]:
%load_ext sql
%sql postgresql://postgres:00wasabi00@127.0.0.1/salesdb

'Connected: postgres@salesdb'

# CS561 – Programming Assignment 2

1.For each customer, product and state combination, compute 
- (1) the customer's average sale of this product for the state, 
- (2) the average sale of the product and the customer but for the other states and 
- (3) the customer’s average sale for the given state, but for the other products.

In [110]:
%%sql
with avg_table as(
    select cust, prod, state,round(avg(quant),2) as cust_avg 
    from sales
    group by cust, prod, state
),
avg_state as(
    select a.cust,a.prod,a.state, avg(b.quant) as other_state_avg
    from sales as a
    join sales as b
    on a.cust=b.cust
    and a.prod=b.prod
    and a.state != b.state
    group by a.cust,a.prod,a.state
),
avg_prod as(
    select a.cust,a.prod,a.state, avg(b.quant) as other_prod_avg
    from sales as a
    join sales as b
    on a.cust=b.cust
    and a.prod<>b.prod
    and a.state=b.state
    group by a.cust,a.prod,a.state
)
select distinct a.cust,a.prod,a.state,
round(a.cust_avg,2) as cust_avg,
round(b.other_state_avg,2) as other_state_avg,
round(c.other_prod_avg,2) as other_prod_avg
from avg_table as a
natural inner join avg_state as b 
natural inner join avg_prod as c
order by a.cust,a.prod

 * postgresql://postgres:***@127.0.0.1/salesdb
187 rows affected.

[('Bloom', 'Bread', 'CT', Decimal('1529.60'), Decimal('2527.86'), Decimal('2782.43')),
 ('Bloom', 'Bread', 'NJ', Decimal('2160.60'), Decimal('2077.14'), Decimal('2567.17')),
 ('Bloom', 'Bread', 'NY', Decimal('3792.00'), Decimal('1959.18'), Decimal('2546.35')),
 ('Bloom', 'Bread', 'PA', Decimal('3100.00'), Decimal('2022.09'), Decimal('2146.41')),
 ('Bloom', 'Butter', 'CT', Decimal('4279.00'), Decimal('2386.00'), Decimal('2472.00')),
 ('Bloom', 'Butter', 'NJ', Decimal('3718.00'), Decimal('2666.50'), Decimal('2453.46')),
 ('Bloom', 'Butter', 'NY', Decimal('1054.00'), Decimal('3998.50'), Decimal('2707.41')),
 ('Bloom', 'Coke', 'CT', Decimal('2284.00'), Decimal('2354.57'), Decimal('2562.96')),
 ('Bloom', 'Coke', 'NJ', Decimal('2017.00'), Decimal('2499.83'), Decimal('2552.46')),
 ('Bloom', 'Coke', 'NY', Decimal('1229.00'), Decimal('2477.63'), Decimal('2697.12')),
 ('Bloom', 'Coke', 'PA', Decimal('3067.33'), Decimal('1974.67'), Decimal('2055.95')),
 ('Bloom', 'Cookies', 'CT', Decimal('2640.75'), Decimal('3411.80'), Decimal('2523.45')),
 ('Bloom', 'Cookies', 'NJ', Decimal('4063.50'), Decimal('2785.00'), Decimal('2381.04')),
 ('Bloom', 'Cookies', 'NY', Decimal('4570.00'), Decimal('2881.50'), Decimal('2500.59')),
 ('Bloom', 'Cookies', 'PA', Decimal('2181.00'), Decimal('3322.86'), Decimal('2188.52')),
 ('Bloom', 'Eggs', 'CT', Decimal('2410.75'), Decimal('2558.57'), Decimal('2565.27')),
 ('Bloom', 'Eggs', 'NJ', Decimal('2765.50'), Decimal('2446.89'), Decimal('2477.19')),
 ('Bloom', 'Eggs', 'NY', Decimal('2164.00'), Decimal('2699.57'), Decimal('2744.57')),
 ('Bloom', 'Eggs', 'PA', Decimal('3723.00'), Decimal('2383.00'), Decimal('2118.09')),
 ('Bloom', 'Fruits', 'CT', Decimal('3639.33'), Decimal('2220.93'), Decimal('2398.30')),
 ('Bloom', 'Fruits', 'NJ', Decimal('2234.00'), Decimal('2522.07'), Decimal('2527.42')),
 ('Bloom', 'Fruits', 'NY', Decimal('2332.75'), Decimal('2513.85'), Decimal('2696.36')),
 ('Bloom', 'Fruits', 'PA', Decimal('2151.43'), Decimal('2695.10'), Decimal('2203.81')),
 ('Bloom', 'Milk', 'CT', Decimal('3117.33'), Decimal('2658.90'), Decimal('2466.39')),
 ('Bloom', 'Milk', 'NJ', Decimal('2380.00'), Decimal('2935.67'), Decimal('2515.80')),
 ('Bloom', 'Milk', 'NY', Decimal('3306.33'), Decimal('2602.20'), Decimal('2477.40')),
 ('Bloom', 'Milk', 'PA', Decimal('2383.33'), Decimal('2879.10'), Decimal('2158.55')),
 ('Bloom', 'Pepsi', 'CT', Decimal('94.00'), Decimal('2185.14'), Decimal('2639.40')),
 ('Bloom', 'Pepsi', 'NJ', Decimal('2194.00'), Decimal('1653.50'), Decimal('2545.56')),
 ('Bloom', 'Pepsi', 'NY', Decimal('2243.00'), Decimal('1817.33'), Decimal('2662.13')),
 ('Bloom', 'Pepsi', 'PA', Decimal('2034.00'), Decimal('1908.00'), Decimal('2194.86')),
 ('Bloom', 'Soap', 'CT', Decimal('2505.00'), Decimal('2313.50'), Decimal('2544.54')),
 ('Bloom', 'Soap', 'NJ', Decimal('4364.00'), Decimal('1980.00'), Decimal('2430.39')),
 ('Bloom', 'Soap', 'PA', Decimal('1630.00'), Decimal('3124.67'), Decimal('2271.55')),
 ('Bloom', 'Yogurt', 'CT', Decimal('4004.00'), Decimal('1952.29'), Decimal('2483.00')),
 ('Bloom', 'Yogurt', 'NJ', Decimal('2205.75'), Decimal('2211.75'), Decimal('2543.68')),
 ('Bloom', 'Yogurt', 'NY', Decimal('4043.00'), Decimal('1946.71'), Decimal('2531.59')),
 ('Bloom', 'Yogurt', 'PA', Decimal('400.00'), Decimal('2811.67'), Decimal('2358.14')),
 ('Emily', 'Bread', 'CT', Decimal('1626.00'), Decimal('1524.11'), Decimal('2688.46')),
 ('Emily', 'Bread', 'NJ', Decimal('1743.75'), Decimal('1394.67'), Decimal('2804.36')),
 ('Emily', 'Bread', 'NY', Decimal('1281.50'), Decimal('1597.50'), Decimal('2716.68')),
 ('Emily', 'Bread', 'PA', Decimal('1393.00'), Decimal('1594.86'), Decimal('2254.29')),
 ('Emily', 'Butter', 'CT', Decimal('1843.75'), Decimal('2695.40'), Decimal('2798.76')),
 ('Emily', 'Butter', 'NJ', Decimal('2576.00'), Decimal('2242.86'), Decimal('2646.63')),
 ('Emily', 'Butter', 'NY', Decimal('2826.00'), Decimal('2253.25'), Decimal('2587.13')),
 ('Emily', 'Butter', 'PA', Decimal('2749.50'), Decimal('2193.29'), Decimal('2091.82')),
 ('Emily', 'Coke', 'CT', Decimal('2456.33'), Decimal('2385.33'), Decimal('2671.82')),
 ('Emily', 'Coke', 'NJ', Decimal('2269.00'), Decimal('2479.00'), Decimal('2689.74')),
 ('Emily', 'Coke', 'NY', Decimal('2501.67'), Decimal('2362.67'), Decimal('2610.71')),
 ('Emily', 'Cookies', 'CT', Decimal('3962.33'), Decimal('2375.23'), Decimal('2466.45')),
 ('Emily', 'Cookies', 'NJ', Decimal('1774.80'), Decimal('3081.00'), Decimal('2847.48')),
 ('Emily', 'Cookies', 'NY', Decimal('2463.50'), Decimal('2742.58'), Decimal('2623.80')),
 ('Emily', 'Cookies', 'PA', Decimal('3037.50'), Decimal('2551.25'), Decimal('1968.45')),
 ('Emily', 'Eggs', 'CT', Decimal('2722.00'), Decimal('2759.82'), Decimal('2642.79')),
 ('Emily', 'Eggs', 'NJ', Decimal('3845.00'), Decimal('2212.50'), Decimal('2422.32')),
 ('Emily', 'Eggs', 'NY', Decimal('2787.00'), Decimal('2746.56'), Decimal('2569.95')),
 ('Emily', 'Eggs', 'PA', Decimal('1654.25'), Decimal('3307.88'), Decimal('2245.10')),
 ('Emily', 'Fruits', 'CT', Decimal('3055.00'), Decimal('2667.00'), Decimal('2628.92')),
 ('Emily', 'Fruits', 'NJ', Decimal('4056.00'), Decimal('2449.73'), Decimal('2523.29')),
 ('Emily', 'Fruits', 'NY', Decimal('2463.00'), Decimal('2800.78'), Decimal('2623.90')),
 ('Emily', 'Fruits', 'PA', Decimal('2340.00'), Decimal('3002.71'), Decimal('2082.17')),
 ('Emily', 'Milk', 'CT', Decimal('1957.33'), Decimal('3087.00'), Decimal('2739.86')),
 ('Emily', 'Milk', 'NJ', Decimal('3839.00'), Decimal('2495.43'), Decimal('2593.28')),
 ('Emily', 'Milk', 'NY', Decimal('4986.00'), Decimal('2331.57'), Decimal('2493.22')),
 ('Emily', 'Milk', 'PA', Decimal('2203.33'), Decimal('2939.40'), Decimal('2138.52')),
 ('Emily', 'Pepsi', 'CT', Decimal('4356.67'), Decimal('2428.00'), Decimal('2412.68')),
 ('Emily', 'Pepsi', 'NJ', Decimal('2591.00'), Decimal('3365.17'), Decimal('2643.20')),
 ('Emily', 'Pepsi', 'NY', Decimal('2719.50'), Decimal('3468.60'), Decimal('2585.95')),
 ('Emily', 'Pepsi', 'PA', Decimal('1682.00'), Decimal('3516.67'), Decimal('2166.83')),
 ('Emily', 'Soap', 'CT', Decimal('2241.67'), Decimal('2513.00'), Decimal('2701.09')),
 ('Emily', 'Soap', 'NJ', Decimal('2868.33'), Decimal('2137.00'), Decimal('2611.57')),
 ('Emily', 'Soap', 'NY', Decimal('3218.00'), Decimal('2296.00'), Decimal('2570.09')),
 ('Emily', 'Soap', 'PA', Decimal('742.00'), Decimal('2649.71'), Decimal('2207.70')),
 ('Emily', 'Yogurt', 'CT', Decimal('2149.33'), Decimal('2515.50'), Decimal('2713.68')),
 ('Emily', 'Yogurt', 'NJ', Decimal('2336.00'), Decimal('2362.33'), Decimal('2653.40')),
 ('Emily', 'Yogurt', 'NY', Decimal('2575.33'), Decimal('2196.00'), Decimal('2600.19')),
 ('Helen', 'Bread', 'CT', Decimal('3016.67'), Decimal('2663.67'), Decimal('2208.61')),
 ('Helen', 'Bread', 'NJ', Decimal('2100.00'), Decimal('2976.00'), Decimal('2375.21')),
 ('Helen', 'Bread', 'NY', Decimal('3381.67'), Decimal('2481.17'), Decimal('2235.54')),
 ('Helen', 'Bread', 'PA', Decimal('1637.00'), Decimal('2924.38'), Decimal('2199.61')),
 ('Helen', 'Butter', 'CT', Decimal('306.00'), Decimal('1985.10'), Decimal('2339.73')),
 ('Helen', 'Butter', 'NJ', Decimal('1708.44'), Decimal('2047.46'), Decimal('2634.76')),
 ('Helen', 'Butter', 'NY', Decimal('2685.29'), Decimal('1546.40'), Decimal('2248.73')),
 ('Helen', 'Butter', 'PA', Decimal('1502.80'), Decimal('2028.18'), Decimal('2408.29')),
 ('Helen', 'Coke', 'CT', Decimal('2648.43'), Decimal('2590.50'), Decimal('2184.37')),
 ('Helen', 'Coke', 'NJ', Decimal('2904.60'), Decimal('2474.00'), Decimal('2247.32')),
 ('Helen', 'Coke', 'NY', Decimal('1534.50'), Decimal('2784.15'), Decimal('2414.81')),
 ('Helen', 'Coke', 'PA', Decimal('3132.00'), Decimal('2580.79'), Decimal('2116.56')),
 ('Helen', 'Cookies', 'CT', Decimal('1179.00'), Decimal('2179.67'), Decimal('2348.72')),
 ('Helen', 'Cookies', 'NJ', Decimal('1965.00'), Decimal('1733.00'), Decimal('2370.38')),
 ('Helen', 'Cookies', 'NY', Decimal('2287.00'), Decimal('1441.00'), Decimal('2359.07')),
 ('Helen', 'Eggs', 'CT', Decimal('2301.50'), Decimal('1968.75'), Decimal('2277.03')),
 ('Helen', 'Eggs', 'NY', Decimal('3200.00'), Decimal('1983.00'), Decimal('2323.89')),
 ('Helen', 'Eggs', 'PA', Decimal('1558.33'), Decimal('2481.20'), Decimal('2284.69')),
 ('Helen', 'Fruits', 'CT', Decimal('1760.17'), Decimal('2000.00'), Decimal('2391.29')),
 ('Helen', 'Fruits', 'NJ', Decimal('415.00'), Decimal('2018.25'), Decimal('2423.83')),
 ('Helen', 'Fruits', 'NY', Decimal('2774.00'), Decimal('1723.38'), Decimal('2339.11')),
 ('Helen', 'Fruits', 'PA', Decimal('2811.00'), Decimal('1718.75'), Decimal('2134.39')),
 ('Helen', 'Milk', 'CT', Decimal('1962.67'), Decimal('2150.11'), Decimal('2310.61')),
 ('Helen', 'Milk', 'NJ', Decimal('1839.00'), Decimal('2127.27'), Decimal('2374.72')),
 ('Helen', 'Milk', 'NY', Decimal('1589.40'), Decimal('2470.29'), Decimal('2513.42')),
 ('Helen', 'Milk', 'PA', Decimal('3188.33'), Decimal('1741.56'), Decimal('1979.06')),
 ('Helen', 'Pepsi', 'CT', Decimal('2630.67'), Decimal('2672.10'), Decimal('2245.97')),
 ('Helen', 'Pepsi', 'NJ', Decimal('3267.00'), Decimal('2284.75'), Decimal('2174.84')),
 ('Helen', 'Pepsi', 'NY', Decimal('2507.67'), Decimal('2709.00'), Decimal('2336.38')),
 ('Helen', 'Pepsi', 'PA', Decimal('1431.50'), Decimal('2886.36'), Decimal('2256.88')),
 ('Helen', 'Soap', 'CT', Decimal('1752.00'), Decimal('2712.71'), Decimal('2312.91')),
 ('Helen', 'Soap', 'NJ', Decimal('2791.40'), Decimal('2134.00'), Decimal('2269.96')),
 ('Helen', 'Soap', 'PA', Decimal('2516.00'), Decimal('2494.43'), Decimal('2129.29')),
 ('Helen', 'Yogurt', 'CT', Decimal('3404.33'), Decimal('2333.86'), Decimal('2171.10')),
 ('Helen', 'Yogurt', 'NJ', Decimal('2096.00'), Decimal('2717.11'), Decimal('2365.86')),
 ('Helen', 'Yogurt', 'NY', Decimal('2048.00'), Decimal('3262.00'), Decimal('2417.88')),
 ('Helen', 'Yogurt', 'PA', Decimal('4001.00'), Decimal('2505.44'), Decimal('2068.28')),
 ('Knuth', 'Bread', 'CT', Decimal('2561.17'), Decimal('2865.83'), Decimal('1949.77')),
 ('Knuth', 'Bread', 'NJ', Decimal('1013.00'), Decimal('2868.09'), Decimal('2324.67')),
 ('Knuth', 'Bread', 'NY', Decimal('3370.00'), Decimal('2653.82'), Decimal('2459.35')),
 ('Knuth', 'Bread', 'PA', Decimal('3203.00'), Decimal('2468.75'), Decimal('2330.88')),
 ('Knuth', 'Butter', 'CT', Decimal('2232.00'), Decimal('1062.60'), Decimal('2059.00')),
 ('Knuth', 'Butter', 'NY', Decimal('648.33'), Decimal('1866.67'), Decimal('2811.78')),
 ('Knuth', 'Butter', 'PA', Decimal('1684.00'), Decimal('1044.25'), Decimal('2508.00')),
 ('Knuth', 'Coke', 'CT', Decimal('2113.75'), Decimal('2999.33'), Decimal('2057.36')),
 ('Knuth', 'Coke', 'NJ', Decimal('2340.33'), Decimal('2842.80'), Decimal('2239.75')),
 ('Knuth', 'Coke', 'NY', Decimal('1946.00'), Decimal('2791.92'), Decimal('2530.55')),
 ('Knuth', 'Coke', 'PA', Decimal('3605.40'), Decimal('2177.75'), Decimal('2210.71')),
 ('Knuth', 'Cookies', 'CT', Decimal('3350.67'), Decimal('2289.86'), Decimal('1931.34')),
 ('Knuth', 'Cookies', 'NJ', Decimal('3172.25'), Decimal('2232.00'), Decimal('2011.20')),
 ('Knuth', 'Cookies', 'NY', Decimal('1485.00'), Decimal('2732.89'), Decimal('2553.60')),
 ('Knuth', 'Cookies', 'PA', Decimal('927.50'), Decimal('3028.25'), Decimal('2564.04')),
 ('Knuth', 'Eggs', 'CT', Decimal('2432.50'), Decimal('2608.50'), Decimal('2011.82')),
 ('Knuth', 'Eggs', 'NJ', Decimal('1846.00'), Decimal('2711.13'), Decimal('2303.82')),
 ('Knuth', 'Eggs', 'NY', Decimal('4050.50'), Decimal('2160.00'), Decimal('2339.79')),
 ('Knuth', 'Eggs', 'PA', Decimal('1929.00'), Decimal('2690.38'), Decimal('2489.85')),
 ('Knuth', 'Fruits', 'CT', Decimal('1629.33'), Decimal('1907.55'), Decimal('2109.41')),
 ('Knuth', 'Fruits', 'NJ', Decimal('2013.33'), Decimal('1802.82'), Decimal('2301.06')),
 ('Knuth', 'Fruits', 'NY', Decimal('1251.75'), Decimal('2086.40'), Decimal('2797.06')),
 ('Knuth', 'Fruits', 'PA', Decimal('2484.00'), Decimal('1593.50'), Decimal('2445.92')),
 ('Knuth', 'Milk', 'CT', Decimal('58.00'), Decimal('1212.67'), Decimal('2129.13')),
 ('Knuth', 'Milk', 'NY', Decimal('2424.00'), Decimal('424.00'), Decimal('2506.65')),
 ('Knuth', 'Milk', 'PA', Decimal('607.00'), Decimal('1241.00'), Decimal('2587.78')),
 ('Knuth', 'Pepsi', 'CT', Decimal('1784.50'), Decimal('3029.22'), Decimal('2104.39')),
 ('Knuth', 'Pepsi', 'NJ', Decimal('2394.50'), Decimal('2758.11'), Decimal('2218.60')),
 ('Knuth', 'Pepsi', 'NY', Decimal('4252.33'), Decimal('2164.40'), Decimal('2211.11')),
 ('Knuth', 'Pepsi', 'PA', Decimal('2464.00'), Decimal('2679.36'), Decimal('2450.22')),
 ('Knuth', 'Soap', 'CT', Decimal('1568.00'), Decimal('2096.00'), Decimal('2156.33')),
 ('Knuth', 'Soap', 'NJ', Decimal('657.00'), Decimal('1975.90'), Decimal('2344.44')),
 ('Knuth', 'Soap', 'NY', Decimal('2790.67'), Decimal('1505.50'), Decimal('2454.72')),
 ('Knuth', 'Soap', 'PA', Decimal('1773.50'), Decimal('1874.33'), Decimal('2501.37')),
 ('Knuth', 'Yogurt', 'CT', Decimal('301.00'), Decimal('2979.43'), Decimal('2121.29')),
 ('Knuth', 'Yogurt', 'NJ', Decimal('2167.00'), Decimal('2712.86'), Decimal('2260.56')),
 ('Knuth', 'Yogurt', 'NY', Decimal('3575.00'), Decimal('2334.50'), Decimal('2389.84')),
 ('Knuth', 'Yogurt', 'PA', Decimal('2884.75'), Decimal('2404.50'), Decimal('2381.80')),
 ('Sam', 'Bread', 'CT', Decimal('903.00'), Decimal('1936.83'), Decimal('2139.89')),
 ('Sam', 'Bread', 'NJ', Decimal('2791.33'), Decimal('1010.60'), Decimal('2558.83')),
 ('Sam', 'Bread', 'NY', Decimal('2282.00'), Decimal('1592.14'), Decimal('2435.70')),
 ('Sam', 'Bread', 'PA', Decimal('482.50'), Decimal('2077.00'), Decimal('2605.96')),
 ('Sam', 'Butter', 'NJ', Decimal('3211.50'), Decimal('2191.50'), Decimal('2471.86')),
 ('Sam', 'Butter', 'NY', Decimal('2697.67'), Decimal('2703.80'), Decimal('2383.50')),
 ('Sam', 'Butter', 'PA', Decimal('673.00'), Decimal('2991.29'), Decimal('2509.54')),
 ('Sam', 'Coke', 'CT', Decimal('2745.50'), Decimal('1954.33'), Decimal('1935.17')),
 ('Sam', 'Coke', 'NY', Decimal('1405.00'), Decimal('2848.00'), Decimal('2536.11')),
 ('Sam', 'Coke', 'PA', Decimal('3053.00'), Decimal('2075.25'), Decimal('2410.38')),
 ('Sam', 'Cookies', 'CT', Decimal('1327.50'), Decimal('1914.80'), Decimal('2092.72')),
 ('Sam', 'Cookies', 'NY', Decimal('3376.00'), Decimal('1475.50'), Decimal('2381.00')),
 ('Sam', 'Cookies', 'PA', Decimal('1549.50'), Decimal('2010.33'), Decimal('2604.95')),
 ('Sam', 'Eggs', 'NJ', Decimal('1102.50'), Decimal('2795.33'), Decimal('2709.25')),
 ('Sam', 'Eggs', 'NY', Decimal('2174.67'), Decimal('2490.60'), Decimal('2470.67')),
 ('Sam', 'Eggs', 'PA', Decimal('3416.00'), Decimal('1745.80'), Decimal('2302.45')),
 ('Sam', 'Fruits', 'CT', Decimal('3100.50'), Decimal('3459.75'), Decimal('1895.72')),
 ('Sam', 'Fruits', 'NJ', Decimal('3282.33'), Decimal('3433.14'), Decimal('2494.78')),
 ('Sam', 'Fruits', 'NY', Decimal('3573.50'), Decimal('3341.50'), Decimal('2307.84')),
 ('Sam', 'Fruits', 'PA', Decimal('3561.33'), Decimal('3313.57'), Decimal('2282.64')),
 ('Sam', 'Milk', 'CT', Decimal('1423.20'), Decimal('2059.13'), Decimal('2213.87')),
 ('Sam', 'Milk', 'NJ', Decimal('4522.00'), Decimal('1588.92'), Decimal('2508.20')),
 ('Sam', 'Milk', 'NY', Decimal('1600.75'), Decimal('1909.56'), Decimal('2623.12')),
 ('Sam', 'Milk', 'PA', Decimal('1849.33'), Decimal('1804.10'), Decimal('2516.09')),
 ('Sam', 'Pepsi', 'CT', Decimal('2375.75'), Decimal('3260.56'), Decimal('1926.31')),
 ('Sam', 'Pepsi', 'NJ', Decimal('3086.33'), Decimal('2904.29'), Decimal('2435.45')),
 ('Sam', 'Pepsi', 'NY', Decimal('3993.00'), Decimal('2805.64'), Decimal('2263.68')),
 ('Sam', 'Pepsi', 'PA', Decimal('2841.00'), Decimal('3000.58'), Decimal('2419.21')),
 ('Sam', 'Soap', 'CT', Decimal('2461.00'), Decimal('2175.40'), Decimal('1992.79')),
 ('Sam', 'Soap', 'NJ', Decimal('1348.25'), Decimal('2688.86'), Decimal('2810.64')),
 ('Sam', 'Soap', 'NY', Decimal('2529.00'), Decimal('2128.56'), Decimal('2417.79')),
 ('Sam', 'Soap', 'PA', Decimal('2825.75'), Decimal('1844.57'), Decimal('2361.86')),
 ('Sam', 'Yogurt', 'CT', Decimal('2545.50'), Decimal('2318.29'), Decimal('1957.39')),
 ('Sam', 'Yogurt', 'NJ', Decimal('1840.67'), Decimal('2632.83'), Decimal('2682.83')),
 ('Sam', 'Yogurt', 'NY', Decimal('1317.00'), Decimal('2500.25'), Decimal('2483.95')),
 ('Sam', 'Yogurt', 'PA', Decimal('3129.67'), Decimal('1988.33'), Decimal('2341.50'))]

<br>

2.For customer and product, show the average sales before and after each quarter (e.g., for Q2, show average sales of Q1 and Q3. For “before” Q1 and “after” Q4, display <NULL>. The “YEAR” attribute is not considered for this query – for example, both Q1 of 2007 and Q1 of 2008 are considered Q1 regardless of the year.

In [123]:
%%sql
With
t_all_month AS(
SELECT DISTINCT s1.prod, s1.cust,
case when s2.month in (1,2,3) then 1
     when s2.month in (4,5,6) then 2
     when s2.month in (7,8,9) then 3
     when s2.month in (10,11,12) then 4 END AS Q
FROM sales s1, sales s2
-- ORDER BY 1,2,3
),


t1 AS (
SELECT prod, cust, ROUND(AVG(quant)) AS avq,
case when month in (1,2,3) then 1
     when month in (4,5,6) then 2
     when month in (7,8,9) then 3
     when month in (10,11,12) then 4 END AS Q
FROM sales
GROUP BY prod, cust, Q
),


tbf AS(
SELECT t1.prod, t1.cust, bf.Q, bf.avq as bfq
FROM t1
LEFT JOIN t1 bf ON t1.cust = bf.cust AND t1.prod = bf.prod AND t1.Q-1 = bf.Q
-- WHERE t1.prod='Bread' and t1.cust='Bloom'
),


taf AS
(
SELECT t1.prod, t1.cust, af.Q, af.avq as afq
FROM t1
LEFT JOIN t1 af ON t1.cust = af.cust AND t1.prod = af.prod AND t1.Q+1 = af.Q
-- WHERE t1.prod='Bread' and t1.cust='Bloom'
)




SELECT ta.prod,  ta.cust,  ta.Q,
-- t1.avq, -- USED for checking
bfq as BEFORE_AVG, afq as AFTER_AVG
FROM t_all_month ta
LEFT JOIN t1 on ta.prod = t1.prod AND ta.cust = t1.cust AND ta.Q = t1.Q  -- keep 200 rows, this is neccessary
LEFT JOIN tbf ON t1.Q = tbf.Q+1 AND t1.cust = tbf.cust AND t1.prod = tbf.prod  -- NEED to add back month difference
LEFT JOIN taf ON t1.Q = taf.Q-1 AND t1.cust = taf.cust AND t1.prod = taf.prod
-- WHERE t1.prod='Bread' and t1.cust='Bloom'
ORDER BY 1,2,3

 * postgresql://postgres:***@127.0.0.1/salesdb
200 rows affected.

[('Bread', 'Bloom', 1, None, Decimal('539')),
 ('Bread', 'Bloom', 2, Decimal('3267'), Decimal('2388')),
 ('Bread', 'Bloom', 3, Decimal('539'), Decimal('1106')),
 ('Bread', 'Bloom', 4, Decimal('2388'), None),
 ('Bread', 'Emily', 1, None, Decimal('1720')),
 ('Bread', 'Emily', 2, Decimal('492'), Decimal('807')),
 ('Bread', 'Emily', 3, Decimal('1720'), Decimal('2318')),
 ('Bread', 'Emily', 4, Decimal('807'), None),
 ('Bread', 'Helen', 1, None, Decimal('2648')),
 ('Bread', 'Helen', 2, Decimal('3530'), None),
 ('Bread', 'Helen', 3, None, None),
 ('Bread', 'Helen', 4, None, None),
 ('Bread', 'Knuth', 1, None, Decimal('3283')),
 ('Bread', 'Knuth', 2, Decimal('3366'), Decimal('1579')),
 ('Bread', 'Knuth', 3, Decimal('3283'), Decimal('1405')),
 ('Bread', 'Knuth', 4, Decimal('1579'), None),
 ('Bread', 'Sam', 1, None, Decimal('2735')),
 ('Bread', 'Sam', 2, Decimal('1378'), Decimal('1622')),
 ('Bread', 'Sam', 3, Decimal('2735'), Decimal('93')),
 ('Bread', 'Sam', 4, Decimal('1622'), None),
 ('Butter', 'Bloom', 1, None, None),
 ('Butter', 'Bloom', 2, None, None),
 ('Butter', 'Bloom', 3, None, Decimal('4279')),
 ('Butter', 'Bloom', 4, Decimal('2386'), None),
 ('Butter', 'Emily', 1, None, Decimal('2869')),
 ('Butter', 'Emily', 2, Decimal('1490'), Decimal('3053')),
 ('Butter', 'Emily', 3, Decimal('2869'), Decimal('2862')),
 ('Butter', 'Emily', 4, Decimal('3053'), None),
 ('Butter', 'Helen', 1, None, Decimal('2886')),
 ('Butter', 'Helen', 2, Decimal('2040'), Decimal('1913')),
 ('Butter', 'Helen', 3, Decimal('2886'), Decimal('907')),
 ('Butter', 'Helen', 4, Decimal('1913'), None),
 ('Butter', 'Knuth', 1, None, Decimal('895')),
 ('Butter', 'Knuth', 2, Decimal('1374'), None),
 ('Butter', 'Knuth', 3, None, None),
 ('Butter', 'Knuth', 4, None, None),
 ('Butter', 'Sam', 1, None, Decimal('4056')),
 ('Butter', 'Sam', 2, Decimal('673'), Decimal('4893')),
 ('Butter', 'Sam', 3, Decimal('4056'), Decimal('1984')),
 ('Butter', 'Sam', 4, Decimal('4893'), None),
 ('Coke', 'Bloom', 1, None, Decimal('2681')),
 ('Coke', 'Bloom', 2, Decimal('1079'), Decimal('2669')),
 ('Coke', 'Bloom', 3, Decimal('2681'), Decimal('2867')),
 ('Coke', 'Bloom', 4, Decimal('2669'), None),
 ('Coke', 'Emily', 1, None, Decimal('3314')),
 ('Coke', 'Emily', 2, Decimal('2398'), Decimal('4379')),
 ('Coke', 'Emily', 3, Decimal('3314'), Decimal('999')),
 ('Coke', 'Emily', 4, Decimal('4379'), None),
 ('Coke', 'Helen', 1, None, Decimal('1999')),
 ('Coke', 'Helen', 2, Decimal('2708'), Decimal('2800')),
 ('Coke', 'Helen', 3, Decimal('1999'), Decimal('3109')),
 ('Coke', 'Helen', 4, Decimal('2800'), None),
 ('Coke', 'Knuth', 1, None, Decimal('2676')),
 ('Coke', 'Knuth', 2, Decimal('3559'), Decimal('1512')),
 ('Coke', 'Knuth', 3, Decimal('2676'), Decimal('2789')),
 ('Coke', 'Knuth', 4, Decimal('1512'), None),
 ('Coke', 'Sam', 1, None, Decimal('1481')),
 ('Coke', 'Sam', 2, Decimal('2670'), Decimal('3053')),
 ('Coke', 'Sam', 3, Decimal('1481'), None),
 ('Coke', 'Sam', 4, None, None),
 ('Cookies', 'Bloom', 1, None, None),
 ('Cookies', 'Bloom', 2, None, Decimal('3287')),
 ('Cookies', 'Bloom', 3, Decimal('2782'), Decimal('2970')),
 ('Cookies', 'Bloom', 4, Decimal('3287'), None),
 ('Cookies', 'Emily', 1, None, Decimal('3760')),
 ('Cookies', 'Emily', 2, Decimal('3131'), Decimal('1716')),
 ('Cookies', 'Emily', 3, Decimal('3760'), Decimal('2421')),
 ('Cookies', 'Emily', 4, Decimal('1716'), None),
 ('Cookies', 'Helen', 1, None, None),
 ('Cookies', 'Helen', 2, None, None),
 ('Cookies', 'Helen', 3, None, Decimal('1179')),
 ('Cookies', 'Helen', 4, Decimal('2180'), None),
 ('Cookies', 'Knuth', 1, None, Decimal('2978')),
 ('Cookies', 'Knuth', 2, Decimal('2363'), Decimal('3709')),
 ('Cookies', 'Knuth', 3, Decimal('2978'), Decimal('1669')),
 ('Cookies', 'Knuth', 4, Decimal('3709'), None),
 ('Cookies', 'Sam', 1, None, Decimal('408')),
 ('Cookies', 'Sam', 2, Decimal('2523'), None),
 ('Cookies', 'Sam', 3, None, None),
 ('Cookies', 'Sam', 4, None, None),
 ('Eggs', 'Bloom', 1, None, Decimal('3597')),
 ('Eggs', 'Bloom', 2, Decimal('2819'), Decimal('2185')),
 ('Eggs', 'Bloom', 3, Decimal('3597'), Decimal('1053')),
 ('Eggs', 'Bloom', 4, Decimal('2185'), None),
 ('Eggs', 'Emily', 1, None, Decimal('2715')),
 ('Eggs', 'Emily', 2, Decimal('4535'), Decimal('3231')),
 ('Eggs', 'Emily', 3, Decimal('2715'), Decimal('2039')),
 ('Eggs', 'Emily', 4, Decimal('3231'), None),
 ('Eggs', 'Helen', 1, None, Decimal('2327')),
 ('Eggs', 'Helen', 2, Decimal('813'), None),
 ('Eggs', 'Helen', 3, None, None),
 ('Eggs', 'Helen', 4, None, None),
 ('Eggs', 'Knuth', 1, None, Decimal('1239')),
 ('Eggs', 'Knuth', 2, Decimal('4051'), Decimal('3532')),
 ('Eggs', 'Knuth', 3, Decimal('1239'), Decimal('2254')),
 ('Eggs', 'Knuth', 4, Decimal('3532'), None),
 ('Eggs', 'Sam', 1, None, Decimal('2239')),
 ('Eggs', 'Sam', 2, Decimal('2482'), Decimal('1191')),
 ('Eggs', 'Sam', 3, Decimal('2239'), Decimal('4674')),
 ('Eggs', 'Sam', 4, Decimal('1191'), None),
 ('Fruits', 'Bloom', 1, None, Decimal('1933')),
 ('Fruits', 'Bloom', 2, Decimal('2243'), Decimal('2994')),
 ('Fruits', 'Bloom', 3, Decimal('1933'), Decimal('2926')),
 ('Fruits', 'Bloom', 4, Decimal('2994'), None),
 ('Fruits', 'Emily', 1, None, Decimal('2243')),
 ('Fruits', 'Emily', 2, Decimal('2919'), Decimal('2750')),
 ('Fruits', 'Emily', 3, Decimal('2243'), Decimal('2873')),
 ('Fruits', 'Emily', 4, Decimal('2750'), None),
 ('Fruits', 'Helen', 1, None, Decimal('2000')),
 ('Fruits', 'Helen', 2, Decimal('1570'), None),
 ('Fruits', 'Helen', 3, None, None),
 ('Fruits', 'Helen', 4, None, None),
 ('Fruits', 'Knuth', 1, None, Decimal('1857')),
 ('Fruits', 'Knuth', 2, Decimal('2758'), Decimal('1175')),
 ('Fruits', 'Knuth', 3, Decimal('1857'), Decimal('2279')),
 ('Fruits', 'Knuth', 4, Decimal('1175'), None),
 ('Fruits', 'Sam', 1, None, None),
 ('Fruits', 'Sam', 2, None, Decimal('3611')),
 ('Fruits', 'Sam', 3, Decimal('3743'), Decimal('3217')),
 ('Fruits', 'Sam', 4, Decimal('3611'), None),
 ('Milk', 'Bloom', 1, None, Decimal('2377')),
 ('Milk', 'Bloom', 2, Decimal('3215'), Decimal('1106')),
 ('Milk', 'Bloom', 3, Decimal('2377'), Decimal('3010')),
 ('Milk', 'Bloom', 4, Decimal('1106'), None),
 ('Milk', 'Emily', 1, None, Decimal('2581')),
 ('Milk', 'Emily', 2, Decimal('2589'), Decimal('1997')),
 ('Milk', 'Emily', 3, Decimal('2581'), Decimal('4986')),
 ('Milk', 'Emily', 4, Decimal('1997'), None),
 ('Milk', 'Helen', 1, None, Decimal('807')),
 ('Milk', 'Helen', 2, Decimal('3312'), Decimal('3314')),
 ('Milk', 'Helen', 3, Decimal('807'), Decimal('981')),
 ('Milk', 'Helen', 4, Decimal('3314'), None),
 ('Milk', 'Knuth', 1, None, Decimal('2424')),
 ('Milk', 'Knuth', 2, Decimal('92'), None),
 ('Milk', 'Knuth', 3, None, None),
 ('Milk', 'Knuth', 4, None, None),
 ('Milk', 'Sam', 1, None, Decimal('598')),
 ('Milk', 'Sam', 2, Decimal('1745'), Decimal('2125')),
 ('Milk', 'Sam', 3, Decimal('598'), Decimal('2431')),
 ('Milk', 'Sam', 4, Decimal('2125'), None),
 ('Pepsi', 'Bloom', 1, None, Decimal('1868')),
 ('Pepsi', 'Bloom', 2, Decimal('526'), Decimal('794')),
 ('Pepsi', 'Bloom', 3, Decimal('1868'), Decimal('4374')),
 ('Pepsi', 'Bloom', 4, Decimal('794'), None),
 ('Pepsi', 'Emily', 1, None, Decimal('2374')),
 ('Pepsi', 'Emily', 2, Decimal('3842'), None),
 ('Pepsi', 'Emily', 3, None, None),
 ('Pepsi', 'Emily', 4, None, None),
 ('Pepsi', 'Helen', 1, None, Decimal('2397')),
 ('Pepsi', 'Helen', 2, Decimal('3130'), Decimal('2768')),
 ('Pepsi', 'Helen', 3, Decimal('2397'), Decimal('2435')),
 ('Pepsi', 'Helen', 4, Decimal('2768'), None),
 ('Pepsi', 'Knuth', 1, None, Decimal('2468')),
 ('Pepsi', 'Knuth', 2, Decimal('3214'), Decimal('2982')),
 ('Pepsi', 'Knuth', 3, Decimal('2468'), Decimal('1596')),
 ('Pepsi', 'Knuth', 4, Decimal('2982'), None),
 ('Pepsi', 'Sam', 1, None, Decimal('2332')),
 ('Pepsi', 'Sam', 2, Decimal('2442'), Decimal('3954')),
 ('Pepsi', 'Sam', 3, Decimal('2332'), Decimal('3166')),
 ('Pepsi', 'Sam', 4, Decimal('3954'), None),
 ('Soap', 'Bloom', 1, None, Decimal('2310')),
 ('Soap', 'Bloom', 2, Decimal('4623'), Decimal('329')),
 ('Soap', 'Bloom', 3, Decimal('2310'), Decimal('4364')),
 ('Soap', 'Bloom', 4, Decimal('329'), None),
 ('Soap', 'Emily', 1, None, Decimal('2549')),
 ('Soap', 'Emily', 2, Decimal('3218'), Decimal('1531')),
 ('Soap', 'Emily', 3, Decimal('2549'), Decimal('2976')),
 ('Soap', 'Emily', 4, Decimal('1531'), None),
 ('Soap', 'Helen', 1, None, None),
 ('Soap', 'Helen', 2, None, None),
 ('Soap', 'Helen', 3, None, Decimal('1209')),
 ('Soap', 'Helen', 4, Decimal('2990'), None),
 ('Soap', 'Knuth', 1, None, Decimal('1519')),
 ('Soap', 'Knuth', 2, Decimal('878'), Decimal('1002')),
 ('Soap', 'Knuth', 3, Decimal('1519'), Decimal('2620')),
 ('Soap', 'Knuth', 4, Decimal('1002'), None),
 ('Soap', 'Sam', 1, None, Decimal('2878')),
 ('Soap', 'Sam', 2, Decimal('1994'), Decimal('3108')),
 ('Soap', 'Sam', 3, Decimal('2878'), Decimal('694')),
 ('Soap', 'Sam', 4, Decimal('3108'), None),
 ('Yogurt', 'Bloom', 1, None, Decimal('2623')),
 ('Yogurt', 'Bloom', 2, Decimal('1660'), Decimal('2398')),
 ('Yogurt', 'Bloom', 3, Decimal('2623'), Decimal('1786')),
 ('Yogurt', 'Bloom', 4, Decimal('2398'), None),
 ('Yogurt', 'Emily', 1, None, Decimal('2650')),
 ('Yogurt', 'Emily', 2, Decimal('3079'), Decimal('2161')),
 ('Yogurt', 'Emily', 3, Decimal('2650'), Decimal('730')),
 ('Yogurt', 'Emily', 4, Decimal('2161'), None),
 ('Yogurt', 'Helen', 1, None, Decimal('3174')),
 ('Yogurt', 'Helen', 2, Decimal('2332'), Decimal('2904')),
 ('Yogurt', 'Helen', 3, Decimal('3174'), Decimal('2247')),
 ('Yogurt', 'Helen', 4, Decimal('2904'), None),
 ('Yogurt', 'Knuth', 1, None, Decimal('1787')),
 ('Yogurt', 'Knuth', 2, Decimal('3903'), Decimal('3705')),
 ('Yogurt', 'Knuth', 3, Decimal('1787'), Decimal('2497')),
 ('Yogurt', 'Knuth', 4, Decimal('3705'), None),
 ('Yogurt', 'Sam', 1, None, Decimal('2735')),
 ('Yogurt', 'Sam', 2, Decimal('2126'), Decimal('2000')),
 ('Yogurt', 'Sam', 3, Decimal('2735'), None),
 ('Yogurt', 'Sam', 4, None, None)]

<br>

<br>

3.For each product, find the median sales quantity (assume an odd number of sales for simplicity of presentation). (NOTE – “median” is defined as “denoting or relating to a value or quantity lying at the midpoint of a frequency distribution of observed values or quantities, such that there is an equal probability of falling above or below it.” E.g., Median value of the list {13, 23, 12, 16, 15, 9, 29} is 15.

In [39]:
%%sql
SELECT
    prod,
    percentile_disc(0.5) WITHIN GROUP (ORDER BY quant) AS median_quant
FROM sales
GROUP BY prod
ORDER BY prod

 * postgresql://postgres:***@127.0.0.1/salesdb
10 rows affected.

[('Bread', 1932),
 ('Butter', 1715),
 ('Coke', 2681),
 ('Cookies', 2500),
 ('Eggs', 2151),
 ('Fruits', 2525),
 ('Milk', 1839),
 ('Pepsi', 2591),
 ('Soap', 2231),
 ('Yogurt', 2336)]

<br>

<br>

4.For customer and product, find the month by which time, 2/3 of the sales quantities have been purchased. Again, for this query, the “YEAR” attribute is not considered. Another way to view this query is to pretend all 500 rows of sales data are from the same year.

In [120]:
%%sql
with t1 as (
    select cust,prod,month,sum(quant)
    from sales
    group by cust, prod,month 
    order by cust, prod,month asc
),
t2 as (
    select b.cust, b.prod, b.month, sum(a.sum) as add_quant
    from t1 as a, t1 as b
    where a.cust=b.cust
    and a.prod=b.prod
    and a.month<=b.month
    group by b.cust, b.prod, b.month
    order by b.cust, b.prod, b.month
),
t3 as (
    select cust, prod, max(add_quant)*2/3 as the_two_third_amount
    from t2 
    group by cust, prod
    order by cust, prod
)
select a.cust, a.prod,min(b.month) as two_third_purchased_by_month
from t2 as b,t3 as a
where a.cust=b.cust
and a.prod=b.prod
and add_quant>=the_two_third_amount
group by a.cust, a.prod
order by a.cust, a.prod

 * postgresql://postgres:***@127.0.0.1/salesdb
50 rows affected.

[('Bloom', 'Bread', 8),
 ('Bloom', 'Butter', 10),
 ('Bloom', 'Coke', 7),
 ('Bloom', 'Cookies', 9),
 ('Bloom', 'Eggs', 5),
 ('Bloom', 'Fruits', 7),
 ('Bloom', 'Milk', 10),
 ('Bloom', 'Pepsi', 11),
 ('Bloom', 'Soap', 7),
 ('Bloom', 'Yogurt', 9),
 ('Emily', 'Bread', 9),
 ('Emily', 'Butter', 7),
 ('Emily', 'Coke', 6),
 ('Emily', 'Cookies', 11),
 ('Emily', 'Eggs', 9),
 ('Emily', 'Fruits', 8),
 ('Emily', 'Milk', 9),
 ('Emily', 'Pepsi', 5),
 ('Emily', 'Soap', 10),
 ('Emily', 'Yogurt', 6),
 ('Helen', 'Bread', 6),
 ('Helen', 'Butter', 7),
 ('Helen', 'Coke', 10),
 ('Helen', 'Cookies', 8),
 ('Helen', 'Eggs', 10),
 ('Helen', 'Fruits', 6),
 ('Helen', 'Milk', 4),
 ('Helen', 'Pepsi', 9),
 ('Helen', 'Soap', 8),
 ('Helen', 'Yogurt', 8),
 ('Knuth', 'Bread', 5),
 ('Knuth', 'Butter', 10),
 ('Knuth', 'Coke', 6),
 ('Knuth', 'Cookies', 7),
 ('Knuth', 'Eggs', 11),
 ('Knuth', 'Fruits', 7),
 ('Knuth', 'Milk', 4),
 ('Knuth', 'Pepsi', 9),
 ('Knuth', 'Soap', 11),
 ('Knuth', 'Yogurt', 6),
 ('Sam', 'Bread', 8),
 ('Sam', 'Butter', 10),
 ('Sam', 'Coke', 5),
 ('Sam', 'Cookies', 11),
 ('Sam', 'Eggs', 7),
 ('Sam', 'Fruits', 11),
 ('Sam', 'Milk', 8),
 ('Sam', 'Pepsi', 9),
 ('Sam', 'Soap', 6),
 ('Sam', 'Yogurt', 6)]

In [ ]:
select *
from sales

In [ ]:
with q1 as(
    select b.cust,b.prod,b.month,round(avg(b.quant),2)
    from (select cust,prod,month from sales where sales.month in(1,2,3)) as a
    left join sales as b
    on a.cust=b.cust
    and a.month <> b.month
    group by b.cust,b.prod,b.month
),

In [ ]:
%%sql
select cust,prod,state,quant
from sales
where cust='Bloom'
and prod='Pepsi'
and state='NY'

In [ ]:
%%sql
select cust, prod, state,round(avg(quant),2) as "AVG_Q"
from sales
group by cust, prod, state

In [ ]:
%%sql
with avg_all as(
    select cust, prod, state,round(avg(quant),2) as avg_q 
    from sales
    group by cust, prod, state
),
avg_no_PA as(
    select cust, prod, state,round(avg(quant),2) as avg_q 
    from sales
    group by cust, prod, state
    having state!='PA'
),
avg_no_NJ as(
    select cust, prod, state,round(avg(quant),2) as avg_q 
    from sales
    group by cust, prod, state
    having state!='NJ'
),
avg_no_CT as(
    select cust, prod, state,round(avg(quant),2) as avg_q 
    from sales
    group by cust, prod, state
    having state!='CT'
),
avg_no_NY as(
    select cust, prod, state,round(avg(quant),2) as avg_q 
    from sales
    group by cust, prod, state
    having state!='NY'
),
avg_other as(
select avg_all.cust,
from avg_all
inner join avg_no_PA on avg_all.cust=avg_no_PA.cust and avg_all.prod=avg_no_PA.prod
)

how many rows equla or less than me   #caculate mid

In [30]:
%%sql
SELECT
    prod,
    percentile_cont(0.1) WITHIN GROUP (ORDER BY quant) As cont_median,
    /*
    percentile_disc(0.5) WITHIN GROUP (ORDER BY score) AS disc_median,
    mode() WITHIN GROUP (ORDER BY score) AS mode,
    */
    COUNT(*) As num_scores
FROM sales
GROUP BY prod
ORDER BY prod

 * postgresql://postgres:***@127.0.0.1/salesdb
10 rows affected.

[('Bread', 256.0, 51),
 ('Butter', 453.0, 48),
 ('Coke', 755.0, 51),
 ('Cookies', 590.0, 47),
 ('Eggs', 804.6, 49),
 ('Fruits', 467.6, 63),
 ('Milk', 300.9, 50),
 ('Pepsi', 572.5, 54),
 ('Soap', 413.8, 45),
 ('Yogurt', 735.3, 42)]

In [31]:

select prod,count(prod)
from sales

 * postgresql://postgres:***@127.0.0.1/salesdb
(psycopg2.errors.GroupingError) column "sales.prod" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: select prod,count(prod)
               ^

[SQL: select prod,count(prod)
from sales]
(Background on this error at: http://sqlalche.me/e/f405)

In [32]:
%%sql
with t1 as(
    select prod,count(prod)/2
    from sales
    group by prod
)
select *
from sales
order by prod asc,quant asc

 * postgresql://postgres:***@127.0.0.1/salesdb
500 rows affected.

[('Emily', 'Bread', 28, 9, 2005, 'PA', 42),
 ('Sam', 'Bread', 13, 11, 2008, 'PA', 93),
 ('Emily', 'Bread', 21, 6, 2000, 'NJ', 141),
 ('Sam', 'Bread', 22, 7, 2006, 'CT', 207),
 ('Emily', 'Bread', 13, 5, 2001, 'NJ', 232),
 ('Bloom', 'Bread', 13, 6, 2000, 'CT', 256),
 ('Helen', 'Bread', 21, 5, 2000, 'NY', 389),
 ('Bloom', 'Bread', 20, 4, 2006, 'CT', 417),
 ('Emily', 'Bread', 21, 3, 2001, 'NY', 492),
 ('Sam', 'Bread', 7, 7, 2007, 'PA', 872),
 ('Bloom', 'Bread', 22, 6, 2008, 'NJ', 944),
 ('Knuth', 'Bread', 2, 11, 2002, 'NJ', 1013),
 ('Knuth', 'Bread', 16, 8, 2004, 'CT', 1095),
 ('Bloom', 'Bread', 3, 12, 2008, 'NJ', 1106),
 ('Sam', 'Bread', 18, 1, 2002, 'NJ', 1378),
 ('Helen', 'Bread', 26, 5, 2006, 'CT', 1406),
 ('Bloom', 'Bread', 4, 7, 2006, 'CT', 1494),
 ('Emily', 'Bread', 4, 9, 2000, 'PA', 1572),
 ('Sam', 'Bread', 29, 8, 2000, 'CT', 1599),
 ('Emily', 'Bread', 4, 6, 2001, 'CT', 1626),
 ('Helen', 'Bread', 15, 11, 2008, 'PA', 1637),
 ('Helen', 'Bread', 15, 6, 2003, 'NJ', 1687),
 ('Bloom', 'Bread', 4, 9, 2008, 'NJ', 1698),
 ('Knuth', 'Bread', 9, 10, 2002, 'CT', 1796),
 ('Knuth', 'Bread', 3, 2, 2004, 'CT', 1914),
 ('Knuth', 'Bread', 19, 6, 2005, 'PA', 1932),
 ('Knuth', 'Bread', 5, 8, 2000, 'CT', 2063),
 ('Emily', 'Bread', 23, 12, 2005, 'NY', 2071),
 ('Emily', 'Bread', 31, 4, 2008, 'NJ', 2135),
 ('Bloom', 'Bread', 22, 1, 2003, 'CT', 2220),
 ('Bloom', 'Bread', 5, 3, 2007, 'NJ', 2277),
 ('Sam', 'Bread', 11, 4, 2006, 'NY', 2282),
 ('Helen', 'Bread', 11, 10, 2007, 'NJ', 2513),
 ('Emily', 'Bread', 17, 11, 2001, 'PA', 2565),
 ('Knuth', 'Bread', 13, 1, 2002, 'PA', 3049),
 ('Bloom', 'Bread', 25, 8, 2004, 'PA', 3100),
 ('Sam', 'Bread', 13, 6, 2007, 'NJ', 3187),
 ('Bloom', 'Bread', 14, 9, 2007, 'CT', 3261),
 ('Knuth', 'Bread', 14, 4, 2002, 'NY', 3370),
 ('Helen', 'Bread', 24, 1, 2002, 'CT', 3530),
 ('Knuth', 'Bread', 7, 5, 2003, 'PA', 3664),
 ('Bloom', 'Bread', 13, 3, 2006, 'NY', 3792),
 ('Sam', 'Bread', 26, 9, 2001, 'NJ', 3809),
 ('Helen', 'Bread', 12, 12, 2004, 'CT', 4114),
 ('Knuth', 'Bread', 16, 2, 2007, 'CT', 4127),
 ('Knuth', 'Bread', 23, 5, 2005, 'PA', 4167),
 ('Knuth', 'Bread', 27, 3, 2008, 'CT', 4372),
 ('Emily', 'Bread', 2, 4, 2005, 'NJ', 4467),
 ('Bloom', 'Bread', 25, 2, 2000, 'NJ', 4778),
 ('Helen', 'Bread', 3, 6, 2008, 'NY', 4855),
 ('Helen', 'Bread', 30, 5, 2008, 'NY', 4901),
 ('Knuth', 'Butter', 2, 10, 2007, 'NY', 156),
 ('Helen', 'Butter', 18, 8, 2001, 'NY', 163),
 ('Emily', 'Butter', 23, 2, 2003, 'CT', 212),
 ('Helen', 'Butter', 1, 11, 2006, 'PA', 278),
 ('Helen', 'Butter', 25, 11, 2000, 'CT', 306),
 ('Knuth', 'Butter', 28, 3, 2004, 'PA', 516),
 ('Helen', 'Butter', 17, 2, 2002, 'PA', 566),
 ('Sam', 'Butter', 27, 2, 2006, 'PA', 673),
 ('Helen', 'Butter', 2, 1, 2000, 'NJ', 728),
 ('Helen', 'Butter', 11, 9, 2000, 'NJ', 803),
 ('Knuth', 'Butter', 1, 4, 2007, 'NY', 839),
 ('Helen', 'Butter', 15, 7, 2005, 'NJ', 942),
 ('Knuth', 'Butter', 9, 6, 2004, 'NY', 950),
 ('Helen', 'Butter', 7, 2, 2000, 'PA', 1025),
 ('Bloom', 'Butter', 16, 8, 2003, 'NY', 1054),
 ('Helen', 'Butter', 5, 7, 2004, 'NJ', 1174),
 ('Sam', 'Butter', 20, 12, 2002, 'NY', 1234),
 ('Emily', 'Butter', 22, 8, 2004, 'NJ', 1312),
 ('Helen', 'Butter', 12, 11, 2001, 'NY', 1357),
 ('Emily', 'Butter', 20, 2, 2007, 'CT', 1432),
 ('Emily', 'Butter', 7, 2, 2004, 'PA', 1491),
 ('Helen', 'Butter', 26, 11, 2006, 'NY', 1685),
 ('Helen', 'Butter', 11, 4, 2000, 'NJ', 1712),
 ('Sam', 'Butter', 22, 12, 2000, 'NJ', 1715),
 ('Helen', 'Butter', 30, 3, 2008, 'PA', 1786),
 ('Sam', 'Butter', 20, 10, 2006, 'NY', 1966),
 ('Helen', 'Butter', 21, 4, 2004, 'NY', 1978),
 ('Helen', 'Butter', 21, 7, 2001, 'NJ', 2086),
 ('Helen', 'Butter', 1, 2, 2005, 'NJ', 2160),
 ('Knuth', 'Butter', 4, 3, 2008, 'CT', 2232),
 ('Helen', 'Butter', 28, 2, 2002, 'NJ', 2483),
 ('Emily', 'Butter', 13, 2, 2001, 'NY', 2826),
 ('Knuth', 'Butter', 8, 10, 2008, 'PA', 2852),
 ('Emily', 'Butter', 16, 11, 2004, 'CT', 2862),
 ('Emily', 'Butter', 13, 6, 2008, 'CT', 2869),
 ('Sam', 'Butter', 14, 12, 2007, 'NJ', 3019),
 ('Helen', 'Butter', 10, 2, 2005, 'NJ', 3288),
 ('Sam', 'Butter', 9, 6, 2008, 'NJ', 3659),
 ('Bloom', 'Butter', 17, 9, 2008, 'NJ', 3718),
 ('Emily', 'Butter', 5, 7, 2005, 'NJ', 3840),
 ('Helen', 'Butter', 7, 7, 2007, 'PA', 3859),
 ('Emily', 'Butter', 25, 7, 2000, 'PA', 4008),
 ('Bloom', 'Butter', 9, 10, 2000, 'CT', 4279),
 ('Helen', 'Butter', 1, 1, 2006, 'NY', 4281),
 ('Helen', 'Butter', 2, 7, 2003, 'NY', 4364),
 ('Sam', 'Butter', 18, 4, 2004, 'NJ', 4453),
 ('Sam', 'Butter', 30, 9, 2006, 'NY', 4893),
 ('Helen', 'Butter', 4, 6, 2001, 'NY', 4969),
 ('Emily', 'Coke', 22, 11, 2003, 'CT', 81),
 ('Sam', 'Coke', 21, 6, 2003, 'NY', 142),
 ('Knuth', 'Coke', 8, 7, 2001, 'CT', 211),
 ('Bloom', 'Coke', 2, 8, 2003, 'NJ', 279),
 ('Helen', 'Coke', 11, 4, 2001, 'NY', 668),
 ('Helen', 'Coke', 4, 2, 2007, 'NJ', 755),
 ('Knuth', 'Coke', 9, 10, 2002, 'NJ', 766),
 ('Bloom', 'Coke', 14, 1, 2008, 'CT', 928),
 ('Helen', 'Coke', 23, 5, 2006, 'CT', 1099),
 ('Bloom', 'Coke', 7, 2, 2000, 'NY', 1229),
 ('Emily', 'Coke', 20, 2, 2004, 'NJ', 1301),
 ('Emily', 'Coke', 15, 2, 2007, 'NY', 1330),
 ('Knuth', 'Coke', 6, 1, 2003, 'CT', 1557),
 ('Knuth', 'Coke', 8, 5, 2004, 'NJ', 1583),
 ('Emily', 'Coke', 6, 11, 2008, 'NY', 1917),
 ('Knuth', 'Coke', 9, 5, 2005, 'NY', 1946),
 ('Helen', 'Coke', 4, 12, 2003, 'CT', 2172),
 ('Emily', 'Coke', 17, 1, 2006, 'NJ', 2192),
 ('Helen', 'Coke', 14, 4, 2001, 'CT', 2331),
 ('Helen', 'Coke', 10, 7, 2000, 'NY', 2401),
 ('Helen', 'Coke', 25, 5, 2008, 'CT', 2554),
 ('Knuth', 'Coke', 23, 6, 2007, 'CT', 2660),
 ('Helen', 'Coke', 19, 10, 2002, 'NJ', 2662),
 ('Sam', 'Coke', 14, 1, 2003, 'NY', 2668),
 ('Sam', 'Coke', 23, 1, 2006, 'CT', 2672),
 ('Bloom', 'Coke', 5, 4, 2003, 'PA', 2681),
 ('Bloom', 'Coke', 30, 9, 2000, 'NJ', 2714),
 ('Knuth', 'Coke', 17, 8, 2007, 'PA', 2812),
 ('Sam', 'Coke', 20, 5, 2007, 'CT', 2819),
 ('Bloom', 'Coke', 6, 10, 2008, 'PA', 2867),
 ('Emily', 'Coke', 13, 2, 2000, 'CT', 2909),
 ('Knuth', 'Coke', 13, 12, 2007, 'PA', 2928),
 ('Sam', 'Coke', 24, 8, 2004, 'PA', 3053),
 ('Bloom', 'Coke', 26, 7, 2003, 'NJ', 3058),
 ('Helen', 'Coke', 9, 10, 2008, 'NJ', 3065),
 ('Helen', 'Coke', 9, 2, 2008, 'PA', 3132),
 ('Knuth', 'Coke', 30, 6, 2008, 'PA', 3166),
 ('Helen', 'Coke', 15, 7, 2008, 'CT', 3198),
 ('Emily', 'Coke', 3, 6, 2004, 'NJ', 3314),
 ('Helen', 'Coke', 4, 5, 2005, 'CT', 3345),
 ('Bloom', 'Coke', 22, 7, 2008, 'CT', 3640),
 ('Bloom', 'Coke', 13, 7, 2001, 'PA', 3654),
 ('Helen', 'Coke', 31, 12, 2007, 'NJ', 3804),
 ('Helen', 'Coke', 15, 10, 2005, 'CT', 3840),
 ('Knuth', 'Coke', 9, 4, 2002, 'CT', 4027),
 ('Helen', 'Coke', 10, 2, 2002, 'NJ', 4237),
 ('Emily', 'Coke', 29, 2, 2001, 'NY', 4258),
 ('Knuth', 'Coke', 29, 1, 2005, 'PA', 4364),
 ('Emily', 'Coke', 25, 8, 2002, 'CT', 4379),
 ('Knuth', 'Coke', 3, 10, 2000, 'NJ', 4672),
 ('Knuth', 'Coke', 23, 2, 2003, 'PA', 4757),
 ('Sam', 'Cookies', 9, 10, 2007, 'CT', 132),
 ('Emily', 'Cookies', 3, 11, 2008, 'NJ', 173),
 ('Sam', 'Cookies', 23, 6, 2003, 'PA', 362),
 ('Sam', 'Cookies', 9, 5, 2004, 'PA', 454),
 ('Knuth', 'Cookies', 7, 3, 2002, 'PA', 488),
 ('Emily', 'Cookies', 1, 10, 2000, 'NJ', 658),
 ('Bloom', 'Cookies', 29, 11, 2006, 'CT', 796),
 ('Helen', 'Cookies', 19, 7, 2004, 'NY', 1080),
 ('Helen', 'Cookies', 16, 11, 2006, 'CT', 1164),
 ('Helen', 'Cookies', 23, 12, 2004, 'CT', 1194),
 ('Knuth', 'Cookies', 7, 10, 2001, 'PA', 1367),
 ('Emily', 'Cookies', 17, 7, 2004, 'PA', 1477),
 ('Knuth', 'Cookies', 23, 12, 2008, 'NY', 1485),
 ('Emily', 'Cookies', 28, 10, 2005, 'NY', 1656),
 ('Sam', 'Cookies', 22, 12, 2008, 'PA', 1657),
 ('Bloom', 'Cookies', 20, 6, 2005, 'CT', 1676),
 ('Emily', 'Cookies', 22, 7, 2007, 'NJ', 1827),
 ('Emily', 'Cookies', 30, 7, 2005, 'NY', 1844),
 ('Bloom', 'Cookies', 9, 9, 2005, 'PA', 1858),
 ('Helen', 'Cookies', 15, 7, 2005, 'NJ', 1965),
 ('Knuth', 'Cookies', 25, 10, 2004, 'NJ', 2154),
 ('Knuth', 'Cookies', 3, 7, 2003, 'CT', 2423),
 ('Emily', 'Cookies', 3, 11, 2004, 'NJ', 2497),
 ('Emily', 'Cookies', 9, 2, 2007, 'PA', 2500),
 ('Bloom', 'Cookies', 19, 9, 2002, 'PA', 2504),
 ('Sam', 'Cookies', 8, 2, 2008, 'CT', 2523),
 ('Knuth', 'Cookies', 12, 6, 2007, 'NJ', 2615),
 ('Knuth', 'Cookies', 29, 6, 2006, 'CT', 2635),
 ('Emily', 'Cookies', 19, 5, 2001, 'NY', 2685),
 ('Emily', 'Cookies', 2, 1, 2002, 'PA', 3238),
 ('Emily', 'Cookies', 24, 12, 2006, 'CT', 3308),
 ('Sam', 'Cookies', 20, 11, 2004, 'NY', 3376),
 ('Helen', 'Cookies', 28, 8, 2002, 'NY', 3494),
 ('Bloom', 'Cookies', 8, 10, 2000, 'CT', 3545),
 ('Emily', 'Cookies', 27, 1, 2001, 'CT', 3654),
 ('Emily', 'Cookies', 30, 4, 2005, 'NY', 3669),
 ('Knuth', 'Cookies', 6, 6, 2003, 'NJ', 3683),
 ('Emily', 'Cookies', 27, 11, 2006, 'NJ', 3719),
 ('Sam', 'Cookies', 17, 11, 2002, 'PA', 3725),
 ('Bloom', 'Cookies', 8, 6, 2006, 'NJ', 3887),
 ('Knuth', 'Cookies', 20, 2, 2000, 'NJ', 4237),
 ('Bloom', 'Cookies', 20, 9, 2005, 'NJ', 4240),
 ('Bloom', 'Cookies', 7, 7, 2003, 'CT', 4546),
 ('Bloom', 'Cookies', 8, 10, 2002, 'NY', 4570),
 ('Emily', 'Cookies', 9, 6, 2002, 'CT', 4925),
 ('Emily', 'Cookies', 18, 12, 2007, 'PA', 4935),
 ('Knuth', 'Cookies', 17, 7, 2003, 'CT', 4994),
 ('Emily', 'Eggs', 26, 11, 2002, 'PA', 128),
 ('Knuth', 'Eggs', 8, 4, 2006, 'PA', 326),
 ('Bloom', 'Eggs', 30, 11, 2000, 'NJ', 559),
 ('Bloom', 'Eggs', 24, 1, 2000, 'NY', 666),
 ('Emily', 'Eggs', 20, 4, 2006, 'PA', 771),
 ('Helen', 'Eggs', 7, 2, 2003, 'PA', 813),
 ('Sam', 'Eggs', 20, 9, 2008, 'PA', 964),
 ('Bloom', 'Eggs', 30, 11, 2004, 'CT', 1028),
 ('Helen', 'Eggs', 5, 10, 2003, 'PA', 1045),
 ('Emily', 'Eggs', 3, 11, 2006, 'PA', 1060),
 ('Sam', 'Eggs', 12, 2, 2006, 'NJ', 1091),
 ('Sam', 'Eggs', 10, 5, 2008, 'NJ', 1114),
 ('Bloom', 'Eggs', 5, 7, 2000, 'NY', 1219),
 ('Knuth', 'Eggs', 2, 12, 2008, 'CT', 1312),
 ('Knuth', 'Eggs', 19, 12, 2006, 'NJ', 1339),
 ('Sam', 'Eggs', 11, 7, 2004, 'NY', 1417),
 ('Helen', 'Eggs', 13, 5, 2000, 'CT', 1483),
 ('Bloom', 'Eggs', 24, 11, 2004, 'CT', 1573),
 ('Emily', 'Eggs', 1, 12, 2003, 'NY', 1595),
 ('Sam', 'Eggs', 14, 3, 2001, 'NY', 1744),
 ('Helen', 'Eggs', 18, 10, 2004, 'CT', 1754),
 ('Helen', 'Eggs', 17, 4, 2006, 'CT', 1807),
 ('Knuth', 'Eggs', 12, 11, 2004, 'CT', 1950),
 ('Emily', 'Eggs', 23, 7, 2007, 'NY', 2012),
 ('Knuth', 'Eggs', 9, 4, 2003, 'CT', 2151),
 ('Knuth', 'Eggs', 18, 10, 2001, 'NJ', 2353),
 ('Emily', 'Eggs', 10, 11, 2004, 'CT', 2722),
 ('Helen', 'Eggs', 13, 6, 2000, 'PA', 2817),
 ('Bloom', 'Eggs', 2, 4, 2000, 'CT', 2865),
 ('Emily', 'Eggs', 8, 7, 2007, 'NJ', 3030),
 ('Emily', 'Eggs', 3, 9, 2003, 'NJ', 3126),
 ('Bloom', 'Eggs', 22, 9, 2006, 'NY', 3150),
 ('Helen', 'Eggs', 21, 6, 2004, 'NY', 3200),
 ('Sam', 'Eggs', 11, 5, 2007, 'NY', 3363),
 ('Knuth', 'Eggs', 22, 9, 2003, 'PA', 3532),
 ('Bloom', 'Eggs', 13, 4, 2003, 'NY', 3621),
 ('Bloom', 'Eggs', 22, 4, 2007, 'PA', 3723),
 ('Knuth', 'Eggs', 6, 2, 2006, 'NY', 3788),
 ('Helen', 'Eggs', 21, 10, 2002, 'CT', 4162),
 ('Bloom', 'Eggs', 17, 5, 2005, 'CT', 4177),
 ('Knuth', 'Eggs', 12, 2, 2007, 'NY', 4313),
 ('Knuth', 'Eggs', 2, 11, 2004, 'CT', 4317),
 ('Emily', 'Eggs', 8, 1, 2006, 'NJ', 4535),
 ('Sam', 'Eggs', 31, 1, 2005, 'PA', 4610),
 ('Emily', 'Eggs', 19, 4, 2001, 'PA', 4658),
 ('Sam', 'Eggs', 7, 11, 2007, 'PA', 4674),
 ('Emily', 'Eggs', 20, 10, 2004, 'NJ', 4689),
 ('Emily', 'Eggs', 18, 8, 2007, 'NY', 4754),
 ('Bloom', 'Eggs', 3, 1, 2004, 'NJ', 4972),
 ('Knuth', 'Fruits', 26, 8, 2001, 'NY', 24),
 ('Bloom', 'Fruits', 29, 6, 2001, 'PA', 26),
 ('Emily', 'Fruits', 7, 7, 2007, 'PA', 111),
 ('Knuth', 'Fruits', 18, 9, 2003, 'CT', 159),
 ('Helen', 'Fruits', 17, 12, 2004, 'CT', 268),
 ('Helen', 'Fruits', 5, 6, 2003, 'NJ', 415),
 ('Helen', 'Fruits', 27, 2, 2007, 'CT', 442),
 ('Bloom', 'Fruits', 9, 4, 2000, 'PA', 570),
 ('Bloom', 'Fruits', 9, 7, 2002, 'NY', 612),
 ('Bloom', 'Fruits', 25, 3, 2004, 'PA', 699),
 ('Knuth', 'Fruits', 5, 7, 2002, 'NJ', 733),
 ('Bloom', 'Fruits', 12, 2, 2001, 'NJ', 776),
 ('Emily', 'Fruits', 3, 11, 2000, 'NY', 859),
 ('Helen', 'Fruits', 19, 2, 2003, 'CT', 951),
 ('Knuth', 'Fruits', 8, 4, 2005, 'CT', 973),
 ('Knuth', 'Fruits', 24, 7, 2008, 'NY', 1062),
 ('Knuth', 'Fruits', 25, 10, 2006, 'NY', 1181),
 ('Bloom', 'Fruits', 24, 3, 2004, 'NY', 1268),
 ('Sam', 'Fruits', 12, 12, 2006, 'NJ', 1311),
 ('Knuth', 'Fruits', 16, 9, 2003, 'PA', 1313),
 ('Knuth', 'Fruits', 12, 1, 2002, 'NJ', 1368),
 ('Emily', 'Fruits', 24, 3, 2008, 'PA', 1469),
 ('Emily', 'Fruits', 5, 4, 2000, 'PA', 1573),
 ('Knuth', 'Fruits', 30, 11, 2002, 'PA', 1718),
 ('Bloom', 'Fruits', 26, 11, 2006, 'NJ', 1832),
 ('Emily', 'Fruits', 28, 4, 2005, 'NY', 2102),
 ('Sam', 'Fruits', 27, 7, 2007, 'PA', 2240),
 ('Emily', 'Fruits', 22, 7, 2004, 'PA', 2243),
 ('Helen', 'Fruits', 21, 1, 2005, 'CT', 2360),
 ('Sam', 'Fruits', 12, 10, 2005, 'NY', 2409),
 ('Knuth', 'Fruits', 4, 2, 2005, 'PA', 2430),
 ('Helen', 'Fruits', 30, 3, 2007, 'CT', 2525),
 ('Bloom', 'Fruits', 13, 4, 2004, 'PA', 2692),
 ('Knuth', 'Fruits', 19, 4, 2007, 'NY', 2740),
 ('Helen', 'Fruits', 3, 5, 2006, 'NY', 2774),
 ('Sam', 'Fruits', 15, 10, 2005, 'CT', 2802),
 ('Helen', 'Fruits', 28, 6, 2005, 'PA', 2811),
 ('Bloom', 'Fruits', 14, 7, 2005, 'CT', 2813),
 ('Bloom', 'Fruits', 11, 1, 2004, 'PA', 3006),
 ('Emily', 'Fruits', 6, 10, 2000, 'NY', 3027),
 ('Emily', 'Fruits', 6, 4, 2008, 'CT', 3055),
 ('Sam', 'Fruits', 21, 11, 2006, 'CT', 3399),
 ('Bloom', 'Fruits', 30, 1, 2003, 'PA', 3623),
 ('Bloom', 'Fruits', 29, 7, 2005, 'NY', 3653),
 ('Sam', 'Fruits', 23, 5, 2000, 'NJ', 3743),
 ('Emily', 'Fruits', 5, 11, 2001, 'NJ', 3743),
 ('Knuth', 'Fruits', 6, 7, 2001, 'CT', 3756),
 ('Bloom', 'Fruits', 14, 8, 2000, 'NY', 3798),
 ('Sam', 'Fruits', 21, 9, 2005, 'PA', 3800),
 ('Emily', 'Fruits', 14, 12, 2003, 'NY', 3864),
 ('Emily', 'Fruits', 31, 8, 2005, 'PA', 3913),
 ('Knuth', 'Fruits', 23, 12, 2008, 'NJ', 3939),
 ('Helen', 'Fruits', 25, 12, 2006, 'CT', 4015),
 ('Bloom', 'Fruits', 15, 11, 2005, 'CT', 4020),
 ('Bloom', 'Fruits', 31, 1, 2003, 'CT', 4085),
 ('Bloom', 'Fruits', 31, 8, 2003, 'NJ', 4094),
 ('Emily', 'Fruits', 11, 1, 2000, 'NJ', 4369),
 ('Bloom', 'Fruits', 5, 5, 2002, 'PA', 4444),
 ('Knuth', 'Fruits', 1, 2, 2003, 'PA', 4475),
 ('Sam', 'Fruits', 16, 12, 2005, 'PA', 4644),
 ('Emily', 'Fruits', 29, 8, 2002, 'PA', 4731),
 ('Sam', 'Fruits', 2, 11, 2004, 'NY', 4738),
 ('Sam', 'Fruits', 15, 9, 2006, 'NJ', 4793),
 ('Emily', 'Milk', 2, 7, 2008, 'CT', 26),
 ('Knuth', 'Milk', 25, 3, 2001, 'CT', 58),
 ('Helen', 'Milk', 9, 4, 2000, 'NY', 77),
 ('Knuth', 'Milk', 5, 2, 2007, 'PA', 126),
 ('Helen', 'Milk', 7, 11, 2006, 'CT', 210),
 ('Helen', 'Milk', 24, 12, 2006, 'NY', 311),
 ('Sam', 'Milk', 7, 4, 2004, 'CT', 385),
 ('Bloom', 'Milk', 31, 10, 2003, 'PA', 553),
 ('Sam', 'Milk', 7, 4, 2001, 'CT', 811),
 ('Sam', 'Milk', 29, 1, 2005, 'CT', 879),
 ('Helen', 'Milk', 13, 4, 2000, 'NY', 888),
 ('Sam', 'Milk', 4, 1, 2008, 'NY', 987),
 ('Knuth', 'Milk', 6, 10, 2003, 'PA', 1088),
 ('Bloom', 'Milk', 8, 9, 2000, 'NJ', 1106),
 ('Sam', 'Milk', 4, 2, 2002, 'PA', 1126),
 ('Sam', 'Milk', 9, 8, 2001, 'NY', 1132),
 ('Sam', 'Milk', 28, 12, 2007, 'NY', 1164),
 ('Helen', 'Milk', 6, 3, 2003, 'CT', 1249),
 ('Emily', 'Milk', 9, 6, 2003, 'PA', 1274),
 ('Helen', 'Milk', 10, 5, 2001, 'PA', 1457),
 ('Sam', 'Milk', 7, 11, 2000, 'CT', 1607),
 ('Bloom', 'Milk', 4, 12, 2004, 'CT', 1639),
 ('Bloom', 'Milk', 3, 5, 2001, 'NJ', 1794),
 ('Bloom', 'Milk', 11, 5, 2007, 'NY', 1820),
 ('Helen', 'Milk', 21, 1, 2006, 'NJ', 1839),
 ('Bloom', 'Milk', 16, 10, 2001, 'NJ', 2004),
 ('Sam', 'Milk', 6, 8, 2005, 'PA', 2124),
 ('Emily', 'Milk', 5, 7, 2000, 'PA', 2125),
 ('Bloom', 'Milk', 20, 1, 2008, 'PA', 2220),
 ('Sam', 'Milk', 6, 1, 2003, 'PA', 2298),
 ('Helen', 'Milk', 6, 11, 2001, 'NY', 2422),
 ('Knuth', 'Milk', 13, 4, 2006, 'NY', 2424),
 ('Emily', 'Milk', 14, 3, 2005, 'CT', 2589),
 ('Bloom', 'Milk', 30, 3, 2001, 'CT', 2843),
 ('Sam', 'Milk', 6, 7, 2005, 'NY', 3120),
 ('Emily', 'Milk', 5, 4, 2005, 'PA', 3211),
 ('Emily', 'Milk', 2, 4, 2008, 'CT', 3257),
 ('Helen', 'Milk', 19, 9, 2002, 'PA', 3314),
 ('Sam', 'Milk', 4, 2, 2008, 'CT', 3434),
 ('Bloom', 'Milk', 19, 4, 2003, 'NY', 3516),
 ('Emily', 'Milk', 3, 9, 2008, 'NJ', 3839),
 ('Helen', 'Milk', 28, 2, 2006, 'NY', 4249),
 ('Bloom', 'Milk', 19, 10, 2008, 'PA', 4377),
 ('Helen', 'Milk', 6, 1, 2003, 'CT', 4429),
 ('Sam', 'Milk', 19, 12, 2006, 'NJ', 4522),
 ('Bloom', 'Milk', 27, 1, 2007, 'NY', 4583),
 ('Bloom', 'Milk', 15, 12, 2006, 'NJ', 4616),
 ('Helen', 'Milk', 28, 2, 2006, 'PA', 4794),
 ('Bloom', 'Milk', 15, 10, 2008, 'CT', 4870),
 ('Emily', 'Milk', 12, 11, 2002, 'NY', 4986),
 ('Bloom', 'Pepsi', 10, 7, 2000, 'CT', 94),
 ('Sam', 'Pepsi', 16, 4, 2003, 'CT', 160),
 ('Bloom', 'Pepsi', 7, 8, 2006, 'NY', 254),
 ('Knuth', 'Pepsi', 29, 8, 2001, 'NJ', 277),
 ('Bloom', 'Pepsi', 20, 1, 2000, 'NJ', 526),
 ('Emily', 'Pepsi', 15, 6, 2008, 'NY', 538),
 ('Knuth', 'Pepsi', 21, 12, 2008, 'CT', 653),
 ('Sam', 'Pepsi', 8, 11, 2008, 'NJ', 1097),
 ('Knuth', 'Pepsi', 12, 8, 2004, 'CT', 1244),
 ('Bloom', 'Pepsi', 1, 6, 2003, 'NJ', 1368),
 ('Helen', 'Pepsi', 1, 10, 2005, 'PA', 1407),
 ('Helen', 'Pepsi', 23, 6, 2000, 'PA', 1456),
 ('Sam', 'Pepsi', 15, 3, 2008, 'CT', 1470),
 ('Knuth', 'Pepsi', 29, 4, 2002, 'CT', 1481),
 ('Helen', 'Pepsi', 12, 12, 2002, 'CT', 1515),
 ('Emily', 'Pepsi', 5, 5, 2001, 'PA', 1682),
 ('Helen', 'Pepsi', 13, 4, 2006, 'NY', 1931),
 ('Helen', 'Pepsi', 13, 2, 2001, 'NJ', 1983),
 ('Bloom', 'Pepsi', 20, 9, 2000, 'PA', 2034),
 ('Knuth', 'Pepsi', 15, 6, 2001, 'NJ', 2064),
 ('Helen', 'Pepsi', 18, 1, 2006, 'NJ', 2232),
 ('Bloom', 'Pepsi', 26, 5, 2001, 'NJ', 2367),
 ('Knuth', 'Pepsi', 17, 6, 2008, 'PA', 2390),
 ('Knuth', 'Pepsi', 13, 12, 2007, 'PA', 2538),
 ('Knuth', 'Pepsi', 2, 3, 2002, 'NJ', 2548),
 ('Helen', 'Pepsi', 25, 5, 2003, 'NY', 2590),
 ('Emily', 'Pepsi', 14, 1, 2004, 'NJ', 2591),
 ('Helen', 'Pepsi', 24, 9, 2004, 'CT', 2768),
 ('Sam', 'Pepsi', 26, 3, 2005, 'PA', 2841),
 ('Helen', 'Pepsi', 14, 12, 2005, 'NY', 3002),
 ('Sam', 'Pepsi', 30, 10, 2001, 'CT', 3008),
 ('Sam', 'Pepsi', 16, 3, 2008, 'NJ', 3014),
 ('Sam', 'Pepsi', 27, 7, 2008, 'NY', 3189),
 ('Sam', 'Pepsi', 19, 6, 2001, 'NJ', 3368),
 ('Sam', 'Pepsi', 28, 5, 2002, 'NJ', 3468),
 ('Helen', 'Pepsi', 23, 4, 2007, 'CT', 3609),
 ('Sam', 'Pepsi', 16, 11, 2003, 'NJ', 3694),
 ('Knuth', 'Pepsi', 6, 9, 2006, 'CT', 3760),
 ('Helen', 'Pepsi', 20, 10, 2002, 'NJ', 3817),
 ('Sam', 'Pepsi', 13, 9, 2002, 'NJ', 3877),
 ('Knuth', 'Pepsi', 3, 2, 2005, 'NY', 3879),
 ('Helen', 'Pepsi', 14, 3, 2002, 'NJ', 3891),
 ('Knuth', 'Pepsi', 2, 6, 2002, 'NY', 3936),
 ('Emily', 'Pepsi', 4, 10, 2003, 'CT', 4135),
 ('Bloom', 'Pepsi', 2, 12, 2001, 'NY', 4232),
 ('Emily', 'Pepsi', 22, 1, 2006, 'CT', 4404),
 ('Helen', 'Pepsi', 31, 1, 2008, 'NJ', 4412),
 ('Bloom', 'Pepsi', 30, 11, 2008, 'NJ', 4515),
 ('Emily', 'Pepsi', 22, 3, 2004, 'CT', 4531),
 ('Knuth', 'Pepsi', 27, 7, 2008, 'NJ', 4689),
 ('Sam', 'Pepsi', 28, 9, 2008, 'NY', 4797),
 ('Sam', 'Pepsi', 19, 12, 2002, 'CT', 4865),
 ('Emily', 'Pepsi', 11, 5, 2005, 'NY', 4901),
 ('Knuth', 'Pepsi', 11, 9, 2004, 'NY', 4942),
 ('Emily', 'Soap', 4, 9, 2003, 'CT', 70),
 ('Sam', 'Soap', 12, 2, 2001, 'NJ', 165),
 ('Bloom', 'Soap', 17, 9, 2002, 'PA', 270),
 ('Bloom', 'Soap', 5, 7, 2002, 'CT', 387),
 ('Sam', 'Soap', 23, 11, 2005, 'PA', 399),
 ('Knuth', 'Soap', 17, 4, 2008, 'CT', 436),
 ('Knuth', 'Soap', 18, 11, 2004, 'PA', 586),
 ('Emily', 'Soap', 31, 7, 2007, 'NJ', 623),
 ('Knuth', 'Soap', 9, 2, 2005, 'NJ', 657),
 ('Helen', 'Soap', 25, 10, 2006, 'NJ', 712),
 ('Emily', 'Soap', 26, 10, 2000, 'PA', 742),
 ('Helen', 'Soap', 27, 11, 2001, 'PA', 925),
 ('Sam', 'Soap', 20, 11, 2004, 'NJ', 989),
 ('Knuth', 'Soap', 22, 8, 2005, 'NY', 1002),
 ('Knuth', 'Soap', 16, 1, 2001, 'CT', 1098),
 ('Knuth', 'Soap', 13, 4, 2008, 'CT', 1160),
 ('Bloom', 'Soap', 10, 4, 2007, 'PA', 1216),
 ('Helen', 'Soap', 26, 8, 2005, 'CT', 1301),
 ('Sam', 'Soap', 19, 6, 2007, 'NY', 1798),
 ('Sam', 'Soap', 11, 6, 2005, 'NJ', 1883),
 ('Helen', 'Soap', 18, 11, 2007, 'NJ', 1991),
 ('Helen', 'Soap', 22, 3, 2008, 'CT', 2203),
 ('Knuth', 'Soap', 27, 10, 2006, 'CT', 2231),
 ('Sam', 'Soap', 4, 1, 2003, 'NJ', 2356),
 ('Sam', 'Soap', 6, 1, 2003, 'CT', 2461),
 ('Emily', 'Soap', 2, 4, 2002, 'CT', 2549),
 ('Knuth', 'Soap', 23, 11, 2002, 'CT', 2915),

In [ ]:
SELECT
    prod,
    percentile_cont(0.1) WITHIN GROUP (ORDER BY quant) As cont_median,
    /*
    percentile_disc(0.5) WITHIN GROUP (ORDER BY score) AS disc_median,
    mode() WITHIN GROUP (ORDER BY score) AS mode,
    */
    COUNT(*) As num_scores
FROM sales
GROUP BY prod
ORDER BY prod

In [63]:
%%sql
select *
    from sales
    order by cust, prod,month asc

 * postgresql://postgres:***@127.0.0.1/salesdb
500 rows affected.

[('Bloom', 'Bread', 22, 1, 2003, 'CT', 2220),
 ('Bloom', 'Bread', 25, 2, 2000, 'NJ', 4778),
 ('Bloom', 'Bread', 13, 3, 2006, 'NY', 3792),
 ('Bloom', 'Bread', 5, 3, 2007, 'NJ', 2277),
 ('Bloom', 'Bread', 20, 4, 2006, 'CT', 417),
 ('Bloom', 'Bread', 13, 6, 2000, 'CT', 256),
 ('Bloom', 'Bread', 22, 6, 2008, 'NJ', 944),
 ('Bloom', 'Bread', 4, 7, 2006, 'CT', 1494),
 ('Bloom', 'Bread', 25, 8, 2004, 'PA', 3100),
 ('Bloom', 'Bread', 14, 9, 2007, 'CT', 3261),
 ('Bloom', 'Bread', 4, 9, 2008, 'NJ', 1698),
 ('Bloom', 'Bread', 3, 12, 2008, 'NJ', 1106),
 ('Bloom', 'Butter', 16, 8, 2003, 'NY', 1054),
 ('Bloom', 'Butter', 17, 9, 2008, 'NJ', 3718),
 ('Bloom', 'Butter', 9, 10, 2000, 'CT', 4279),
 ('Bloom', 'Coke', 14, 1, 2008, 'CT', 928),
 ('Bloom', 'Coke', 7, 2, 2000, 'NY', 1229),
 ('Bloom', 'Coke', 5, 4, 2003, 'PA', 2681),
 ('Bloom', 'Coke', 22, 7, 2008, 'CT', 3640),
 ('Bloom', 'Coke', 13, 7, 2001, 'PA', 3654),
 ('Bloom', 'Coke', 26, 7, 2003, 'NJ', 3058),
 ('Bloom', 'Coke', 2, 8, 2003, 'NJ', 279),
 ('Bloom', 'Coke', 30, 9, 2000, 'NJ', 2714),
 ('Bloom', 'Coke', 6, 10, 2008, 'PA', 2867),
 ('Bloom', 'Cookies', 20, 6, 2005, 'CT', 1676),
 ('Bloom', 'Cookies', 8, 6, 2006, 'NJ', 3887),
 ('Bloom', 'Cookies', 7, 7, 2003, 'CT', 4546),
 ('Bloom', 'Cookies', 20, 9, 2005, 'NJ', 4240),
 ('Bloom', 'Cookies', 19, 9, 2002, 'PA', 2504),
 ('Bloom', 'Cookies', 9, 9, 2005, 'PA', 1858),
 ('Bloom', 'Cookies', 8, 10, 2000, 'CT', 3545),
 ('Bloom', 'Cookies', 8, 10, 2002, 'NY', 4570),
 ('Bloom', 'Cookies', 29, 11, 2006, 'CT', 796),
 ('Bloom', 'Eggs', 3, 1, 2004, 'NJ', 4972),
 ('Bloom', 'Eggs', 24, 1, 2000, 'NY', 666),
 ('Bloom', 'Eggs', 22, 4, 2007, 'PA', 3723),
 ('Bloom', 'Eggs', 2, 4, 2000, 'CT', 2865),
 ('Bloom', 'Eggs', 13, 4, 2003, 'NY', 3621),
 ('Bloom', 'Eggs', 17, 5, 2005, 'CT', 4177),
 ('Bloom', 'Eggs', 5, 7, 2000, 'NY', 1219),
 ('Bloom', 'Eggs', 22, 9, 2006, 'NY', 3150),
 ('Bloom', 'Eggs', 30, 11, 2000, 'NJ', 559),
 ('Bloom', 'Eggs', 30, 11, 2004, 'CT', 1028),
 ('Bloom', 'Eggs', 24, 11, 2004, 'CT', 1573),
 ('Bloom', 'Fruits', 11, 1, 2004, 'PA', 3006),
 ('Bloom', 'Fruits', 30, 1, 2003, 'PA', 3623),
 ('Bloom', 'Fruits', 31, 1, 2003, 'CT', 4085),
 ('Bloom', 'Fruits', 12, 2, 2001, 'NJ', 776),
 ('Bloom', 'Fruits', 24, 3, 2004, 'NY', 1268),
 ('Bloom', 'Fruits', 25, 3, 2004, 'PA', 699),
 ('Bloom', 'Fruits', 13, 4, 2004, 'PA', 2692),
 ('Bloom', 'Fruits', 9, 4, 2000, 'PA', 570),
 ('Bloom', 'Fruits', 5, 5, 2002, 'PA', 4444),
 ('Bloom', 'Fruits', 29, 6, 2001, 'PA', 26),
 ('Bloom', 'Fruits', 29, 7, 2005, 'NY', 3653),
 ('Bloom', 'Fruits', 9, 7, 2002, 'NY', 612),
 ('Bloom', 'Fruits', 14, 7, 2005, 'CT', 2813),
 ('Bloom', 'Fruits', 14, 8, 2000, 'NY', 3798),
 ('Bloom', 'Fruits', 31, 8, 2003, 'NJ', 4094),
 ('Bloom', 'Fruits', 15, 11, 2005, 'CT', 4020),
 ('Bloom', 'Fruits', 26, 11, 2006, 'NJ', 1832),
 ('Bloom', 'Milk', 20, 1, 2008, 'PA', 2220),
 ('Bloom', 'Milk', 27, 1, 2007, 'NY', 4583),
 ('Bloom', 'Milk', 30, 3, 2001, 'CT', 2843),
 ('Bloom', 'Milk', 19, 4, 2003, 'NY', 3516),
 ('Bloom', 'Milk', 11, 5, 2007, 'NY', 1820),
 ('Bloom', 'Milk', 3, 5, 2001, 'NJ', 1794),
 ('Bloom', 'Milk', 8, 9, 2000, 'NJ', 1106),
 ('Bloom', 'Milk', 15, 10, 2008, 'CT', 4870),
 ('Bloom', 'Milk', 16, 10, 2001, 'NJ', 2004),
 ('Bloom', 'Milk', 19, 10, 2008, 'PA', 4377),
 ('Bloom', 'Milk', 31, 10, 2003, 'PA', 553),
 ('Bloom', 'Milk', 4, 12, 2004, 'CT', 1639),
 ('Bloom', 'Milk', 15, 12, 2006, 'NJ', 4616),
 ('Bloom', 'Pepsi', 20, 1, 2000, 'NJ', 526),
 ('Bloom', 'Pepsi', 26, 5, 2001, 'NJ', 2367),
 ('Bloom', 'Pepsi', 1, 6, 2003, 'NJ', 1368),
 ('Bloom', 'Pepsi', 10, 7, 2000, 'CT', 94),
 ('Bloom', 'Pepsi', 7, 8, 2006, 'NY', 254),
 ('Bloom', 'Pepsi', 20, 9, 2000, 'PA', 2034),
 ('Bloom', 'Pepsi', 30, 11, 2008, 'NJ', 4515),
 ('Bloom', 'Pepsi', 2, 12, 2001, 'NY', 4232),
 ('Bloom', 'Soap', 6, 1, 2005, 'CT', 4623),
 ('Bloom', 'Soap', 10, 4, 2007, 'PA', 1216),
 ('Bloom', 'Soap', 7, 6, 2005, 'PA', 3404),
 ('Bloom', 'Soap', 5, 7, 2002, 'CT', 387),
 ('Bloom', 'Soap', 17, 9, 2002, 'PA', 270),
 ('Bloom', 'Soap', 3, 11, 2002, 'NJ', 4364),
 ('Bloom', 'Yogurt', 28, 3, 2008, 'NJ', 1660),
 ('Bloom', 'Yogurt', 28, 4, 2005, 'NY', 4043),
 ('Bloom', 'Yogurt', 3, 4, 2001, 'NJ', 1203),
 ('Bloom', 'Yogurt', 25, 7, 2004, 'PA', 17),
 ('Bloom', 'Yogurt', 11, 9, 2001, 'NJ', 3172),
 ('Bloom', 'Yogurt', 17, 9, 2003, 'CT', 4004),
 ('Bloom', 'Yogurt', 6, 10, 2000, 'NJ', 2788),
 ('Bloom', 'Yogurt', 7, 12, 2006, 'PA', 783),
 ('Emily', 'Bread', 21, 3, 2001, 'NY', 492),
 ('Emily', 'Bread', 2, 4, 2005, 'NJ', 4467),
 ('Emily', 'Bread', 31, 4, 2008, 'NJ', 2135),
 ('Emily', 'Bread', 13, 5, 2001, 'NJ', 232),
 ('Emily', 'Bread', 21, 6, 2000, 'NJ', 141),
 ('Emily', 'Bread', 4, 6, 2001, 'CT', 1626),
 ('Emily', 'Bread', 4, 9, 2000, 'PA', 1572),
 ('Emily', 'Bread', 28, 9, 2005, 'PA', 42),
 ('Emily', 'Bread', 17, 11, 2001, 'PA', 2565),
 ('Emily', 'Bread', 23, 12, 2005, 'NY', 2071),
 ('Emily', 'Butter', 20, 2, 2007, 'CT', 1432),
 ('Emily', 'Butter', 7, 2, 2004, 'PA', 1491),
 ('Emily', 'Butter', 13, 2, 2001, 'NY', 2826),
 ('Emily', 'Butter', 23, 2, 2003, 'CT', 212),
 ('Emily', 'Butter', 13, 6, 2008, 'CT', 2869),
 ('Emily', 'Butter', 25, 7, 2000, 'PA', 4008),
 ('Emily', 'Butter', 5, 7, 2005, 'NJ', 3840),
 ('Emily', 'Butter', 22, 8, 2004, 'NJ', 1312),
 ('Emily', 'Butter', 16, 11, 2004, 'CT', 2862),
 ('Emily', 'Coke', 17, 1, 2006, 'NJ', 2192),
 ('Emily', 'Coke', 20, 2, 2004, 'NJ', 1301),
 ('Emily', 'Coke', 29, 2, 2001, 'NY', 4258),
 ('Emily', 'Coke', 13, 2, 2000, 'CT', 2909),
 ('Emily', 'Coke', 15, 2, 2007, 'NY', 1330),
 ('Emily', 'Coke', 3, 6, 2004, 'NJ', 3314),
 ('Emily', 'Coke', 25, 8, 2002, 'CT', 4379),
 ('Emily', 'Coke', 22, 11, 2003, 'CT', 81),
 ('Emily', 'Coke', 6, 11, 2008, 'NY', 1917),
 ('Emily', 'Cookies', 2, 1, 2002, 'PA', 3238),
 ('Emily', 'Cookies', 27, 1, 2001, 'CT', 3654),
 ('Emily', 'Cookies', 9, 2, 2007, 'PA', 2500),
 ('Emily', 'Cookies', 30, 4, 2005, 'NY', 3669),
 ('Emily', 'Cookies', 19, 5, 2001, 'NY', 2685),
 ('Emily', 'Cookies', 9, 6, 2002, 'CT', 4925),
 ('Emily', 'Cookies', 17, 7, 2004, 'PA', 1477),
 ('Emily', 'Cookies', 22, 7, 2007, 'NJ', 1827),
 ('Emily', 'Cookies', 30, 7, 2005, 'NY', 1844),
 ('Emily', 'Cookies', 28, 10, 2005, 'NY', 1656),
 ('Emily', 'Cookies', 1, 10, 2000, 'NJ', 658),
 ('Emily', 'Cookies', 3, 11, 2008, 'NJ', 173),
 ('Emily', 'Cookies', 3, 11, 2004, 'NJ', 2497),
 ('Emily', 'Cookies', 27, 11, 2006, 'NJ', 3719),
 ('Emily', 'Cookies', 18, 12, 2007, 'PA', 4935),
 ('Emily', 'Cookies', 24, 12, 2006, 'CT', 3308),
 ('Emily', 'Eggs', 8, 1, 2006, 'NJ', 4535),
 ('Emily', 'Eggs', 19, 4, 2001, 'PA', 4658),
 ('Emily', 'Eggs', 20, 4, 2006, 'PA', 771),
 ('Emily', 'Eggs', 23, 7, 2007, 'NY', 2012),
 ('Emily', 'Eggs', 8, 7, 2007, 'NJ', 3030),
 ('Emily', 'Eggs', 18, 8, 2007, 'NY', 4754),
 ('Emily', 'Eggs', 3, 9, 2003, 'NJ', 3126),
 ('Emily', 'Eggs', 20, 10, 2004, 'NJ', 4689),
 ('Emily', 'Eggs', 26, 11, 2002, 'PA', 128),
 ('Emily', 'Eggs', 10, 11, 2004, 'CT', 2722),
 ('Emily', 'Eggs', 3, 11, 2006, 'PA', 1060),
 ('Emily', 'Eggs', 1, 12, 2003, 'NY', 1595),
 ('Emily', 'Fruits', 11, 1, 2000, 'NJ', 4369),
 ('Emily', 'Fruits', 24, 3, 2008, 'PA', 1469),
 ('Emily', 'Fruits', 28, 4, 2005, 'NY', 2102),
 ('Emily', 'Fruits', 5, 4, 2000, 'PA', 1573),
 ('Emily', 'Fruits', 6, 4, 2008, 'CT', 3055),
 ('Emily', 'Fruits', 22, 7, 2004, 'PA', 2243),
 ('Emily', 'Fruits', 7, 7, 2007, 'PA', 111),
 ('Emily', 'Fruits', 31, 8, 2005, 'PA', 3913),
 ('Emily', 'Fruits', 29, 8, 2002, 'PA', 4731),
 ('Emily', 'Fruits', 6, 10, 2000, 'NY', 3027),
 ('Emily', 'Fruits', 5, 11, 2001, 'NJ', 3743),
 ('Emily', 'Fruits', 3, 11, 2000, 'NY', 859),
 ('Emily', 'Fruits', 14, 12, 2003, 'NY', 3864),
 ('Emily', 'Milk', 14, 3, 2005, 'CT', 2589),
 ('Emily', 'Milk', 2, 4, 2008, 'CT', 3257),
 ('Emily', 'Milk', 5, 4, 2005, 'PA', 3211),
 ('Emily', 'Milk', 9, 6, 2003, 'PA', 1274),
 ('Emily', 'Milk', 2, 7, 2008, 'CT', 26),
 ('Emily', 'Milk', 5, 7, 2000, 'PA', 2125),
 ('Emily', 'Milk', 3, 9, 2008, 'NJ', 3839),
 ('Emily', 'Milk', 12, 11, 2002, 'NY', 4986),
 ('Emily', 'Pepsi', 22, 1, 2006, 'CT', 4404),
 ('Emily', 'Pepsi', 14, 1, 2004, 'NJ', 2591),
 ('Emily', 'Pepsi', 22, 3, 2004, 'CT', 4531),
 ('Emily', 'Pepsi', 5, 5, 2001, 'PA', 1682),
 ('Emily', 'Pepsi', 11, 5, 2005, 'NY', 4901),
 ('Emily', 'Pepsi', 15, 6, 2008, 'NY', 538),
 ('Emily', 'Pepsi', 4, 10, 2003, 'CT', 4135),
 ('Emily', 'Soap', 27, 1, 2006, 'NY', 3218),
 ('Emily', 'Soap', 2, 4, 2002, 'CT', 2549),
 ('Emily', 'Soap', 31, 7, 2007, 'NJ', 623),
 ('Emily', 'Soap', 4, 8, 2001, 'NJ', 3901),
 ('Emily', 'Soap', 4, 9, 2003, 'CT', 70),
 ('Emily', 'Soap', 26, 10, 2000, 'PA', 742),
 ('Emily', 'Soap', 10, 10, 2000, 'NJ', 4081),
 ('Emily', 'Soap', 15, 11, 2003, 'CT', 4106),
 ('Emily', 'Yogurt', 28, 3, 2005, 'NY', 3822),
 ('Emily', 'Yogurt', 9, 3, 2003, 'NJ', 2336),
 ('Emily', 'Yogurt', 29, 5, 2002, 'CT', 2126),
 ('Emily', 'Yogurt', 9, 6, 2006, 'NY', 3174),
 ('Emily', 'Yogurt', 16, 8, 2000, 'CT', 557),
 ('Emily', 'Yogurt', 4, 8, 2004, 'CT', 3765),
 ('Emily', 'Yogurt', 7, 10, 2005, 'NY', 730),
 ('Helen', 'Bread', 24, 1, 2002, 'CT', 3530),
 ('Helen', 'Bread', 30, 5, 2008, 'NY', 4901),
 ('Helen', 'Bread', 26, 5, 2006, 'CT', 1406),
 ('Helen', 'Bread', 21, 5, 2000, 'NY', 389),
 ('Helen', 'Bread', 3, 6, 2008, 'NY', 4855),
 ('Helen', 'Bread', 15, 6, 2003, 'NJ', 1687),
 ('Helen', 'Bread', 11, 10, 2007, 'NJ', 2513),
 ('Helen', 'Bread', 15, 11, 2008, 'PA', 1637),
 ('Helen', 'Bread', 12, 12, 2004, 'CT', 4114),
 ('Helen', 'Butter', 1, 1, 2006, 'NY', 4281),
 ('Helen', 'Butter', 2, 1, 2000, 'NJ', 728),
 ('Helen', 'Butter', 28, 2, 2002, 'NJ', 2483),
 ('Helen', 'Butter', 10, 2, 2005, 'NJ', 3288),
 ('Helen', 'Butter', 1, 2, 2005, 'NJ', 2160),
 ('Helen', 'Butter', 7, 2, 2000, 'PA', 1025),
 ('Helen', 'Butter', 17, 2, 2002, 'PA', 566),
 ('Helen', 'Butter', 30, 3, 2008, 'PA', 1786),
 ('Helen', 'Butter', 11, 4, 2000, 'NJ', 1712),
 ('Helen', 'Butter', 21, 4, 2004, 'NY', 1978),
 ('Helen', 'Butter', 4, 6, 2001, 'NY', 4969),
 ('Helen', 'Butter', 15, 7, 2005, 'NJ', 942),
 ('Helen', 'Butter', 7, 7, 2007, 'PA', 3859),
 ('Helen', 'Butter', 2, 7, 2003, 'NY', 4364),
 ('Helen', 'Butter', 21, 7, 2001, 'NJ', 2086),
 ('Helen', 'Butter', 5, 7, 2004, 'NJ', 1174),
 ('Helen', 'Butter', 18, 8, 2001, 'NY', 163),
 ('Helen', 'Butter', 11, 9, 2000, 'NJ', 803),
 ('Helen', 'Butter', 26, 11, 2006, 'NY', 1685),
 ('Helen', 'Butter', 25, 11, 2000, 'CT', 306),
 ('Helen', 'Butter', 12, 11, 2001, 'NY', 1357),
 ('Helen', 'Butter', 1, 11, 2006, 'PA', 278),
 ('Helen', 'Coke', 9, 2, 2008, 'PA', 3132),
 ('Helen', 'Coke', 10, 2, 2002, 'NJ', 4237),
 ('Helen', 'Coke', 4, 2, 2007, 'NJ', 755),
 ('Helen', 'Coke', 11, 4, 2001, 'NY', 668),
 ('Helen', 'Coke', 14, 4, 2001, 'CT', 2331),
 ('Helen', 'Coke', 25, 5, 2008, 'CT', 2554),
 ('Helen', 'Coke', 23, 5, 2006, 'CT', 1099),
 ('Helen', 'Coke', 4, 5, 2005, 'CT', 3345),
 ('Helen', 'Coke', 15, 7, 2008, 'CT', 3198),
 ('Helen', 'Coke', 10, 7, 2000, 'NY', 2401),
 ('Helen', 'Coke', 15, 10, 2005, 'CT', 3840),
 ('Helen', 'Coke', 9, 10, 2008, 'NJ', 3065),
 ('Helen', 'Coke', 19, 10, 2002, 'NJ', 2662),
 ('Helen', 'Coke', 4, 12, 2003, 'CT', 2172),
 ('Helen', 'Coke', 31, 12, 2007, 'NJ', 3804),
 ('Helen', 'Cookies', 15, 7, 2005, 'NJ', 1965),
 ('Helen', 'Cookies', 19, 7, 2004, 'NY', 1080),
 ('Helen', 'Cookies', 28, 8, 2002, 'NY', 3494),
 ('Helen', 'Cookies', 16, 11, 2006, 'CT', 1164),
 ('Helen', 'Cookies', 23, 12, 2004, 'CT', 1194),
 ('Helen', 'Eggs', 7, 2, 2003, 'PA', 813),
 ('Helen', 'Eggs', 17, 4, 2006, 'CT', 1807),
 ('Helen', 'Eggs', 13, 5, 2000, 'CT', 1483),
 ('Helen', 'Eggs', 21, 6, 2004, 'NY', 3200),
 ('Helen', 'Eggs', 13, 6, 2000, 'PA', 2817),
 ('Helen', 'Eggs', 21, 10, 2002, 'CT', 4162),
 ('Helen', 'Eggs', 5, 10, 2003, 'PA', 1045),
 ('Helen', 'Eggs', 18, 10, 2004, 'CT', 1754),
 ('Helen', 'Fruits', 21, 1, 2005, 'CT', 2360),
 ('Helen', 'Fruits', 19, 2, 2003, 'CT', 951),
 ('Helen', 'Fruits', 27, 2, 2007, 'CT', 442),
 ('Helen', 'Fruits', 30, 3, 2007, 'CT', 2525),
 ('Helen', 'Fruits', 3, 5, 2006, 'NY', 2774),
 ('Helen', 'Fruits', 28, 6, 2005, 'PA', 2811),
 ('Helen', 'Fruits', 5, 6, 2003, 'NJ', 415),
 ('Helen', 'Fruits', 25, 12, 2006, 'CT', 4015),
 ('Helen', 'Fruits', 17, 12, 2004, 'CT', 268),
 ('Helen', 'Milk', 6, 1, 2003, 'CT', 4429),
 ('Helen', 'Milk', 21, 1, 2006, 'NJ', 1839),
 ('Helen', 'Milk', 28, 2, 2006, 'PA', 4794),
 ('Helen', 'Milk', 28, 2, 2006, 'NY', 4249),
 ('Helen', 'Milk', 6, 3, 2003, 'CT', 1249),
 ('Helen', 'Milk', 13, 4, 2000, 'NY', 888),
 ('Helen', 'Milk', 9, 4, 2000, 'NY', 77),
 ('Helen', 'Milk', 10, 5, 2001, 'PA', 1457),
 ('Helen', 'Milk', 19, 9, 2002, 'PA', 3314),
 ('Helen', 'Milk', 7, 11, 2006, 'CT', 210),
 ('Helen', 'Milk', 6, 11, 2001, 'NY', 2422),
 ('Helen', 'Milk', 24, 12, 2006, 'NY', 311),
 ('Helen', 'Pepsi', 31, 1, 2008, 'NJ', 4412),
 ('Helen', 'Pepsi', 18, 1, 2006, 'NJ', 2232),
 ('Helen', 'Pepsi', 13, 2, 2001, 'NJ', 1983),
 ('Helen', 'Pepsi', 14, 3, 2002, 'NJ', 3891),
 ('Helen', 'Pepsi', 23, 4, 2007, 'CT', 3609),
 ('Helen', 'Pepsi', 13, 4, 2006, 'NY', 1931),
 ('Helen', 'Pepsi', 25, 5, 2003, 'NY', 2590),
 ('Helen', 'Pepsi', 23, 6, 2000, 'PA', 1456),
 ('Helen', 'Pepsi', 24, 9, 2004, 'CT', 2768),
 ('Helen', 'Pepsi', 20, 10, 2002, 'NJ', 3817),
 ('Helen', 'Pepsi', 1, 10, 2005, 'PA', 1407),
 ('Helen', 'Pepsi', 12, 12, 2002, 'CT', 1515),
 ('Helen', 'Pepsi', 14, 12, 2005, 'NY', 3002),
 ('Helen', 'Soap', 10, 1, 2003, 'NJ', 4702),
 ('Helen', 'Soap', 22, 3, 2008, 'CT', 2203),
 ('Helen', 'Soap', 21, 7, 2004, 'PA', 4107),
 ('Helen', 'Soap', 26, 8, 2005, 'CT', 1301),
 ('Helen', 'Soap', 19, 8, 2005, 'NJ', 3618),
 ('Helen', 'Soap', 3, 9, 2007, 'NJ', 2934),
 ('Helen', 'Soap', 25, 10, 2006, 'NJ', 712),
 ('Helen', 'Soap', 27, 11, 2001, 'PA', 925),
 ('Helen', 'Soap', 18, 11, 2007, 'NJ', 1991),
 ('Helen', 'Yogurt', 19, 1, 2007, 'NJ', 2096),
 ('Helen', 'Yogurt', 6, 2, 2000, 'PA', 4001),
 ('Helen', 'Yogurt', 24, 2, 2004, 'NY', 900),
 ('Helen', 'Yogurt', 18, 4, 2005, 'NY', 2516),
 ('Helen', 'Yogurt', 20, 6, 2004, 'CT', 3832),
 ('Helen', 'Yogurt', 8, 8, 2007, 'NY', 4909),
 ('Helen', 'Yogurt', 22, 8, 2006, 'NY', 787),
 ('Helen', 'Yogurt', 12, 9, 2003, 'CT', 3015),
 ('Helen', 'Yogurt', 1, 10, 2007, 'CT', 3366),
 ('Helen', 'Yogurt', 2, 12, 2005, 'NY', 1128),
 ('Knuth', 'Bread', 13, 1, 2002, 'PA', 3049),
 ('Knuth', 'Bread', 3, 2, 2004, 'CT', 1914),
 ('Knuth', 'Bread', 16, 2, 2007, 'CT', 4127),
 ('Knuth', 'Bread', 27, 3, 2008, 'CT', 4372),
 ('Knuth', 'Bread', 14, 4, 2002, 'NY', 3370),
 ('Knuth', 'Bread', 7, 5, 2003, 'PA', 3664),
 ('Knuth', 'Bread', 23, 5, 2005, 'PA', 4167),
 ('Knuth', 'Bread', 19, 6, 2005, 'PA', 1932),
 ('Knuth', 'Bread', 16, 8, 2004, 'CT', 1095),
 ('Knuth', 'Bread', 5, 8, 2000, 'CT', 2063),
 ('Knuth', 'Bread', 9, 10, 2002, 'CT', 1796),
 ('Knuth', 'Bread', 2, 11, 2002, 'NJ', 1013),
 ('Knuth', 'Butter', 28, 3, 2004, 'PA', 516),
 ('Knuth', 'Butter', 4, 3, 2008, 'CT', 2232),
 ('Knuth', 'Butter', 1, 4, 2007, 'NY', 839),
 ('Knuth', 'Butter', 9, 6, 2004, 'NY', 950),
 ('Knuth', 'Butter', 2, 10, 2007, 'NY', 156),
 ('Knuth', 'Butter', 8, 10, 2008, 'PA', 2852),
 ('Knuth', 'Coke', 6, 1, 2003, 'CT', 1557),
 ('Knuth', 'Coke', 29, 1, 2005, 'PA', 4364),
 ('Knuth', 'Coke', 23, 2, 2003, 'PA', 4757),
 ('Knuth', 'Coke', 9, 4, 2002, 'CT', 4027),
 ('Knuth', 'Coke', 9, 5, 2005, 'NY', 1946),
 ('Knuth', 'Coke', 8, 5, 2004, 'NJ', 1583),
 ('Knuth', 'Coke', 23, 6, 2007, 'CT', 2660),
 ('Knuth', 'Coke', 30, 6, 2008, 'PA', 3166),
 ('Knuth', 'Coke', 8, 7, 2001, 'CT', 211),
 ('Knuth', 'Coke', 17, 8, 2007, 'PA', 2812),
 ('Knuth', 'Coke', 9, 10, 2002, 'NJ', 766),
 ('Knuth', 'Coke', 3, 10, 2000, 'NJ', 4672),
 ('Knuth', 'Coke', 13, 12, 2007, 'PA', 2928),
 ('Knuth', 'Cookies', 20, 2, 2000, 'NJ', 4237),
 ('Knuth', 'Cookies', 7, 3, 2002, 'PA', 488),
 ('Knuth', 'Cookies', 12, 6, 2007, 'NJ', 2615),
 ('Knuth', 'Cookies', 6, 6, 2003, 'NJ', 3683),
 ('Knuth', 'Cookies', 29, 6, 2006, 'CT', 2635),
 ('Knuth', 'Cookies', 17, 7, 2003, 'CT', 4994),
 ('Knuth', 'Cookies', 3, 7, 2003, 'CT', 2423),
 ('Knuth', 'Cookies', 25, 10, 2004, 'NJ', 2154),
 ('Knuth', 'Cookies', 7, 10, 2001, 'PA', 1367),
 ('Knuth', 'Cookies', 23, 12, 2008, 'NY', 1485),
 ('Knuth', 'Eggs', 6, 2, 2006, 'NY', 3788),
 ('Knuth', 'Eggs', 12, 2, 2007, 'NY', 4313),
 ('Knuth', 'Eggs', 9, 4, 2003, 'CT', 2151),
 ('Knuth', 'Eggs', 8, 4, 2006, 'PA', 326),
 ('Knuth', 'Eggs', 22, 9, 2003, 'PA', 3532),
 ('Knuth', 'Eggs', 18, 10, 2001, 'NJ', 2353),
 ('Knuth', 'Eggs', 2, 11, 2004, 'CT', 4317),
 ('Knuth', 'Eggs', 12, 11, 2004, 'CT', 1950),
 ('Knuth', 'Eggs', 2, 12, 2008, 'CT', 1312),
 ('Knuth', 'Eggs', 19, 12, 2006, 'NJ', 1339),
 ('Knuth', 'Fruits', 12, 1, 2002, 'NJ', 1368),
 ('Knuth', 'Fruits', 1, 2, 2003, 'PA', 4475),
 ('Knuth', 'Fruits', 4, 2, 2005, 'PA', 2430),
 ('Knuth', 'Fruits', 8, 4, 2005, 'CT', 973),
 ('Knuth', 'Fruits', 19, 4, 2007, 'NY', 2740),
 ('Knuth', 'Fruits', 5, 7, 2002, 'NJ', 733),
 ('Knuth', 'Fruits', 6, 7, 2001, 'CT', 3756),
 ('Knuth', 'Fruits', 24, 7, 2008, 'NY', 1062),
 ('Knuth', 'Fruits', 26, 8, 2001, 'NY', 24),
 ('Knuth', 'Fruits', 18, 9, 2003, 'CT', 159),
 ('Knuth', 'Fruits', 16, 9, 2003, 'PA', 1313),
 ('Knuth', 'Fruits', 25, 10, 2006, 'NY', 1181),
 ('Knuth', 'Fruits', 30, 11, 2002, 'PA', 1718),
 ('Knuth', 'Fruits', 23, 12, 2008, 'NJ', 3939),
 ('Knuth', 'Milk', 5, 2, 2007, 'PA', 126),
 ('Knuth', 'Milk', 25, 3, 2001, 'CT', 58),
 ('Knuth', 'Milk', 13, 4, 2006, 'NY', 2424),
 ('Knuth', 'Milk', 6, 10, 2003, 'PA', 1088),
 ('Knuth', 'Pepsi', 3, 2, 2005, 'NY', 3879),
 ('Knuth', 'Pepsi', 2, 3, 2002, 'NJ', 2548),
 ('Knuth', 'Pepsi', 29, 4, 2002, 'CT', 1481),
 ('Knuth', 'Pepsi', 2, 6, 2002, 'NY', 3936),
 ('Knuth', 'Pepsi', 17, 6, 2008, 'PA', 2390),
 ('Knuth', 'Pepsi', 15, 6, 2001, 'NJ', 2064),
 ('Knuth', 'Pepsi', 27, 7, 2008, 'NJ', 4689),
 ('Knuth', 'Pepsi', 12, 8, 2004, 'CT', 1244),
 ('Knuth', 'Pepsi', 29, 8, 2001, 'NJ', 277),
 ('Knuth', 'Pepsi', 11, 9, 2004, 'NY', 4942),
 ('Knuth', 'Pepsi', 6, 9, 2006, 'CT', 3760),
 ('Knuth', 'Pepsi', 21, 12, 2008, 'CT', 653),
 ('Knuth', 'Pepsi', 13, 12, 2007, 'PA', 2538),
 ('Knuth', 'Soap', 16, 1, 2001, 'CT', 1098),
 ('Knuth', 'Soap', 9, 2, 2005, 'NJ', 657),
 ('Knuth', 'Soap', 13, 4, 2008, 'CT', 1160),
 ('Knuth', 'Soap', 17, 4, 2008, 'CT', 436),
 ('Knuth', 'Soap', 29, 5, 2001, 'PA', 2961),
 ('Knuth', 'Soap', 22, 8, 2005, 'NY', 1002),
 ('Knuth', 'Soap', 27, 10, 2006, 'CT', 2231),
 ('Knuth', 'Soap', 12, 11, 2007, 'NY', 3063),
 ('Knuth', 'Soap', 18, 11, 2004, 'PA', 586),
 ('Knuth', 'Soap', 23, 11, 2002, 'CT', 2915),
 ('Knuth', 'Soap', 16, 12, 2001, 'NY', 4307),
 ('Knuth', 'Yogurt', 29, 2, 2000, 'NY', 3445),
 ('Knuth', 'Yogurt', 14, 3, 2007, 'PA', 4361),
 ('Knuth', 'Yogurt', 22, 4, 2005, 'CT', 301),
 ('Knuth', 'Yogurt', 16, 5, 2000, 'PA', 3396),
 ('Knuth', 'Yogurt', 3, 6, 2004, 'PA', 1285),
 ('Knuth', 'Yogurt', 9, 6, 2001, 'NJ', 2167),
 ('Knuth', 'Yogurt', 18, 9, 2001, 'NY', 3705),
 ('Knuth', 'Yogurt', 2, 10, 2006, 'PA', 2497),
 ('Sam', 'Bread', 18, 1, 2002, 'NJ', 1378),
 ('Sam', 'Bread', 11, 4, 2006, 'NY', 2282),
 ('Sam', 'Bread', 13, 6, 2007, 'NJ', 3187),
 ('Sam', 'Bread', 22, 7, 2006, 'CT', 207),
 ('Sam', 'Bread', 7, 7, 2007, 'PA', 872),
 ('Sam', 'Bread', 29, 8, 2000, 'CT', 1599),
 ('Sam', 'Bread', 26, 9, 2001, 'NJ', 3809),
 ('Sam', 'Bread', 13, 11, 2008, 'PA', 93),
 ('Sam', 'Butter', 27, 2, 2006, 'PA', 673),
 ('Sam', 'Butter', 18, 4, 2004, 'NJ', 4453),
 ('Sam', 'Butter', 9, 6, 2008, 'NJ', 3659),
 ('Sam', 'Butter', 30, 9, 2006, 'NY', 4893),
 ('Sam', 'Butter', 20, 10, 2006, 'NY', 1966),
 ('Sam', 'Butter', 22, 12, 2000, 'NJ', 1715),
 ('Sam', 'Butter', 14, 12, 2007, 'NJ', 3019),
 ('Sam', 'Butter', 20, 12, 2002, 'NY', 1234),
 ('Sam', 'Coke', 14, 1, 2003, 'NY', 2668),
 ('Sam', 'Coke', 23, 1, 2006, 'CT', 2672),
 ('Sam', 'Coke', 20, 5, 2007, 'CT', 2819),
 ('Sam', 'Coke', 21, 6, 2003, 'NY', 142),
 ('Sam', 'Coke', 24, 8, 2004, 'PA', 3053),
 ('Sam', 'Cookies', 8, 2, 2008, 'CT', 2523),
 ('Sam', 'Cookies', 9, 5, 2004, 'PA', 454),
 ('Sam', 'Cookies', 23, 6, 2003, 'PA', 362),
 ('Sam', 'Cookies', 9, 10, 2007, 'CT', 132),
 ('Sam', 'Cookies', 17, 11, 2002, 'PA', 3725),
 ('Sam', 'Cookies', 20, 11, 2004, 'NY', 3376),
 ('Sam', 'Cookies', 22, 12, 2008, 'PA', 1657),
 ('Sam', 'Eggs', 31, 1, 2005, 'PA', 4610),

In [62]:
%%sql 
with t1 as(
    select * 
    from sales 
    order by cust, prod,quant asc
)
    select cust,prod,sum(quant)*0.6666667 as two_three_prod
    from t1
    group by cust,prod
    order by cust, prod

 * postgresql://postgres:***@127.0.0.1/salesdb
50 rows affected.

[('Bloom', 'Bread', Decimal('16895.3341781')),
 ('Bloom', 'Butter', Decimal('6034.0003017')),
 ('Bloom', 'Coke', Decimal('14033.3340350')),
 ('Bloom', 'Cookies', Decimal('18414.6675874')),
 ('Bloom', 'Eggs', Decimal('18368.6675851')),
 ('Bloom', 'Fruits', Decimal('28007.3347337')),
 ('Bloom', 'Milk', Decimal('23960.6678647')),
 ('Bloom', 'Pepsi', Decimal('10260.0005130')),
 ('Bloom', 'Soap', Decimal('9509.3338088')),
 ('Bloom', 'Yogurt', Decimal('11780.0005890')),
 ('Emily', 'Bread', Decimal('10228.6671781')),
 ('Emily', 'Butter', Decimal('13901.3340284')),
 ('Emily', 'Coke', Decimal('14454.0007227')),
 ('Emily', 'Cookies', Decimal('28510.0014255')),
 ('Emily', 'Eggs', Decimal('22053.3344360')),
 ('Emily', 'Fruits', Decimal('23372.6678353')),
 ('Emily', 'Milk', Decimal('14204.6673769')),
 ('Emily', 'Pepsi', Decimal('15188.0007594')),
 ('Emily', 'Soap', Decimal('12860.0006430')),
 ('Emily', 'Yogurt', Decimal('11006.6672170')),
 ('Helen', 'Bread', Decimal('16688.0008344')),
 ('Helen', 'Butter', Decimal('27995.3347331')),
 ('Helen', 'Coke', Decimal('26175.3346421')),
 ('Helen', 'Cookies', Decimal('5931.3336299')),
 ('Helen', 'Eggs', Decimal('11387.3339027')),
 ('Helen', 'Fruits', Decimal('11040.6672187')),
 ('Helen', 'Milk', Decimal('16826.0008413')),
 ('Helen', 'Pepsi', Decimal('23075.3344871')),
 ('Helen', 'Soap', Decimal('14995.3340831')),
 ('Helen', 'Yogurt', Decimal('17700.0008850')),
 ('Knuth', 'Bread', Decimal('21708.0010854')),
 ('Knuth', 'Butter', Decimal('5030.0002515')),
 ('Knuth', 'Coke', Decimal('23632.6678483')),
 ('Knuth', 'Cookies', Decimal('17387.3342027')),
 ('Knuth', 'Eggs', Decimal('16920.6675127')),
 ('Knuth', 'Fruits', Decimal('17247.3341957')),
 ('Knuth', 'Milk', Decimal('2464.0001232')),
 ('Knuth', 'Pepsi', Decimal('22934.0011467')),
 ('Knuth', 'Soap', Decimal('13610.6673472')),
 ('Knuth', 'Yogurt', Decimal('14104.6673719')),
 ('Sam', 'Bread', Decimal('8951.3337809')),
 ('Sam', 'Butter', Decimal('14408.0007204')),
 ('Sam', 'Coke', Decimal('7569.3337118')),
 ('Sam', 'Cookies', Decimal('8152.6670743')),
 ('Sam', 'Eggs', Decimal('12651.3339659')),
 ('Sam', 'Fruits', Decimal('22586.0011293')),
 ('Sam', 'Milk', Decimal('15726.0007863')),
 ('Sam', 'Pepsi', Decimal('25898.6679616')),
 ('Sam', 'Soap', Decimal('16143.3341405')),
 ('Sam', 'Yogurt', Decimal('14212.6673773'))]

In [65]:
%%sql
with t1 as(
    select * 
    from sales 
    order by cust, prod,quant asc
)
select month, (
    select sum(acc) from t1 as b where b.quant<= a.quant) as acc
from t1 as a 
group by id;

 * postgresql://postgres:***@127.0.0.1/salesdb
(psycopg2.errors.UndefinedColumn) column "acc" does not exist
LINE 7:     select sum(acc) from t1 as b where b.quant<= a.quant) as...
                       ^

[SQL: with t1 as(
    select *
    from sales
    order by cust, prod,quant asc
)
select month, (
    select sum(acc) from t1 as b where b.quant<= a.quant) as acc
from t1 as a
group by id;]
(Background on this error at: http://sqlalche.me/e/f405)

In [74]:
%%sql
with t1 as(
    select * 
    from sales 
    order by cust, prod,quant asc
)
select b.cust, b.prod, b.quant,b.month, sum(a.quant) 
from t1 as a,t1 as b 
where a.month<=b.month 
group by b.cust, b.prod,b.quant,b.month
order by b.cust,b.prod,b.month

 * postgresql://postgres:***@127.0.0.1/salesdb
500 rows affected.

[('Bloom', 'Bread', 2220, 1, 126442),
 ('Bloom', 'Bread', 4778, 2, 234423),
 ('Bloom', 'Bread', 3792, 3, 302436),
 ('Bloom', 'Bread', 2277, 3, 302436),
 ('Bloom', 'Bread', 417, 4, 411220),
 ('Bloom', 'Bread', 944, 6, 602411),
 ('Bloom', 'Bread', 256, 6, 602411),
 ('Bloom', 'Bread', 1494, 7, 707536),
 ('Bloom', 'Bread', 3100, 8, 781080),
 ('Bloom', 'Bread', 3261, 9, 885213),
 ('Bloom', 'Bread', 1698, 9, 885213),
 ('Bloom', 'Bread', 1106, 12, 1194294),
 ('Bloom', 'Butter', 1054, 8, 781080),
 ('Bloom', 'Butter', 3718, 9, 885213),
 ('Bloom', 'Butter', 4279, 10, 996557),
 ('Bloom', 'Coke', 928, 1, 126442),
 ('Bloom', 'Coke', 1229, 2, 234423),
 ('Bloom', 'Coke', 2681, 4, 411220),
 ('Bloom', 'Coke', 3058, 7, 707536),
 ('Bloom', 'Coke', 3640, 7, 707536),
 ('Bloom', 'Coke', 3654, 7, 707536),
 ('Bloom', 'Coke', 279, 8, 781080),
 ('Bloom', 'Coke', 2714, 9, 885213),
 ('Bloom', 'Coke', 2867, 10, 996557),
 ('Bloom', 'Cookies', 1676, 6, 602411),
 ('Bloom', 'Cookies', 3887, 6, 602411),
 ('Bloom', 'Cookies', 4546, 7, 707536),
 ('Bloom', 'Cookies', 4240, 9, 885213),
 ('Bloom', 'Cookies', 2504, 9, 885213),
 ('Bloom', 'Cookies', 1858, 9, 885213),
 ('Bloom', 'Cookies', 3545, 10, 996557),
 ('Bloom', 'Cookies', 4570, 10, 996557),
 ('Bloom', 'Cookies', 796, 11, 1101990),
 ('Bloom', 'Eggs', 4972, 1, 126442),
 ('Bloom', 'Eggs', 666, 1, 126442),
 ('Bloom', 'Eggs', 3723, 4, 411220),
 ('Bloom', 'Eggs', 2865, 4, 411220),
 ('Bloom', 'Eggs', 3621, 4, 411220),
 ('Bloom', 'Eggs', 4177, 5, 497974),
 ('Bloom', 'Eggs', 1219, 7, 707536),
 ('Bloom', 'Eggs', 3150, 9, 885213),
 ('Bloom', 'Eggs', 1573, 11, 1101990),
 ('Bloom', 'Eggs', 1028, 11, 1101990),
 ('Bloom', 'Eggs', 559, 11, 1101990),
 ('Bloom', 'Fruits', 3006, 1, 126442),
 ('Bloom', 'Fruits', 4085, 1, 126442),
 ('Bloom', 'Fruits', 3623, 1, 126442),
 ('Bloom', 'Fruits', 776, 2, 234423),
 ('Bloom', 'Fruits', 1268, 3, 302436),
 ('Bloom', 'Fruits', 699, 3, 302436),
 ('Bloom', 'Fruits', 2692, 4, 411220),
 ('Bloom', 'Fruits', 570, 4, 411220),
 ('Bloom', 'Fruits', 4444, 5, 497974),
 ('Bloom', 'Fruits', 26, 6, 602411),
 ('Bloom', 'Fruits', 2813, 7, 707536),
 ('Bloom', 'Fruits', 612, 7, 707536),
 ('Bloom', 'Fruits', 3653, 7, 707536),
 ('Bloom', 'Fruits', 3798, 8, 781080),
 ('Bloom', 'Fruits', 4094, 8, 781080),
 ('Bloom', 'Fruits', 4020, 11, 1101990),
 ('Bloom', 'Fruits', 1832, 11, 1101990),
 ('Bloom', 'Milk', 2220, 1, 126442),
 ('Bloom', 'Milk', 4583, 1, 126442),
 ('Bloom', 'Milk', 2843, 3, 302436),
 ('Bloom', 'Milk', 3516, 4, 411220),
 ('Bloom', 'Milk', 1820, 5, 497974),
 ('Bloom', 'Milk', 1794, 5, 497974),
 ('Bloom', 'Milk', 1106, 9, 885213),
 ('Bloom', 'Milk', 2004, 10, 996557),
 ('Bloom', 'Milk', 4377, 10, 996557),
 ('Bloom', 'Milk', 553, 10, 996557),
 ('Bloom', 'Milk', 4870, 10, 996557),
 ('Bloom', 'Milk', 1639, 12, 1194294),
 ('Bloom', 'Milk', 4616, 12, 1194294),
 ('Bloom', 'Pepsi', 526, 1, 126442),
 ('Bloom', 'Pepsi', 2367, 5, 497974),
 ('Bloom', 'Pepsi', 1368, 6, 602411),
 ('Bloom', 'Pepsi', 94, 7, 707536),
 ('Bloom', 'Pepsi', 254, 8, 781080),
 ('Bloom', 'Pepsi', 2034, 9, 885213),
 ('Bloom', 'Pepsi', 4515, 11, 1101990),
 ('Bloom', 'Pepsi', 4232, 12, 1194294),
 ('Bloom', 'Soap', 4623, 1, 126442),
 ('Bloom', 'Soap', 1216, 4, 411220),
 ('Bloom', 'Soap', 3404, 6, 602411),
 ('Bloom', 'Soap', 387, 7, 707536),
 ('Bloom', 'Soap', 270, 9, 885213),
 ('Bloom', 'Soap', 4364, 11, 1101990),
 ('Bloom', 'Yogurt', 1660, 3, 302436),
 ('Bloom', 'Yogurt', 4043, 4, 411220),
 ('Bloom', 'Yogurt', 1203, 4, 411220),
 ('Bloom', 'Yogurt', 17, 7, 707536),
 ('Bloom', 'Yogurt', 3172, 9, 885213),
 ('Bloom', 'Yogurt', 4004, 9, 885213),
 ('Bloom', 'Yogurt', 2788, 10, 996557),
 ('Bloom', 'Yogurt', 783, 12, 1194294),
 ('Emily', 'Bread', 492, 3, 302436),
 ('Emily', 'Bread', 4467, 4, 411220),
 ('Emily', 'Bread', 2135, 4, 411220),
 ('Emily', 'Bread', 232, 5, 497974),
 ('Emily', 'Bread', 141, 6, 602411),
 ('Emily', 'Bread', 1626, 6, 602411),
 ('Emily', 'Bread', 42, 9, 885213),
 ('Emily', 'Bread', 1572, 9, 885213),
 ('Emily', 'Bread', 2565, 11, 1101990),
 ('Emily', 'Bread', 2071, 12, 1194294),
 ('Emily', 'Butter', 212, 2, 234423),
 ('Emily', 'Butter', 2826, 2, 234423),
 ('Emily', 'Butter', 1432, 2, 234423),
 ('Emily', 'Butter', 1491, 2, 234423),
 ('Emily', 'Butter', 2869, 6, 602411),
 ('Emily', 'Butter', 4008, 7, 707536),
 ('Emily', 'Butter', 3840, 7, 707536),
 ('Emily', 'Butter', 1312, 8, 781080),
 ('Emily', 'Butter', 2862, 11, 1101990),
 ('Emily', 'Coke', 2192, 1, 126442),
 ('Emily', 'Coke', 4258, 2, 234423),
 ('Emily', 'Coke', 1330, 2, 234423),
 ('Emily', 'Coke', 2909, 2, 234423),
 ('Emily', 'Coke', 1301, 2, 234423),
 ('Emily', 'Coke', 3314, 6, 602411),
 ('Emily', 'Coke', 4379, 8, 781080),
 ('Emily', 'Coke', 81, 11, 1101990),
 ('Emily', 'Coke', 1917, 11, 1101990),
 ('Emily', 'Cookies', 3654, 1, 126442),
 ('Emily', 'Cookies', 3238, 1, 126442),
 ('Emily', 'Cookies', 2500, 2, 234423),
 ('Emily', 'Cookies', 3669, 4, 411220),
 ('Emily', 'Cookies', 2685, 5, 497974),
 ('Emily', 'Cookies', 4925, 6, 602411),
 ('Emily', 'Cookies', 1844, 7, 707536),
 ('Emily', 'Cookies', 1827, 7, 707536),
 ('Emily', 'Cookies', 1477, 7, 707536),
 ('Emily', 'Cookies', 1656, 10, 996557),
 ('Emily', 'Cookies', 658, 10, 996557),
 ('Emily', 'Cookies', 173, 11, 1101990),
 ('Emily', 'Cookies', 3719, 11, 1101990),
 ('Emily', 'Cookies', 2497, 11, 1101990),
 ('Emily', 'Cookies', 3308, 12, 1194294),
 ('Emily', 'Cookies', 4935, 12, 1194294),
 ('Emily', 'Eggs', 4535, 1, 126442),
 ('Emily', 'Eggs', 4658, 4, 411220),
 ('Emily', 'Eggs', 771, 4, 411220),
 ('Emily', 'Eggs', 2012, 7, 707536),
 ('Emily', 'Eggs', 3030, 7, 707536),
 ('Emily', 'Eggs', 4754, 8, 781080),
 ('Emily', 'Eggs', 3126, 9, 885213),
 ('Emily', 'Eggs', 4689, 10, 996557),
 ('Emily', 'Eggs', 1060, 11, 1101990),
 ('Emily', 'Eggs', 2722, 11, 1101990),
 ('Emily', 'Eggs', 128, 11, 1101990),
 ('Emily', 'Eggs', 1595, 12, 1194294),
 ('Emily', 'Fruits', 4369, 1, 126442),
 ('Emily', 'Fruits', 1469, 3, 302436),
 ('Emily', 'Fruits', 1573, 4, 411220),
 ('Emily', 'Fruits', 2102, 4, 411220),
 ('Emily', 'Fruits', 3055, 4, 411220),
 ('Emily', 'Fruits', 111, 7, 707536),
 ('Emily', 'Fruits', 2243, 7, 707536),
 ('Emily', 'Fruits', 3913, 8, 781080),
 ('Emily', 'Fruits', 4731, 8, 781080),
 ('Emily', 'Fruits', 3027, 10, 996557),
 ('Emily', 'Fruits', 3743, 11, 1101990),
 ('Emily', 'Fruits', 859, 11, 1101990),
 ('Emily', 'Fruits', 3864, 12, 1194294),
 ('Emily', 'Milk', 2589, 3, 302436),
 ('Emily', 'Milk', 3257, 4, 411220),
 ('Emily', 'Milk', 3211, 4, 411220),
 ('Emily', 'Milk', 1274, 6, 602411),
 ('Emily', 'Milk', 26, 7, 707536),
 ('Emily', 'Milk', 2125, 7, 707536),
 ('Emily', 'Milk', 3839, 9, 885213),
 ('Emily', 'Milk', 4986, 11, 1101990),
 ('Emily', 'Pepsi', 2591, 1, 126442),
 ('Emily', 'Pepsi', 4404, 1, 126442),
 ('Emily', 'Pepsi', 4531, 3, 302436),
 ('Emily', 'Pepsi', 1682, 5, 497974),
 ('Emily', 'Pepsi', 4901, 5, 497974),
 ('Emily', 'Pepsi', 538, 6, 602411),
 ('Emily', 'Pepsi', 4135, 10, 996557),
 ('Emily', 'Soap', 3218, 1, 126442),
 ('Emily', 'Soap', 2549, 4, 411220),
 ('Emily', 'Soap', 623, 7, 707536),
 ('Emily', 'Soap', 3901, 8, 781080),
 ('Emily', 'Soap', 70, 9, 885213),
 ('Emily', 'Soap', 4081, 10, 996557),
 ('Emily', 'Soap', 742, 10, 996557),
 ('Emily', 'Soap', 4106, 11, 1101990),
 ('Emily', 'Yogurt', 2336, 3, 302436),
 ('Emily', 'Yogurt', 3822, 3, 302436),
 ('Emily', 'Yogurt', 2126, 5, 497974),
 ('Emily', 'Yogurt', 3174, 6, 602411),
 ('Emily', 'Yogurt', 3765, 8, 781080),
 ('Emily', 'Yogurt', 557, 8, 781080),
 ('Emily', 'Yogurt', 730, 10, 996557),
 ('Helen', 'Bread', 3530, 1, 126442),
 ('Helen', 'Bread', 1406, 5, 497974),
 ('Helen', 'Bread', 4901, 5, 497974),
 ('Helen', 'Bread', 389, 5, 497974),
 ('Helen', 'Bread', 4855, 6, 602411),
 ('Helen', 'Bread', 1687, 6, 602411),
 ('Helen', 'Bread', 2513, 10, 996557),
 ('Helen', 'Bread', 1637, 11, 1101990),
 ('Helen', 'Bread', 4114, 12, 1194294),
 ('Helen', 'Butter', 728, 1, 126442),
 ('Helen', 'Butter', 4281, 1, 126442),
 ('Helen', 'Butter', 566, 2, 234423),
 ('Helen', 'Butter', 1025, 2, 234423),
 ('Helen', 'Butter', 3288, 2, 234423),
 ('Helen', 'Butter', 2483, 2, 234423),
 ('Helen', 'Butter', 2160, 2, 234423),
 ('Helen', 'Butter', 1786, 3, 302436),
 ('Helen', 'Butter', 1978, 4, 411220),
 ('Helen', 'Butter', 1712, 4, 411220),
 ('Helen', 'Butter', 4969, 6, 602411),
 ('Helen', 'Butter', 942, 7, 707536),
 ('Helen', 'Butter', 3859, 7, 707536),
 ('Helen', 'Butter', 1174, 7, 707536),
 ('Helen', 'Butter', 4364, 7, 707536),
 ('Helen', 'Butter', 2086, 7, 707536),
 ('Helen', 'Butter', 163, 8, 781080),
 ('Helen', 'Butter', 803, 9, 885213),
 ('Helen', 'Butter', 306, 11, 1101990),
 ('Helen', 'Butter', 1685, 11, 1101990),
 ('Helen', 'Butter', 1357, 11, 1101990),
 ('Helen', 'Butter', 278, 11, 1101990),
 ('Helen', 'Coke', 4237, 2, 234423),
 ('Helen', 'Coke', 3132, 2, 234423),
 ('Helen', 'Coke', 755, 2, 234423),
 ('Helen', 'Coke', 668, 4, 411220),
 ('Helen', 'Coke', 2331, 4, 411220),
 ('Helen', 'Coke', 3345, 5, 497974),
 ('Helen', 'Coke', 1099, 5, 497974),
 ('Helen', 'Coke', 2554, 5, 497974),
 ('Helen', 'Coke', 3198, 7, 707536),
 ('Helen', 'Coke', 2401, 7, 707536),
 ('Helen', 'Coke', 3065, 10, 996557),
 ('Helen', 'Coke', 2662, 10, 996557),
 ('Helen', 'Coke', 3840, 10, 996557),
 ('Helen', 'Coke', 2172, 12, 1194294),
 ('Helen', 'Coke', 3804, 12, 1194294),
 ('Helen', 'Cookies', 1080, 7, 707536),
 ('Helen', 'Cookies', 1965, 7, 707536),
 ('Helen', 'Cookies', 3494, 8, 781080),
 ('Helen', 'Cookies', 1164, 11, 1101990),
 ('Helen', 'Cookies', 1194, 12, 1194294),
 ('Helen', 'Eggs', 813, 2, 234423),
 ('Helen', 'Eggs', 1807, 4, 411220),
 ('Helen', 'Eggs', 1483, 5, 497974),
 ('Helen', 'Eggs', 3200, 6, 602411),
 ('Helen', 'Eggs', 2817, 6, 602411),
 ('Helen', 'Eggs', 4162, 10, 996557),
 ('Helen', 'Eggs', 1045, 10, 996557),
 ('Helen', 'Eggs', 1754, 10, 996557),
 ('Helen', 'Fruits', 2360, 1, 126442),
 ('Helen', 'Fruits', 442, 2, 234423),
 ('Helen', 'Fruits', 951, 2, 234423),
 ('Helen', 'Fruits', 2525, 3, 302436),
 ('Helen', 'Fruits', 2774, 5, 497974),
 ('Helen', 'Fruits', 2811, 6, 602411),
 ('Helen', 'Fruits', 415, 6, 602411),
 ('Helen', 'Fruits', 268, 12, 1194294),
 ('Helen', 'Fruits', 4015, 12, 1194294),
 ('Helen', 'Milk', 4429, 1, 126442),
 ('Helen', 'Milk', 1839, 1, 126442),
 ('Helen', 'Milk', 4249, 2, 234423),
 ('Helen', 'Milk', 4794, 2, 234423),
 ('Helen', 'Milk', 1249, 3, 302436),
 ('Helen', 'Milk', 77, 4, 411220),
 ('Helen', 'Milk', 888, 4, 411220),
 ('Helen', 'Milk', 1457, 5, 497974),
 ('Helen', 'Milk', 3314, 9, 885213),
 ('Helen', 'Milk', 2422, 11, 1101990),
 ('Helen', 'Milk', 210, 11, 1101990),
 ('Helen', 'Milk', 311, 12, 1194294),
 ('Helen', 'Pepsi', 2232, 1, 126442),
 ('Helen', 'Pepsi', 4412, 1, 126442),
 ('Helen', 'Pepsi', 1983, 2, 234423),
 ('Helen', 'Pepsi', 3891, 3, 302436),
 ('Helen', 'Pepsi', 3609, 4, 411220),
 ('Helen', 'Pepsi', 1931, 4, 411220),
 ('Helen', 'Pepsi', 2590, 5, 497974),
 ('Helen', 'Pepsi', 1456, 6, 602411),
 ('Helen', 'Pepsi', 2768, 9, 885213),
 ('Helen', 'Pepsi', 3817, 10, 996557),
 ('Helen', 'Pepsi', 1407, 10, 996557),
 ('Helen', 'Pepsi', 1515, 12, 1194294),
 ('Helen', 'Pepsi', 3002, 12, 1194294),
 ('Helen', 'Soap', 4702, 1, 126442),
 ('Helen', 'Soap', 2203, 3, 302436),
 ('Helen', 'Soap', 4107, 7, 707536),
 ('Helen', 'Soap', 1301, 8, 781080),
 ('Helen', 'Soap', 3618, 8, 781080),
 ('Helen', 'Soap', 2934, 9, 885213),
 ('Helen', 'Soap', 712, 10, 996557),
 ('Helen', 'Soap', 1991, 11, 1101990),
 ('Helen', 'Soap', 925, 11, 1101990),
 ('Helen', 'Yogurt', 2096, 1, 126442),
 ('Helen', 'Yogurt', 900, 2, 234423),
 ('Helen', 'Yogurt', 4001, 2, 234423),
 ('Helen', 'Yogurt', 2516, 4, 411220),
 ('Helen', 'Yogurt', 3832, 6, 602411),
 ('Helen', 'Yogurt', 787, 8, 781080),
 ('Helen', 'Yogurt', 4909, 8, 781080),
 ('Helen', 'Yogurt', 3015, 9, 885213),
 ('Helen', 'Yogurt', 3366, 10, 996557),
 ('Helen', 'Yogurt', 1128, 12, 1194294),
 ('Knuth', 'Bread', 3049, 1, 126442),
 ('Knuth', 'Bread', 4127, 2, 234423),
 ('Knuth', 'Bread', 1914, 2, 234423),
 ('Knuth', 'Bread', 4372, 3, 302436),
 ('Knuth', 'Bread', 3370, 4, 411220),
 ('Knuth', 'Bread', 3664, 5, 497974),
 ('Knuth', 'Bread', 4167, 5, 497974),
 ('Knuth', 'Bread', 1932, 6, 602411),
 ('Knuth', 'Bread', 2063, 8, 781080),
 ('Knuth', 'Bread', 1095, 8, 781080),
 ('Knuth', 'Bread', 1796, 10, 996557),
 ('Knuth', 'Bread', 1013, 11, 1101990),
 ('Knuth', 'Butter', 2232, 3, 302436),
 ('Knuth', 'Butter', 516, 3, 302436),
 ('Knuth', 'Butter', 839, 4, 411220),
 ('Knuth', 'Butter', 950, 6, 602411),
 ('Knuth', 'Butter', 2852, 10, 996557),
 ('Knuth', 'Butter', 156, 10, 996557),
 ('Knuth', 'Coke', 1557, 1, 126442),
 ('Knuth', 'Coke', 4364, 1, 126442),
 ('Knuth', 'Coke', 4757, 2, 234423),
 ('Knuth', 'Coke', 4027, 4, 411220),
 ('Knuth', 'Coke', 1583, 5, 497974),
 ('Knuth', 'Coke', 1946, 5, 497974),
 ('Knuth', 'Coke', 2660, 6, 602411),
 ('Knuth', 'Coke', 3166, 6, 602411),
 ('Knuth', 'Coke', 211, 7, 707536),
 ('Knuth', 'Coke', 2812, 8, 781080),
 ('Knuth', 'Coke', 4672, 10, 996557),
 ('Knuth', 'Coke', 766, 10, 996557),
 ('Knuth', 'Coke', 2928, 12, 1194294),
 ('Knuth', 'Cookies', 4237, 2, 234423),
 ('Knuth', 'Cookies', 488, 3, 302436),
 ('Knuth', 'Cookies', 3683, 6, 602411),
 ('Knuth', 'Cookies', 2615, 6, 602411),
 ('Knuth', 'Cookies', 2635, 6, 602411),
 ('Knuth', 'Cookies', 2423, 7, 707536),
 ('Knuth', 'Cookies', 4994, 7, 707536),
 ('Knuth', 'Cookies', 1367, 10, 996557),
 ('Knuth', 'Cookies', 2154, 10, 996557),
 ('Knuth', 'Cookies', 1485, 12, 1194294),
 ('Knuth', 'Eggs', 4313, 2, 234423),
 ('Knuth', 'Eggs', 3788, 2, 234423),
 ('Knuth', 'Eggs', 326, 4, 411220),
 ('Knuth', 'Eggs', 2151, 4, 411220),
 ('Knuth', 'Eggs', 3532, 9, 885213),
 ('Knuth', 'Eggs', 2353, 10, 996557),
 ('Knuth', 'Eggs', 4317, 11, 1101990),
 ('Knuth', 'Eggs', 1950, 11, 1101990),
 ('Knuth', 'Eggs', 1339, 12, 1194294),
 ('Knuth', 'Eggs', 1312, 12, 1194294),
 ('Knuth', 'Fruits', 1368, 1, 126442),
 ('Knuth', 'Fruits', 2430, 2, 234423),
 ('Knuth', 'Fruits', 4475, 2, 234423),
 ('Knuth', 'Fruits', 2740, 4, 411220),
 ('Knuth', 'Fruits', 973, 4, 411220),
 ('Knuth', 'Fruits', 1062, 7, 707536),
 ('Knuth', 'Fruits', 3756, 7, 707536),
 ('Knuth', 'Fruits', 733, 7, 707536),
 ('Knuth', 'Fruits', 24, 8, 781080),
 ('Knuth', 'Fruits', 1313, 9, 885213),
 ('Knuth', 'Fruits', 159, 9, 885213),
 ('Knuth', 'Fruits', 1181, 10, 996557),
 ('Knuth', 'Fruits', 1718, 11, 1101990),
 ('Knuth', 'Fruits', 3939, 12, 1194294),
 ('Knuth', 'Milk', 126, 2, 234423),
 ('Knuth', 'Milk', 58, 3, 302436),
 ('Knuth', 'Milk', 2424, 4, 411220),
 ('Knuth', 'Milk', 1088, 10, 996557),
 ('Knuth', 'Pepsi', 3879, 2, 234423),
 ('Knuth', 'Pepsi', 2548, 3, 302436),
 ('Knuth', 'Pepsi', 1481, 4, 411220),
 ('Knuth', 'Pepsi', 2064, 6, 602411),
 ('Knuth', 'Pepsi', 2390, 6, 602411),
 ('Knuth', 'Pepsi', 3936, 6, 602411),
 ('Knuth', 'Pepsi', 4689, 7, 707536),
 ('Knuth', 'Pepsi', 277, 8, 781080),
 ('Knuth', 'Pepsi', 1244, 8, 781080),
 ('Knuth', 'Pepsi', 4942, 9, 885213),
 ('Knuth', 'Pepsi', 3760, 9, 885213),
 ('Knuth', 'Pepsi', 653, 12, 1194294),
 ('Knuth', 'Pepsi', 2538, 12, 1194294),
 ('Knuth', 'Soap', 1098, 1, 126442),
 ('Knuth', 'Soap', 657, 2, 234423),
 ('Knuth', 'Soap', 1160, 4, 411220),
 ('Knuth', 'Soap', 436, 4, 411220),
 ('Knuth', 'Soap', 2961, 5, 497974),
 ('Knuth', 'Soap', 1002, 8, 781080),
 ('Knuth', 'Soap', 2231, 10, 996557),
 ('Knuth', 'Soap', 3063, 11, 1101990),
 ('Knuth', 'Soap', 586, 11, 1101990),
 ('Knuth', 'Soap', 2915, 11, 1101990),
 ('Knuth', 'Soap', 4307, 12, 1194294),
 ('Knuth', 'Yogurt', 3445, 2, 234423),
 ('Knuth', 'Yogurt', 4361, 3, 302436),
 ('Knuth', 'Yogurt', 301, 4, 411220),
 ('Knuth', 'Yogurt', 3396, 5, 497974),
 ('Knuth', 'Yogurt', 2167, 6, 602411),
 ('Knuth', 'Yogurt', 1285, 6, 602411),
 ('Knuth', 'Yogurt', 3705, 9, 885213),
 ('Knuth', 'Yogurt', 2497, 10, 996557),
 ('Sam', 'Bread', 1378, 1, 126442),
 ('Sam', 'Bread', 2282, 4, 411220),
 ('Sam', 'Bread', 3187, 6, 602411),
 ('Sam', 'Bread', 872, 7, 707536),
 ('Sam', 'Bread', 207, 7, 707536),
 ('Sam', 'Bread', 1599, 8, 781080),
 ('Sam', 'Bread', 3809, 9, 885213),
 ('Sam', 'Bread', 93, 11, 1101990),
 ('Sam', 'Butter', 673, 2, 234423),
 ('Sam', 'Butter', 4453, 4, 411220),
 ('Sam', 'Butter', 3659, 6, 602411),
 ('Sam', 'Butter', 4893, 9, 885213),
 ('Sam', 'Butter', 1966, 10, 996557),
 ('Sam', 'Butter', 3019, 12, 1194294),
 ('Sam', 'Butter', 1715, 12, 1194294),
 ('Sam', 'Butter', 1234, 12, 1194294),
 ('Sam', 'Coke', 2672, 1, 126442),
 ('Sam', 'Coke', 2668, 1, 126442),
 ('Sam', 'Coke', 2819, 5, 497974),
 ('Sam', 'Coke', 142, 6, 602411),
 ('Sam', 'Coke', 3053, 8, 781080),
 ('Sam', 'Cookies', 2523, 2, 234423),
 ('Sam', 'Cookies', 454, 5, 497974),
 ('Sam', 'Cookies', 362, 6, 602411),
 ('Sam', 'Cookies', 132, 10, 996557),
 ('Sam', 'Cookies', 3376, 11, 1101990),
 ('Sam', 'Cookies', 3725, 11, 1101990),
 ('Sam', 'Cookies', 1657, 12, 1194294),
 ('Sam', 'Eggs', 4610, 1, 126442),
 ('Sam', 'Eggs', 1091, 2, 234423),
 ('Sam', 'Eggs', 1744, 3, 302436),
 ('Sam', 'Eggs', 3363, 5, 497974),
 ('Sam', 'Eggs', 1114, 5, 497974),
 ('Sam', 'Eggs', 1417, 7, 707536),
 ('Sam', 'Eggs', 964, 9, 885213),
 ('Sam', 'Eggs', 4674, 11, 1101990),
 ('Sam', 'Fruits', 3743, 5, 497974),
 ('Sam', 'Fruits', 2240, 7, 707536),
 ('Sam', 'Fruits', 3800, 9, 885213),
 ('Sam', 'Fruits', 4793, 9, 885213),
 ('Sam', 'Fruits', 2409, 10, 996557),
 ('Sam', 'Fruits', 2802, 10, 996557),
 ('Sam', 'Fruits', 3399, 11, 1101990),
 ('Sam', 'Fruits', 4738, 11, 1101990),
 ('Sam', 'Fruits', 1311, 12, 1194294),
 ('Sam', 'Fruits', 4644, 12, 1194294),
 ('Sam', 'Milk', 987, 1, 126442),
 ('Sam', 'Milk', 879, 1, 126442),
 ('Sam', 'Milk', 2298, 1, 126442),
 ('Sam', 'Milk', 1126, 2, 234423),
 ('Sam', 'Milk', 3434, 2, 234423),
 ('Sam', 'Milk', 811, 4, 411220),
 ('Sam', 'Milk', 385, 4, 411220),
 ('Sam', 'Milk', 3120, 7, 707536),
 ('Sam', 'Milk', 2124, 8, 781080),
 ('Sam', 'Milk', 1132, 8, 781080),
 ('Sam', 'Milk', 1607, 11, 1101990),
 ('Sam', 'Milk', 4522, 12, 1194294),
 ('Sam', 'Milk', 1164, 12, 1194294),
 ('Sam', 'Pepsi', 1470, 3, 302436),
 ('Sam', 'Pepsi', 2841, 3, 302436),
 ('Sam', 'Pepsi', 3014, 3, 302436),
 ('Sam', 'Pepsi', 160, 4, 411220),
 ('Sam', 'Pepsi', 3468, 5, 497974),
 ('Sam', 'Pepsi', 3368, 6, 602411),
 ('Sam', 'Pepsi', 3189, 7, 707536),
 ('Sam', 'Pepsi', 3877, 9, 885213),
 ('Sam', 'Pepsi', 4797, 9, 885213),
 ('Sam', 'Pepsi', 3008, 10, 996557),
 ('Sam', 'Pepsi', 3694, 11, 1101990),
 ('Sam', 'Pepsi', 1097, 11, 1101990),
 ('Sam', 'Pepsi', 4865, 12, 1194294),
 ('Sam', 'Soap', 2461, 1, 126442),
 ('Sam', 'Soap', 2356, 1, 126442),
 ('Sam', 'Soap', 165, 2, 234423),
 ('Sam', 'Soap', 2994, 3, 302436),
 ('Sam', 'Soap', 4954, 4, 411220),
 ('Sam', 'Soap', 1883, 6, 602411),
 ('Sam', 'Soap', 1798, 6, 602411),
 ('Sam', 'Soap', 2956, 8, 781080),
 ('Sam', 'Soap', 3260, 9, 885213),
 ('Sam', 'Soap', 399, 11, 1101990),
 ('Sam', 'Soap', 989, 11, 1101990),
 ('Sam', 'Yogurt', 2142, 1, 126442),
 ('Sam', 'Yogurt', 2293, 1, 126442),
 ('Sam', 'Yogurt', 1943, 3, 302436),
 ('Sam', 'Yogurt', 1286, 5, 497974),
 ('Sam', 'Yogurt', 4564, 5, 497974),
 ('Sam', 'Yogurt', 363, 6, 602411),
 ('Sam', 'Yogurt', 4728, 6, 602411),
 ('Sam', 'Yogurt', 2683, 7, 707536),
 ('Sam', 'Yogurt', 1317, 9, 885213)]

In [ ]:
%%sql
with t1 as (
    select *
    from sales
    order by cust, prod,quant asc
),
t2 as (
    select cust,prod,sum(quant)*2/3 as two_three_prod
    from t1
    group by cust,prod
),
t3 as (
    select distinct t1.cust,t1.prod,t1.month,
    case
    when t1.quant> t2.two_three_prod then t1.month
    else 222 end
    from t1
    left join t2 using(cust,prod)
    order by t1.cust, t1.prod

)
select *
from t3

In [81]:
%%sql
With
t_all_month AS(
SELECT DISTINCT s1.prod, s1.cust,
case when s2.month in (1,2,3) then 1
     when s2.month in (4,5,6) then 2
     when s2.month in (7,8,9) then 3
     when s2.month in (10,11,12) then 4 END AS Q
FROM sales s1, sales s2
-- ORDER BY 1,2,3
),


t1 AS (
SELECT prod, cust, ROUND(AVG(quant)) AS avq,
case when month in (1,2,3) then 1
     when month in (4,5,6) then 2
     when month in (7,8,9) then 3
     when month in (10,11,12) then 4 END AS Q
FROM sales
GROUP BY prod, cust, Q
),


tbf AS(
SELECT t1.prod, t1.cust, bf.Q, bf.avq as bfq
FROM t1
LEFT JOIN t1 bf ON t1.cust = bf.cust AND t1.prod = bf.prod AND t1.Q-1 = bf.Q
-- WHERE t1.prod='Bread' and t1.cust='Bloom'
),


taf AS
(
SELECT t1.prod, t1.cust, af.Q, af.avq as afq
FROM t1
LEFT JOIN t1 af ON t1.cust = af.cust AND t1.prod = af.prod AND t1.Q+1 = af.Q
-- WHERE t1.prod='Bread' and t1.cust='Bloom'
)




SELECT ta.prod,  ta.cust,  ta.Q,
-- t1.avq, -- USED for checking
bfq as BEFORE_AVG, afq as AFTER_AVG
FROM t_all_month ta
LEFT JOIN t1 on ta.prod = t1.prod AND ta.cust = t1.cust AND ta.Q = t1.Q  -- keep 200 rows, this is neccessary
LEFT JOIN tbf ON t1.Q = tbf.Q+1 AND t1.cust = tbf.cust AND t1.prod = tbf.prod  -- NEED to add back month difference
LEFT JOIN taf ON t1.Q = taf.Q-1 AND t1.cust = taf.cust AND t1.prod = taf.prod
-- WHERE t1.prod='Bread' and t1.cust='Bloom'
ORDER BY 1,2,3

 * postgresql://postgres:***@127.0.0.1/salesdb
200 rows affected.

[('Bread', 'Bloom', 1, None, Decimal('539')),
 ('Bread', 'Bloom', 2, Decimal('3267'), Decimal('2388')),
 ('Bread', 'Bloom', 3, Decimal('539'), Decimal('1106')),
 ('Bread', 'Bloom', 4, Decimal('2388'), None),
 ('Bread', 'Emily', 1, None, Decimal('1720')),
 ('Bread', 'Emily', 2, Decimal('492'), Decimal('807')),
 ('Bread', 'Emily', 3, Decimal('1720'), Decimal('2318')),
 ('Bread', 'Emily', 4, Decimal('807'), None),
 ('Bread', 'Helen', 1, None, Decimal('2648')),
 ('Bread', 'Helen', 2, Decimal('3530'), None),
 ('Bread', 'Helen', 3, None, None),
 ('Bread', 'Helen', 4, None, None),
 ('Bread', 'Knuth', 1, None, Decimal('3283')),
 ('Bread', 'Knuth', 2, Decimal('3366'), Decimal('1579')),
 ('Bread', 'Knuth', 3, Decimal('3283'), Decimal('1405')),
 ('Bread', 'Knuth', 4, Decimal('1579'), None),
 ('Bread', 'Sam', 1, None, Decimal('2735')),
 ('Bread', 'Sam', 2, Decimal('1378'), Decimal('1622')),
 ('Bread', 'Sam', 3, Decimal('2735'), Decimal('93')),
 ('Bread', 'Sam', 4, Decimal('1622'), None),
 ('Butter', 'Bloom', 1, None, None),
 ('Butter', 'Bloom', 2, None, None),
 ('Butter', 'Bloom', 3, None, Decimal('4279')),
 ('Butter', 'Bloom', 4, Decimal('2386'), None),
 ('Butter', 'Emily', 1, None, Decimal('2869')),
 ('Butter', 'Emily', 2, Decimal('1490'), Decimal('3053')),
 ('Butter', 'Emily', 3, Decimal('2869'), Decimal('2862')),
 ('Butter', 'Emily', 4, Decimal('3053'), None),
 ('Butter', 'Helen', 1, None, Decimal('2886')),
 ('Butter', 'Helen', 2, Decimal('2040'), Decimal('1913')),
 ('Butter', 'Helen', 3, Decimal('2886'), Decimal('907')),
 ('Butter', 'Helen', 4, Decimal('1913'), None),
 ('Butter', 'Knuth', 1, None, Decimal('895')),
 ('Butter', 'Knuth', 2, Decimal('1374'), None),
 ('Butter', 'Knuth', 3, None, None),
 ('Butter', 'Knuth', 4, None, None),
 ('Butter', 'Sam', 1, None, Decimal('4056')),
 ('Butter', 'Sam', 2, Decimal('673'), Decimal('4893')),
 ('Butter', 'Sam', 3, Decimal('4056'), Decimal('1984')),
 ('Butter', 'Sam', 4, Decimal('4893'), None),
 ('Coke', 'Bloom', 1, None, Decimal('2681')),
 ('Coke', 'Bloom', 2, Decimal('1079'), Decimal('2669')),
 ('Coke', 'Bloom', 3, Decimal('2681'), Decimal('2867')),
 ('Coke', 'Bloom', 4, Decimal('2669'), None),
 ('Coke', 'Emily', 1, None, Decimal('3314')),
 ('Coke', 'Emily', 2, Decimal('2398'), Decimal('4379')),
 ('Coke', 'Emily', 3, Decimal('3314'), Decimal('999')),
 ('Coke', 'Emily', 4, Decimal('4379'), None),
 ('Coke', 'Helen', 1, None, Decimal('1999')),
 ('Coke', 'Helen', 2, Decimal('2708'), Decimal('2800')),
 ('Coke', 'Helen', 3, Decimal('1999'), Decimal('3109')),
 ('Coke', 'Helen', 4, Decimal('2800'), None),
 ('Coke', 'Knuth', 1, None, Decimal('2676')),
 ('Coke', 'Knuth', 2, Decimal('3559'), Decimal('1512')),
 ('Coke', 'Knuth', 3, Decimal('2676'), Decimal('2789')),
 ('Coke', 'Knuth', 4, Decimal('1512'), None),
 ('Coke', 'Sam', 1, None, Decimal('1481')),
 ('Coke', 'Sam', 2, Decimal('2670'), Decimal('3053')),
 ('Coke', 'Sam', 3, Decimal('1481'), None),
 ('Coke', 'Sam', 4, None, None),
 ('Cookies', 'Bloom', 1, None, None),
 ('Cookies', 'Bloom', 2, None, Decimal('3287')),
 ('Cookies', 'Bloom', 3, Decimal('2782'), Decimal('2970')),
 ('Cookies', 'Bloom', 4, Decimal('3287'), None),
 ('Cookies', 'Emily', 1, None, Decimal('3760')),
 ('Cookies', 'Emily', 2, Decimal('3131'), Decimal('1716')),
 ('Cookies', 'Emily', 3, Decimal('3760'), Decimal('2421')),
 ('Cookies', 'Emily', 4, Decimal('1716'), None),
 ('Cookies', 'Helen', 1, None, None),
 ('Cookies', 'Helen', 2, None, None),
 ('Cookies', 'Helen', 3, None, Decimal('1179')),
 ('Cookies', 'Helen', 4, Decimal('2180'), None),
 ('Cookies', 'Knuth', 1, None, Decimal('2978')),
 ('Cookies', 'Knuth', 2, Decimal('2363'), Decimal('3709')),
 ('Cookies', 'Knuth', 3, Decimal('2978'), Decimal('1669')),
 ('Cookies', 'Knuth', 4, Decimal('3709'), None),
 ('Cookies', 'Sam', 1, None, Decimal('408')),
 ('Cookies', 'Sam', 2, Decimal('2523'), None),
 ('Cookies', 'Sam', 3, None, None),
 ('Cookies', 'Sam', 4, None, None),
 ('Eggs', 'Bloom', 1, None, Decimal('3597')),
 ('Eggs', 'Bloom', 2, Decimal('2819'), Decimal('2185')),
 ('Eggs', 'Bloom', 3, Decimal('3597'), Decimal('1053')),
 ('Eggs', 'Bloom', 4, Decimal('2185'), None),
 ('Eggs', 'Emily', 1, None, Decimal('2715')),
 ('Eggs', 'Emily', 2, Decimal('4535'), Decimal('3231')),
 ('Eggs', 'Emily', 3, Decimal('2715'), Decimal('2039')),
 ('Eggs', 'Emily', 4, Decimal('3231'), None),
 ('Eggs', 'Helen', 1, None, Decimal('2327')),
 ('Eggs', 'Helen', 2, Decimal('813'), None),
 ('Eggs', 'Helen', 3, None, None),
 ('Eggs', 'Helen', 4, None, None),
 ('Eggs', 'Knuth', 1, None, Decimal('1239')),
 ('Eggs', 'Knuth', 2, Decimal('4051'), Decimal('3532')),
 ('Eggs', 'Knuth', 3, Decimal('1239'), Decimal('2254')),
 ('Eggs', 'Knuth', 4, Decimal('3532'), None),
 ('Eggs', 'Sam', 1, None, Decimal('2239')),
 ('Eggs', 'Sam', 2, Decimal('2482'), Decimal('1191')),
 ('Eggs', 'Sam', 3, Decimal('2239'), Decimal('4674')),
 ('Eggs', 'Sam', 4, Decimal('1191'), None),
 ('Fruits', 'Bloom', 1, None, Decimal('1933')),
 ('Fruits', 'Bloom', 2, Decimal('2243'), Decimal('2994')),
 ('Fruits', 'Bloom', 3, Decimal('1933'), Decimal('2926')),
 ('Fruits', 'Bloom', 4, Decimal('2994'), None),
 ('Fruits', 'Emily', 1, None, Decimal('2243')),
 ('Fruits', 'Emily', 2, Decimal('2919'), Decimal('2750')),
 ('Fruits', 'Emily', 3, Decimal('2243'), Decimal('2873')),
 ('Fruits', 'Emily', 4, Decimal('2750'), None),
 ('Fruits', 'Helen', 1, None, Decimal('2000')),
 ('Fruits', 'Helen', 2, Decimal('1570'), None),
 ('Fruits', 'Helen', 3, None, None),
 ('Fruits', 'Helen', 4, None, None),
 ('Fruits', 'Knuth', 1, None, Decimal('1857')),
 ('Fruits', 'Knuth', 2, Decimal('2758'), Decimal('1175')),
 ('Fruits', 'Knuth', 3, Decimal('1857'), Decimal('2279')),
 ('Fruits', 'Knuth', 4, Decimal('1175'), None),
 ('Fruits', 'Sam', 1, None, None),
 ('Fruits', 'Sam', 2, None, Decimal('3611')),
 ('Fruits', 'Sam', 3, Decimal('3743'), Decimal('3217')),
 ('Fruits', 'Sam', 4, Decimal('3611'), None),
 ('Milk', 'Bloom', 1, None, Decimal('2377')),
 ('Milk', 'Bloom', 2, Decimal('3215'), Decimal('1106')),
 ('Milk', 'Bloom', 3, Decimal('2377'), Decimal('3010')),
 ('Milk', 'Bloom', 4, Decimal('1106'), None),
 ('Milk', 'Emily', 1, None, Decimal('2581')),
 ('Milk', 'Emily', 2, Decimal('2589'), Decimal('1997')),
 ('Milk', 'Emily', 3, Decimal('2581'), Decimal('4986')),
 ('Milk', 'Emily', 4, Decimal('1997'), None),
 ('Milk', 'Helen', 1, None, Decimal('807')),
 ('Milk', 'Helen', 2, Decimal('3312'), Decimal('3314')),
 ('Milk', 'Helen', 3, Decimal('807'), Decimal('981')),
 ('Milk', 'Helen', 4, Decimal('3314'), None),
 ('Milk', 'Knuth', 1, None, Decimal('2424')),
 ('Milk', 'Knuth', 2, Decimal('92'), None),
 ('Milk', 'Knuth', 3, None, None),
 ('Milk', 'Knuth', 4, None, None),
 ('Milk', 'Sam', 1, None, Decimal('598')),
 ('Milk', 'Sam', 2, Decimal('1745'), Decimal('2125')),
 ('Milk', 'Sam', 3, Decimal('598'), Decimal('2431')),
 ('Milk', 'Sam', 4, Decimal('2125'), None),
 ('Pepsi', 'Bloom', 1, None, Decimal('1868')),
 ('Pepsi', 'Bloom', 2, Decimal('526'), Decimal('794')),
 ('Pepsi', 'Bloom', 3, Decimal('1868'), Decimal('4374')),
 ('Pepsi', 'Bloom', 4, Decimal('794'), None),
 ('Pepsi', 'Emily', 1, None, Decimal('2374')),
 ('Pepsi', 'Emily', 2, Decimal('3842'), None),
 ('Pepsi', 'Emily', 3, None, None),
 ('Pepsi', 'Emily', 4, None, None),
 ('Pepsi', 'Helen', 1, None, Decimal('2397')),
 ('Pepsi', 'Helen', 2, Decimal('3130'), Decimal('2768')),
 ('Pepsi', 'Helen', 3, Decimal('2397'), Decimal('2435')),
 ('Pepsi', 'Helen', 4, Decimal('2768'), None),
 ('Pepsi', 'Knuth', 1, None, Decimal('2468')),
 ('Pepsi', 'Knuth', 2, Decimal('3214'), Decimal('2982')),
 ('Pepsi', 'Knuth', 3, Decimal('2468'), Decimal('1596')),
 ('Pepsi', 'Knuth', 4, Decimal('2982'), None),
 ('Pepsi', 'Sam', 1, None, Decimal('2332')),
 ('Pepsi', 'Sam', 2, Decimal('2442'), Decimal('3954')),
 ('Pepsi', 'Sam', 3, Decimal('2332'), Decimal('3166')),
 ('Pepsi', 'Sam', 4, Decimal('3954'), None),
 ('Soap', 'Bloom', 1, None, Decimal('2310')),
 ('Soap', 'Bloom', 2, Decimal('4623'), Decimal('329')),
 ('Soap', 'Bloom', 3, Decimal('2310'), Decimal('4364')),
 ('Soap', 'Bloom', 4, Decimal('329'), None),
 ('Soap', 'Emily', 1, None, Decimal('2549')),
 ('Soap', 'Emily', 2, Decimal('3218'), Decimal('1531')),
 ('Soap', 'Emily', 3, Decimal('2549'), Decimal('2976')),
 ('Soap', 'Emily', 4, Decimal('1531'), None),
 ('Soap', 'Helen', 1, None, None),
 ('Soap', 'Helen', 2, None, None),
 ('Soap', 'Helen', 3, None, Decimal('1209')),
 ('Soap', 'Helen', 4, Decimal('2990'), None),
 ('Soap', 'Knuth', 1, None, Decimal('1519')),
 ('Soap', 'Knuth', 2, Decimal('878'), Decimal('1002')),
 ('Soap', 'Knuth', 3, Decimal('1519'), Decimal('2620')),
 ('Soap', 'Knuth', 4, Decimal('1002'), None),
 ('Soap', 'Sam', 1, None, Decimal('2878')),
 ('Soap', 'Sam', 2, Decimal('1994'), Decimal('3108')),
 ('Soap', 'Sam', 3, Decimal('2878'), Decimal('694')),
 ('Soap', 'Sam', 4, Decimal('3108'), None),
 ('Yogurt', 'Bloom', 1, None, Decimal('2623')),
 ('Yogurt', 'Bloom', 2, Decimal('1660'), Decimal('2398')),
 ('Yogurt', 'Bloom', 3, Decimal('2623'), Decimal('1786')),
 ('Yogurt', 'Bloom', 4, Decimal('2398'), None),
 ('Yogurt', 'Emily', 1, None, Decimal('2650')),
 ('Yogurt', 'Emily', 2, Decimal('3079'), Decimal('2161')),
 ('Yogurt', 'Emily', 3, Decimal('2650'), Decimal('730')),
 ('Yogurt', 'Emily', 4, Decimal('2161'), None),
 ('Yogurt', 'Helen', 1, None, Decimal('3174')),
 ('Yogurt', 'Helen', 2, Decimal('2332'), Decimal('2904')),
 ('Yogurt', 'Helen', 3, Decimal('3174'), Decimal('2247')),
 ('Yogurt', 'Helen', 4, Decimal('2904'), None),
 ('Yogurt', 'Knuth', 1, None, Decimal('1787')),
 ('Yogurt', 'Knuth', 2, Decimal('3903'), Decimal('3705')),
 ('Yogurt', 'Knuth', 3, Decimal('1787'), Decimal('2497')),
 ('Yogurt', 'Knuth', 4, Decimal('3705'), None),
 ('Yogurt', 'Sam', 1, None, Decimal('2735')),
 ('Yogurt', 'Sam', 2, Decimal('2126'), Decimal('2000')),
 ('Yogurt', 'Sam', 3, Decimal('2735'), None),
 ('Yogurt', 'Sam', 4, None, None)]

 * postgresql://postgres:***@127.0.0.1/salesdb
335 rows affected.

[('Bloom', 'Bread', 1, 222),
 ('Bloom', 'Bread', 2, 222),
 ('Bloom', 'Bread', 3, 222),
 ('Bloom', 'Bread', 4, 222),
 ('Bloom', 'Bread', 6, 222),
 ('Bloom', 'Bread', 7, 222),
 ('Bloom', 'Bread', 8, 222),
 ('Bloom', 'Bread', 9, 222),
 ('Bloom', 'Bread', 12, 222),
 ('Bloom', 'Butter', 8, 222),
 ('Bloom', 'Butter', 9, 222),
 ('Bloom', 'Butter', 10, 222),
 ('Bloom', 'Coke', 1, 222),
 ('Bloom', 'Coke', 2, 222),
 ('Bloom', 'Coke', 4, 222),
 ('Bloom', 'Coke', 7, 222),
 ('Bloom', 'Coke', 8, 222),
 ('Bloom', 'Coke', 9, 222),
 ('Bloom', 'Coke', 10, 222),
 ('Bloom', 'Cookies', 6, 222),
 ('Bloom', 'Cookies', 7, 222),
 ('Bloom', 'Cookies', 9, 222),
 ('Bloom', 'Cookies', 10, 222),
 ('Bloom', 'Cookies', 11, 222),
 ('Bloom', 'Eggs', 1, 222),
 ('Bloom', 'Eggs', 4, 222),
 ('Bloom', 'Eggs', 5, 222),
 ('Bloom', 'Eggs', 7, 222),
 ('Bloom', 'Eggs', 9, 222),
 ('Bloom', 'Eggs', 11, 222),
 ('Bloom', 'Fruits', 1, 222),
 ('Bloom', 'Fruits', 2, 222),
 ('Bloom', 'Fruits', 3, 222),
 ('Bloom', 'Fruits', 4, 222),
 ('Bloom', 'Fruits', 5, 222),
 ('Bloom', 'Fruits', 6, 222),
 ('Bloom', 'Fruits', 7, 222),
 ('Bloom', 'Fruits', 8, 222),
 ('Bloom', 'Fruits', 11, 222),
 ('Bloom', 'Milk', 1, 222),
 ('Bloom', 'Milk', 3, 222),
 ('Bloom', 'Milk', 4, 222),
 ('Bloom', 'Milk', 5, 222),
 ('Bloom', 'Milk', 9, 222),
 ('Bloom', 'Milk', 10, 222),
 ('Bloom', 'Milk', 12, 222),
 ('Bloom', 'Pepsi', 1, 222),
 ('Bloom', 'Pepsi', 5, 222),
 ('Bloom', 'Pepsi', 6, 222),
 ('Bloom', 'Pepsi', 7, 222),
 ('Bloom', 'Pepsi', 8, 222),
 ('Bloom', 'Pepsi', 9, 222),
 ('Bloom', 'Pepsi', 11, 222),
 ('Bloom', 'Pepsi', 12, 222),
 ('Bloom', 'Soap', 1, 222),
 ('Bloom', 'Soap', 4, 222),
 ('Bloom', 'Soap', 6, 222),
 ('Bloom', 'Soap', 7, 222),
 ('Bloom', 'Soap', 9, 222),
 ('Bloom', 'Soap', 11, 222),
 ('Bloom', 'Yogurt', 3, 222),
 ('Bloom', 'Yogurt', 4, 222),
 ('Bloom', 'Yogurt', 7, 222),
 ('Bloom', 'Yogurt', 9, 222),
 ('Bloom', 'Yogurt', 10, 222),
 ('Bloom', 'Yogurt', 12, 222),
 ('Emily', 'Bread', 3, 222),
 ('Emily', 'Bread', 4, 222),
 ('Emily', 'Bread', 5, 222),
 ('Emily', 'Bread', 6, 222),
 ('Emily', 'Bread', 9, 222),
 ('Emily', 'Bread', 11, 222),
 ('Emily', 'Bread', 12, 222),
 ('Emily', 'Butter', 2, 222),
 ('Emily', 'Butter', 6, 222),
 ('Emily', 'Butter', 7, 222),
 ('Emily', 'Butter', 8, 222),
 ('Emily', 'Butter', 11, 222),
 ('Emily', 'Coke', 1, 222),
 ('Emily', 'Coke', 2, 222),
 ('Emily', 'Coke', 6, 222),
 ('Emily', 'Coke', 8, 222),
 ('Emily', 'Coke', 11, 222),
 ('Emily', 'Cookies', 1, 222),
 ('Emily', 'Cookies', 2, 222),
 ('Emily', 'Cookies', 4, 222),
 ('Emily', 'Cookies', 5, 222),
 ('Emily', 'Cookies', 6, 222),
 ('Emily', 'Cookies', 7, 222),
 ('Emily', 'Cookies', 10, 222),
 ('Emily', 'Cookies', 11, 222),
 ('Emily', 'Cookies', 12, 222),
 ('Emily', 'Eggs', 1, 222),
 ('Emily', 'Eggs', 4, 222),
 ('Emily', 'Eggs', 7, 222),
 ('Emily', 'Eggs', 8, 222),
 ('Emily', 'Eggs', 9, 222),
 ('Emily', 'Eggs', 10, 222),
 ('Emily', 'Eggs', 11, 222),
 ('Emily', 'Eggs', 12, 222),
 ('Emily', 'Fruits', 1, 222),
 ('Emily', 'Fruits', 3, 222),
 ('Emily', 'Fruits', 4, 222),
 ('Emily', 'Fruits', 7, 222),
 ('Emily', 'Fruits', 8, 222),
 ('Emily', 'Fruits', 10, 222),
 ('Emily', 'Fruits', 11, 222),
 ('Emily', 'Fruits', 12, 222),
 ('Emily', 'Milk', 3, 222),
 ('Emily', 'Milk', 4, 222),
 ('Emily', 'Milk', 6, 222),
 ('Emily', 'Milk', 7, 222),
 ('Emily', 'Milk', 9, 222),
 ('Emily', 'Milk', 11, 222),
 ('Emily', 'Pepsi', 1, 222),
 ('Emily', 'Pepsi', 3, 222),
 ('Emily', 'Pepsi', 5, 222),
 ('Emily', 'Pepsi', 6, 222),
 ('Emily', 'Pepsi', 10, 222),
 ('Emily', 'Soap', 1, 222),
 ('Emily', 'Soap', 4, 222),
 ('Emily', 'Soap', 7, 222),
 ('Emily', 'Soap', 8, 222),
 ('Emily', 'Soap', 9, 222),
 ('Emily', 'Soap', 10, 222),
 ('Emily', 'Soap', 11, 222),
 ('Emily', 'Yogurt', 3, 222),
 ('Emily', 'Yogurt', 5, 222),
 ('Emily', 'Yogurt', 6, 222),
 ('Emily', 'Yogurt', 8, 222),
 ('Emily', 'Yogurt', 10, 222),
 ('Helen', 'Bread', 1, 222),
 ('Helen', 'Bread', 5, 222),
 ('Helen', 'Bread', 6, 222),
 ('Helen', 'Bread', 10, 222),
 ('Helen', 'Bread', 11, 222),
 ('Helen', 'Bread', 12, 222),
 ('Helen', 'Butter', 1, 222),
 ('Helen', 'Butter', 2, 222),
 ('Helen', 'Butter', 3, 222),
 ('Helen', 'Butter', 4, 222),
 ('Helen', 'Butter', 6, 222),
 ('Helen', 'Butter', 7, 222),
 ('Helen', 'Butter', 8, 222),
 ('Helen', 'Butter', 9, 222),
 ('Helen', 'Butter', 11, 222),
 ('Helen', 'Coke', 2, 222),
 ('Helen', 'Coke', 4, 222),
 ('Helen', 'Coke', 5, 222),
 ('Helen', 'Coke', 7, 222),
 ('Helen', 'Coke', 10, 222),
 ('Helen', 'Coke', 12, 222),
 ('Helen', 'Cookies', 7, 222),
 ('Helen', 'Cookies', 8, 222),
 ('Helen', 'Cookies', 11, 222),
 ('Helen', 'Cookies', 12, 222),
 ('Helen', 'Eggs', 2, 222),
 ('Helen', 'Eggs', 4, 222),
 ('Helen', 'Eggs', 5, 222),
 ('Helen', 'Eggs', 6, 222),
 ('Helen', 'Eggs', 10, 222),
 ('Helen', 'Fruits', 1, 222),
 ('Helen', 'Fruits', 2, 222),
 ('Helen', 'Fruits', 3, 222),
 ('Helen', 'Fruits', 5, 222),
 ('Helen', 'Fruits', 6, 222),
 ('Helen', 'Fruits', 12, 222),
 ('Helen', 'Milk', 1, 222),
 ('Helen', 'Milk', 2, 222),
 ('Helen', 'Milk', 3, 222),
 ('Helen', 'Milk', 4, 222),
 ('Helen', 'Milk', 5, 222),
 ('Helen', 'Milk', 9, 222),
 ('Helen', 'Milk', 11, 222),
 ('Helen', 'Milk', 12, 222),
 ('Helen', 'Pepsi', 1, 222),
 ('Helen', 'Pepsi', 2, 222),
 ('Helen', 'Pepsi', 3, 222),
 ('Helen', 'Pepsi', 4, 222),
 ('Helen', 'Pepsi', 5, 222),
 ('Helen', 'Pepsi', 6, 222),
 ('Helen', 'Pepsi', 9, 222),
 ('Helen', 'Pepsi', 10, 222),
 ('Helen', 'Pepsi', 12, 222),
 ('Helen', 'Soap', 1, 222),
 ('Helen', 'Soap', 3, 222),
 ('Helen', 'Soap', 7, 222),
 ('Helen', 'Soap', 8, 222),
 ('Helen', 'Soap', 9, 222),
 ('Helen', 'Soap', 10, 222),
 ('Helen', 'Soap', 11, 222),
 ('Helen', 'Yogurt', 1, 222),
 ('Helen', 'Yogurt', 2, 222),
 ('Helen', 'Yogurt', 4, 222),
 ('Helen', 'Yogurt', 6, 222),
 ('Helen', 'Yogurt', 8, 222),
 ('Helen', 'Yogurt', 9, 222),
 ('Helen', 'Yogurt', 10, 222),
 ('Helen', 'Yogurt', 12, 222),
 ('Knuth', 'Bread', 1, 222),
 ('Knuth', 'Bread', 2, 222),
 ('Knuth', 'Bread', 3, 222),
 ('Knuth', 'Bread', 4, 222),
 ('Knuth', 'Bread', 5, 222),
 ('Knuth', 'Bread', 6, 222),
 ('Knuth', 'Bread', 8, 222),
 ('Knuth', 'Bread', 10, 222),
 ('Knuth', 'Bread', 11, 222),
 ('Knuth', 'Butter', 3, 222),
 ('Knuth', 'Butter', 4, 222),
 ('Knuth', 'Butter', 6, 222),
 ('Knuth', 'Butter', 10, 222),
 ('Knuth', 'Coke', 1, 222),
 ('Knuth', 'Coke', 2, 222),
 ('Knuth', 'Coke', 4, 222),
 ('Knuth', 'Coke', 5, 222),
 ('Knuth', 'Coke', 6, 222),
 ('Knuth', 'Coke', 7, 222),
 ('Knuth', 'Coke', 8, 222),
 ('Knuth', 'Coke', 10, 222),
 ('Knuth', 'Coke', 12, 222),
 ('Knuth', 'Cookies', 2, 222),
 ('Knuth', 'Cookies', 3, 222),
 ('Knuth', 'Cookies', 6, 222),
 ('Knuth', 'Cookies', 7, 222),
 ('Knuth', 'Cookies', 10, 222),
 ('Knuth', 'Cookies', 12, 222),
 ('Knuth', 'Eggs', 2, 222),
 ('Knuth', 'Eggs', 4, 222),
 ('Knuth', 'Eggs', 9, 222),
 ('Knuth', 'Eggs', 10, 222),
 ('Knuth', 'Eggs', 11, 222),
 ('Knuth', 'Eggs', 12, 222),
 ('Knuth', 'Fruits', 1, 222),
 ('Knuth', 'Fruits', 2, 222),
 ('Knuth', 'Fruits', 4, 222),
 ('Knuth', 'Fruits', 7, 222),
 ('Knuth', 'Fruits', 8, 222),
 ('Knuth', 'Fruits', 9, 222),
 ('Knuth', 'Fruits', 10, 222),
 ('Knuth', 'Fruits', 11, 222),
 ('Knuth', 'Fruits', 12, 222),
 ('Knuth', 'Milk', 2, 222),
 ('Knuth', 'Milk', 3, 222),
 ('Knuth', 'Milk', 4, 222),
 ('Knuth', 'Milk', 10, 222),
 ('Knuth', 'Pepsi', 2, 222),
 ('Knuth', 'Pepsi', 3, 222),
 ('Knuth', 'Pepsi', 4, 222),
 ('Knuth', 'Pepsi', 6, 222),
 ('Knuth', 'Pepsi', 7, 222),
 ('Knuth', 'Pepsi', 8, 222),
 ('Knuth', 'Pepsi', 9, 222),
 ('Knuth', 'Pepsi', 12, 222),
 ('Knuth', 'Soap', 1, 222),
 ('Knuth', 'Soap', 2, 222),
 ('Knuth', 'Soap', 4, 222),
 ('Knuth', 'Soap', 5, 222),
 ('Knuth', 'Soap', 8, 222),
 ('Knuth', 'Soap', 10, 222),
 ('Knuth', 'Soap', 11, 222),
 ('Knuth', 'Soap', 12, 222),
 ('Knuth', 'Yogurt', 2, 222),
 ('Knuth', 'Yogurt', 3, 222),
 ('Knuth', 'Yogurt', 4, 222),
 ('Knuth', 'Yogurt', 5, 222),
 ('Knuth', 'Yogurt', 6, 222),
 ('Knuth', 'Yogurt', 9, 222),
 ('Knuth', 'Yogurt', 10, 222),
 ('Sam', 'Bread', 1, 222),
 ('Sam', 'Bread', 4, 222),
 ('Sam', 'Bread', 6, 222),
 ('Sam', 'Bread', 7, 222),
 ('Sam', 'Bread', 8, 222),
 ('Sam', 'Bread', 9, 222),
 ('Sam', 'Bread', 11, 222),
 ('Sam', 'Butter', 2, 222),
 ('Sam', 'Butter', 4, 222),
 ('Sam', 'Butter', 6, 222),
 ('Sam', 'Butter', 9, 222),
 ('Sam', 'Butter', 10, 222),
 ('Sam', 'Butter', 12, 222),
 ('Sam', 'Coke', 1, 222),
 ('Sam', 'Coke', 5, 222),
 ('Sam', 'Coke', 6, 222),
 ('Sam', 'Coke', 8, 222),
 ('Sam', 'Cookies', 2, 222),
 ('Sam', 'Cookies', 5, 222),
 ('Sam', 'Cookies', 6, 222),
 ('Sam', 'Cookies', 10, 222),
 ('Sam', 'Cookies', 11, 222),
 ('Sam', 'Cookies', 12, 222),
 ('Sam', 'Eggs', 1, 222),
 ('Sam', 'Eggs', 2, 222),
 ('Sam', 'Eggs', 3, 222),
 ('Sam', 'Eggs', 5, 222),
 ('Sam', 'Eggs', 7, 222),
 ('Sam', 'Eggs', 9, 222),
 ('Sam', 'Eggs', 11, 222),
 ('Sam', 'Fruits', 5, 222),
 ('Sam', 'Fruits', 7, 222),
 ('Sam', 'Fruits', 9, 222),
 ('Sam', 'Fruits', 10, 222),
 ('Sam', 'Fruits', 11, 222),
 ('Sam', 'Fruits', 12, 222),
 ('Sam', 'Milk', 1, 222),
 ('Sam', 'Milk', 2, 222),
 ('Sam', 'Milk', 4, 222),
 ('Sam', 'Milk', 7, 222),
 ('Sam', 'Milk', 8, 222),
 ('Sam', 'Milk', 11, 222),
 ('Sam', 'Milk', 12, 222),
 ('Sam', 'Pepsi', 3, 222),
 ('Sam', 'Pepsi', 4, 222),
 ('Sam', 'Pepsi', 5, 222),
 ('Sam', 'Pepsi', 6, 222),
 ('Sam', 'Pepsi', 7, 222),
 ('Sam', 'Pepsi', 9, 222),
 ('Sam', 'Pepsi', 10, 222),
 ('Sam', 'Pepsi', 11, 222),
 ('Sam', 'Pepsi', 12, 222),
 ('Sam', 'Soap', 1, 222),
 ('Sam', 'Soap', 2, 222),
 ('Sam', 'Soap', 3, 222),
 ('Sam', 'Soap', 4, 222),
 ('Sam', 'Soap', 6, 222),
 ('Sam', 'Soap', 8, 222),
 ('Sam', 'Soap', 9, 222),
 ('Sam', 'Soap', 11, 222),
 ('Sam', 'Yogurt', 1, 222),
 ('Sam', 'Yogurt', 3, 222),
 ('Sam', 'Yogurt', 5, 222),
 ('Sam', 'Yogurt', 6, 222),
 ('Sam', 'Yogurt', 7, 222),
 ('Sam', 'Yogurt', 9, 222)]

In [85]:
%%sql
With t1 AS (
SELECT cust, prod, state, round(avg(quant)) AS CUST_AVG
FROM sales
GROUP BY 1,2,3),

t2 AS (
SELECT s1.cust, s1.prod, s1.state, round(avg(s2.quant)) AS OTHER_STATE_AVG
FROM sales s1, sales s2
WHERE s1.cust = s2.cust AND s1.prod = s2.prod AND s1.state != s2.state
GROUP BY 1,2,3),

t3 AS (
SELECT s1.cust, s1.prod, s1.state, round(avg(s2.quant)) AS OTHER_PROD_AVG
FROM sales s1, sales s2
WHERE s1.cust = s2.cust AND s1.prod != s2.prod AND s1.state = s2.state
GROUP BY 1,2,3)

SELECT *
FROM t1
NATURAL INNER JOIN t2
NATURAL INNER JOIN t3
order by cust,prod

 * postgresql://postgres:***@127.0.0.1/salesdb
187 rows affected.

[('Bloom', 'Bread', 'CT', Decimal('1530'), Decimal('2528'), Decimal('2782')),
 ('Bloom', 'Bread', 'NY', Decimal('3792'), Decimal('1959'), Decimal('2546')),
 ('Bloom', 'Bread', 'PA', Decimal('3100'), Decimal('2022'), Decimal('2146')),
 ('Bloom', 'Bread', 'NJ', Decimal('2161'), Decimal('2077'), Decimal('2567')),
 ('Bloom', 'Butter', 'NY', Decimal('1054'), Decimal('3999'), Decimal('2707')),
 ('Bloom', 'Butter', 'NJ', Decimal('3718'), Decimal('2667'), Decimal('2453')),
 ('Bloom', 'Butter', 'CT', Decimal('4279'), Decimal('2386'), Decimal('2472')),
 ('Bloom', 'Coke', 'PA', Decimal('3067'), Decimal('1975'), Decimal('2056')),
 ('Bloom', 'Coke', 'NY', Decimal('1229'), Decimal('2478'), Decimal('2697')),
 ('Bloom', 'Coke', 'CT', Decimal('2284'), Decimal('2355'), Decimal('2563')),
 ('Bloom', 'Coke', 'NJ', Decimal('2017'), Decimal('2500'), Decimal('2552')),
 ('Bloom', 'Cookies', 'NJ', Decimal('4064'), Decimal('2785'), Decimal('2381')),
 ('Bloom', 'Cookies', 'PA', Decimal('2181'), Decimal('3323'), Decimal('2189')),
 ('Bloom', 'Cookies', 'CT', Decimal('2641'), Decimal('3412'), Decimal('2523')),
 ('Bloom', 'Cookies', 'NY', Decimal('4570'), Decimal('2882'), Decimal('2501')),
 ('Bloom', 'Eggs', 'NJ', Decimal('2766'), Decimal('2447'), Decimal('2477')),
 ('Bloom', 'Eggs', 'PA', Decimal('3723'), Decimal('2383'), Decimal('2118')),
 ('Bloom', 'Eggs', 'NY', Decimal('2164'), Decimal('2700'), Decimal('2745')),
 ('Bloom', 'Eggs', 'CT', Decimal('2411'), Decimal('2559'), Decimal('2565')),
 ('Bloom', 'Fruits', 'PA', Decimal('2151'), Decimal('2695'), Decimal('2204')),
 ('Bloom', 'Fruits', 'NY', Decimal('2333'), Decimal('2514'), Decimal('2696')),
 ('Bloom', 'Fruits', 'NJ', Decimal('2234'), Decimal('2522'), Decimal('2527')),
 ('Bloom', 'Fruits', 'CT', Decimal('3639'), Decimal('2221'), Decimal('2398')),
 ('Bloom', 'Milk', 'NY', Decimal('3306'), Decimal('2602'), Decimal('2477')),
 ('Bloom', 'Milk', 'PA', Decimal('2383'), Decimal('2879'), Decimal('2159')),
 ('Bloom', 'Milk', 'CT', Decimal('3117'), Decimal('2659'), Decimal('2466')),
 ('Bloom', 'Milk', 'NJ', Decimal('2380'), Decimal('2936'), Decimal('2516')),
 ('Bloom', 'Pepsi', 'CT', Decimal('94'), Decimal('2185'), Decimal('2639')),
 ('Bloom', 'Pepsi', 'PA', Decimal('2034'), Decimal('1908'), Decimal('2195')),
 ('Bloom', 'Pepsi', 'NJ', Decimal('2194'), Decimal('1654'), Decimal('2546')),
 ('Bloom', 'Pepsi', 'NY', Decimal('2243'), Decimal('1817'), Decimal('2662')),
 ('Bloom', 'Soap', 'NJ', Decimal('4364'), Decimal('1980'), Decimal('2430')),
 ('Bloom', 'Soap', 'CT', Decimal('2505'), Decimal('2314'), Decimal('2545')),
 ('Bloom', 'Soap', 'PA', Decimal('1630'), Decimal('3125'), Decimal('2272')),
 ('Bloom', 'Yogurt', 'CT', Decimal('4004'), Decimal('1952'), Decimal('2483')),
 ('Bloom', 'Yogurt', 'NY', Decimal('4043'), Decimal('1947'), Decimal('2532')),
 ('Bloom', 'Yogurt', 'NJ', Decimal('2206'), Decimal('2212'), Decimal('2544')),
 ('Bloom', 'Yogurt', 'PA', Decimal('400'), Decimal('2812'), Decimal('2358')),
 ('Emily', 'Bread', 'CT', Decimal('1626'), Decimal('1524'), Decimal('2688')),
 ('Emily', 'Bread', 'PA', Decimal('1393'), Decimal('1595'), Decimal('2254')),
 ('Emily', 'Bread', 'NJ', Decimal('1744'), Decimal('1395'), Decimal('2804')),
 ('Emily', 'Bread', 'NY', Decimal('1282'), Decimal('1598'), Decimal('2717')),
 ('Emily', 'Butter', 'CT', Decimal('1844'), Decimal('2695'), Decimal('2799')),
 ('Emily', 'Butter', 'NY', Decimal('2826'), Decimal('2253'), Decimal('2587')),
 ('Emily', 'Butter', 'NJ', Decimal('2576'), Decimal('2243'), Decimal('2647')),
 ('Emily', 'Butter', 'PA', Decimal('2750'), Decimal('2193'), Decimal('2092')),
 ('Emily', 'Coke', 'NJ', Decimal('2269'), Decimal('2479'), Decimal('2690')),
 ('Emily', 'Coke', 'CT', Decimal('2456'), Decimal('2385'), Decimal('2672')),
 ('Emily', 'Coke', 'NY', Decimal('2502'), Decimal('2363'), Decimal('2611')),
 ('Emily', 'Cookies', 'NY', Decimal('2464'), Decimal('2743'), Decimal('2624')),
 ('Emily', 'Cookies', 'PA', Decimal('3038'), Decimal('2551'), Decimal('1968')),
 ('Emily', 'Cookies', 'NJ', Decimal('1775'), Decimal('3081'), Decimal('2847')),
 ('Emily', 'Cookies', 'CT', Decimal('3962'), Decimal('2375'), Decimal('2466')),
 ('Emily', 'Eggs', 'PA', Decimal('1654'), Decimal('3308'), Decimal('2245')),
 ('Emily', 'Eggs', 'NY', Decimal('2787'), Decimal('2747'), Decimal('2570')),
 ('Emily', 'Eggs', 'CT', Decimal('2722'), Decimal('2760'), Decimal('2643')),
 ('Emily', 'Eggs', 'NJ', Decimal('3845'), Decimal('2213'), Decimal('2422')),
 ('Emily', 'Fruits', 'PA', Decimal('2340'), Decimal('3003'), Decimal('2082')),
 ('Emily', 'Fruits', 'CT', Decimal('3055'), Decimal('2667'), Decimal('2629')),
 ('Emily', 'Fruits', 'NY', Decimal('2463'), Decimal('2801'), Decimal('2624')),
 ('Emily', 'Fruits', 'NJ', Decimal('4056'), Decimal('2450'), Decimal('2523')),
 ('Emily', 'Milk', 'NY', Decimal('4986'), Decimal('2332'), Decimal('2493')),
 ('Emily', 'Milk', 'CT', Decimal('1957'), Decimal('3087'), Decimal('2740')),
 ('Emily', 'Milk', 'NJ', Decimal('3839'), Decimal('2495'), Decimal('2593')),
 ('Emily', 'Milk', 'PA', Decimal('2203'), Decimal('2939'), Decimal('2139')),
 ('Emily', 'Pepsi', 'CT', Decimal('4357'), Decimal('2428'), Decimal('2413')),
 ('Emily', 'Pepsi', 'NY', Decimal('2720'), Decimal('3469'), Decimal('2586')),
 ('Emily', 'Pepsi', 'PA', Decimal('1682'), Decimal('3517'), Decimal('2167')),
 ('Emily', 'Pepsi', 'NJ', Decimal('2591'), Decimal('3365'), Decimal('2643')),
 ('Emily', 'Soap', 'NJ', Decimal('2868'), Decimal('2137'), Decimal('2612')),
 ('Emily', 'Soap', 'CT', Decimal('2242'), Decimal('2513'), Decimal('2701')),
 ('Emily', 'Soap', 'NY', Decimal('3218'), Decimal('2296'), Decimal('2570')),
 ('Emily', 'Soap', 'PA', Decimal('742'), Decimal('2650'), Decimal('2208')),
 ('Emily', 'Yogurt', 'NJ', Decimal('2336'), Decimal('2362'), Decimal('2653')),
 ('Emily', 'Yogurt', 'NY', Decimal('2575'), Decimal('2196'), Decimal('2600')),
 ('Emily', 'Yogurt', 'CT', Decimal('2149'), Decimal('2516'), Decimal('2714')),
 ('Helen', 'Bread', 'CT', Decimal('3017'), Decimal('2664'), Decimal('2209')),
 ('Helen', 'Bread', 'NJ', Decimal('2100'), Decimal('2976'), Decimal('2375')),
 ('Helen', 'Bread', 'PA', Decimal('1637'), Decimal('2924'), Decimal('2200')),
 ('Helen', 'Bread', 'NY', Decimal('3382'), Decimal('2481'), Decimal('2236')),
 ('Helen', 'Butter', 'NJ', Decimal('1708'), Decimal('2047'), Decimal('2635')),
 ('Helen', 'Butter', 'CT', Decimal('306'), Decimal('1985'), Decimal('2340')),
 ('Helen', 'Butter', 'PA', Decimal('1503'), Decimal('2028'), Decimal('2408')),
 ('Helen', 'Butter', 'NY', Decimal('2685'), Decimal('1546'), Decimal('2249')),
 ('Helen', 'Coke', 'NY', Decimal('1535'), Decimal('2784'), Decimal('2415')),
 ('Helen', 'Coke', 'PA', Decimal('3132'), Decimal('2581'), Decimal('2117')),
 ('Helen', 'Coke', 'NJ', Decimal('2905'), Decimal('2474'), Decimal('2247')),
 ('Helen', 'Coke', 'CT', Decimal('2648'), Decimal('2591'), Decimal('2184')),
 ('Helen', 'Cookies', 'NJ', Decimal('1965'), Decimal('1733'), Decimal('2370')),
 ('Helen', 'Cookies', 'CT', Decimal('1179'), Decimal('2180'), Decimal('2349')),
 ('Helen', 'Cookies', 'NY', Decimal('2287'), Decimal('1441'), Decimal('2359')),
 ('Helen', 'Eggs', 'NY', Decimal('3200'), Decimal('1983'), Decimal('2324')),
 ('Helen', 'Eggs', 'CT', Decimal('2302'), Decimal('1969'), Decimal('2277')),
 ('Helen', 'Eggs', 'PA', Decimal('1558'), Decimal('2481'), Decimal('2285')),
 ('Helen', 'Fruits', 'CT', Decimal('1760'), Decimal('2000'), Decimal('2391')),
 ('Helen', 'Fruits', 'PA', Decimal('2811'), Decimal('1719'), Decimal('2134')),
 ('Helen', 'Fruits', 'NY', Decimal('2774'), Decimal('1723'), Decimal('2339')),
 ('Helen', 'Fruits', 'NJ', Decimal('415'), Decimal('2018'), Decimal('2424')),
 ('Helen', 'Milk', 'NJ', Decimal('1839'), Decimal('2127'), Decimal('2375')),
 ('Helen', 'Milk', 'NY', Decimal('1589'), Decimal('2470'), Decimal('2513')),
 ('Helen', 'Milk', 'CT', Decimal('1963'), Decimal('2150'), Decimal('2311')),
 ('Helen', 'Milk', 'PA', Decimal('3188'), Decimal('1742'), Decimal('1979')),
 ('Helen', 'Pepsi', 'PA', Decimal('1432'), Decimal('2886'), Decimal('2257')),
 ('Helen', 'Pepsi', 'NJ', Decimal('3267'), Decimal('2285'), Decimal('2175')),
 ('Helen', 'Pepsi', 'CT', Decimal('2631'), Decimal('2672'), Decimal('2246')),
 ('Helen', 'Pepsi', 'NY', Decimal('2508'), Decimal('2709'), Decimal('2336')),
 ('Helen', 'Soap', 'CT', Decimal('1752'), Decimal('2713'), Decimal('2313')),
 ('Helen', 'Soap', 'NJ', Decimal('2791'), Decimal('2134'), Decimal('2270')),
 ('Helen', 'Soap', 'PA', Decimal('2516'), Decimal('2494'), Decimal('2129')),
 ('Helen', 'Yogurt', 'NJ', Decimal('2096'), Decimal('2717'), Decimal('2366')),
 ('Helen', 'Yogurt', 'CT', Decimal('3404'), Decimal('2334'), Decimal('2171')),
 ('Helen', 'Yogurt', 'PA', Decimal('4001'), Decimal('2505'), Decimal('2068')),
 ('Helen', 'Yogurt', 'NY', Decimal('2048'), Decimal('3262'), Decimal('2418')),
 ('Knuth', 'Bread', 'CT', Decimal('2561'), Decimal('2866'), Decimal('1950')),
 ('Knuth', 'Bread', 'NY', Decimal('3370'), Decimal('2654'), Decimal('2459')),
 ('Knuth', 'Bread', 'PA', Decimal('3203'), Decimal('2469'), Decimal('2331')),
 ('Knuth', 'Bread', 'NJ', Decimal('1013'), Decimal('2868'), Decimal('2325')),
 ('Knuth', 'Butter', 'CT', Decimal('2232'), Decimal('1063'), Decimal('2059')),
 ('Knuth', 'Butter', 'NY', Decimal('648'), Decimal('1867'), Decimal('2812')),
 ('Knuth', 'Butter', 'PA', Decimal('1684'), Decimal('1044'), Decimal('2508')),
 ('Knuth', 'Coke', 'CT', Decimal('2114'), Decimal('2999'), Decimal('2057')),
 ('Knuth', 'Coke', 'PA', Decimal('3605'), Decimal('2178'), Decimal('2211')),
 ('Knuth', 'Coke', 'NY', Decimal('1946'), Decimal('2792'), Decimal('2531')),
 ('Knuth', 'Coke', 'NJ', Decimal('2340'), Decimal('2843'), Decimal('2240')),
 ('Knuth', 'Cookies', 'PA', Decimal('928'), Decimal('3028'), Decimal('2564')),
 ('Knuth', 'Cookies', 'NJ', Decimal('3172'), Decimal('2232'), Decimal('2011')),
 ('Knuth', 'Cookies', 'CT', Decimal('3351'), Decimal('2290'), Decimal('1931')),
 ('Knuth', 'Cookies', 'NY', Decimal('1485'), Decimal('2733'), Decimal('2554')),
 ('Knuth', 'Eggs', 'NJ', Decimal('1846'), Decimal('2711'), Decimal('2304')),
 ('Knuth', 'Eggs', 'NY', Decimal('4051'), Decimal('2160'), Decimal('2340')),
 ('Knuth', 'Eggs', 'PA', Decimal('1929'), Decimal('2690'), Decimal('2490')),
 ('Knuth', 'Eggs', 'CT', Decimal('2433'), Decimal('2609'), Decimal('2012')),
 ('Knuth', 'Fruits', 'CT', Decimal('1629'), Decimal('1908'), Decimal('2109')),
 ('Knuth', 'Fruits', 'NY', Decimal('1252'), Decimal('2086'), Decimal('2797')),
 ('Knuth', 'Fruits', 'PA', Decimal('2484'), Decimal('1594'), Decimal('2446')),
 ('Knuth', 'Fruits', 'NJ', Decimal('2013'), Decimal('1803'), Decimal('2301')),
 ('Knuth', 'Milk', 'NY', Decimal('2424'), Decimal('424'), Decimal('2507')),
 ('Knuth', 'Milk', 'PA', Decimal('607'), Decimal('1241'), Decimal('2588')),
 ('Knuth', 'Milk', 'CT', Decimal('58'), Decimal('1213'), Decimal('2129')),
 ('Knuth', 'Pepsi', 'NJ', Decimal('2395'), Decimal('2758'), Decimal('2219')),
 ('Knuth', 'Pepsi', 'NY', Decimal('4252'), Decimal('2164'), Decimal('2211')),
 ('Knuth', 'Pepsi', 'CT', Decimal('1785'), Decimal('3029'), Decimal('2104')),
 ('Knuth', 'Pepsi', 'PA', Decimal('2464'), Decimal('2679'), Decimal('2450')),
 ('Knuth', 'Soap', 'NY', Decimal('2791'), Decimal('1506'), Decimal('2455')),
 ('Knuth', 'Soap', 'PA', Decimal('1774'), Decimal('1874'), Decimal('2501')),
 ('Knuth', 'Soap', 'CT', Decimal('1568'), Decimal('2096'), Decimal('2156')),
 ('Knuth', 'Soap', 'NJ', Decimal('657'), Decimal('1976'), Decimal('2344')),
 ('Knuth', 'Yogurt', 'NY', Decimal('3575'), Decimal('2335'), Decimal('2390')),
 ('Knuth', 'Yogurt', 'NJ', Decimal('2167'), Decimal('2713'), Decimal('2261')),
 ('Knuth', 'Yogurt', 'PA', Decimal('2885'), Decimal('2405'), Decimal('2382')),
 ('Knuth', 'Yogurt', 'CT', Decimal('301'), Decimal('2979'), Decimal('2121')),
 ('Sam', 'Bread', 'PA', Decimal('483'), Decimal('2077'), Decimal('2606')),
 ('Sam', 'Bread', 'CT', Decimal('903'), Decimal('1937'), Decimal('2140')),
 ('Sam', 'Bread', 'NY', Decimal('2282'), Decimal('1592'), Decimal('2436')),
 ('Sam', 'Bread', 'NJ', Decimal('2791'), Decimal('1011'), Decimal('2559')),
 ('Sam', 'Butter', 'PA', Decimal('673'), Decimal('2991'), Decimal('2510')),
 ('Sam', 'Butter', 'NJ', Decimal('3212'), Decimal('2192'), Decimal('2472')),
 ('Sam', 'Butter', 'NY', Decimal('2698'), Decimal('2704'), Decimal('2384')),
 ('Sam', 'Coke', 'CT', Decimal('2746'), Decimal('1954'), Decimal('1935')),
 ('Sam', 'Coke', 'NY', Decimal('1405'), Decimal('2848'), Decimal('2536')),
 ('Sam', 'Coke', 'PA', Decimal('3053'), Decimal('2075'), Decimal('2410')),
 ('Sam', 'Cookies', 'NY', Decimal('3376'), Decimal('1476'), Decimal('2381')),
 ('Sam', 'Cookies', 'CT', Decimal('1328'), Decimal('1915'), Decimal('2093')),
 ('Sam', 'Cookies', 'PA', Decimal('1550'), Decimal('2010'), Decimal('2605')),
 ('Sam', 'Eggs', 'NJ', Decimal('1103'), Decimal('2795'), Decimal('2709')),
 ('Sam', 'Eggs', 'PA', Decimal('3416'), Decimal('1746'), Decimal('2302')),
 ('Sam', 'Eggs', 'NY', Decimal('2175'), Decimal('2491'), Decimal('2471')),
 ('Sam', 'Fruits', 'CT', Decimal('3101'), Decimal('3460'), Decimal('1896')),
 ('Sam', 'Fruits', 'NY', Decimal('3574'), Decimal('3342'), Decimal('2308')),
 ('Sam', 'Fruits', 'PA', Decimal('3561'), Decimal('3314'), Decimal('2283')),
 ('Sam', 'Fruits', 'NJ', Decimal('3282'), Decimal('3433'), Decimal('2495')),
 ('Sam', 'Milk', 'NJ', Decimal('4522'), Decimal('1589'), Decimal('2508')),
 ('Sam', 'Milk', 'CT', Decimal('1423'), Decimal('2059'), Decimal('2214')),
 ('Sam', 'Milk', 'NY', Decimal('1601'), Decimal('1910'), Decimal('2623')),
 ('Sam', 'Milk', 'PA', Decimal('1849'), Decimal('1804'), Decimal('2516')),
 ('Sam', 'Pepsi', 'CT', Decimal('2376'), Decimal('3261'), Decimal('1926')),
 ('Sam', 'Pepsi', 'NJ', Decimal('3086'), Decimal('2904'), Decimal('2435')),
 ('Sam', 'Pepsi', 'PA', Decimal('2841'), Decimal('3001'), Decimal('2419')),
 ('Sam', 'Pepsi', 'NY', Decimal('3993'), Decimal('2806'), Decimal('2264')),
 ('Sam', 'Soap', 'NY', Decimal('2529'), Decimal('2129'), Decimal('2418')),
 ('Sam', 'Soap', 'CT', Decimal('2461'), Decimal('2175'), Decimal('1993')),
 ('Sam', 'Soap', 'NJ', Decimal('1348'), Decimal('2689'), Decimal('2811')),
 ('Sam', 'Soap', 'PA', Decimal('2826'), Decimal('1845'), Decimal('2362')),
 ('Sam', 'Yogurt', 'CT', Decimal('2546'), Decimal('2318'), Decimal('1957')),
 ('Sam', 'Yogurt', 'PA', Decimal('3130'), Decimal('1988'), Decimal('2342')),
 ('Sam', 'Yogurt', 'NJ', Decimal('1841'), Decimal('2633'), Decimal('2683')),
 ('Sam', 'Yogurt', 'NY', Decimal('1317'), Decimal('2500'), Decimal('2484'))]

In [121]:
%%sql
With
t_all_month AS(
SELECT DISTINCT s1.prod, s1.cust,
case when s2.month in (1,2,3) then 1
     when s2.month in (4,5,6) then 2
     when s2.month in (7,8,9) then 3
     when s2.month in (10,11,12) then 4 END AS Q
FROM sales s1, sales s2
-- ORDER BY 1,2,3
),


t1 AS (
SELECT prod, cust, ROUND(AVG(quant)) AS avq,
case when month in (1,2,3) then 1
     when month in (4,5,6) then 2
     when month in (7,8,9) then 3
     when month in (10,11,12) then 4 END AS Q
FROM sales
GROUP BY prod, cust, Q
),


tbf AS(
SELECT t1.prod, t1.cust, bf.Q, bf.avq as bfq
FROM t1
LEFT JOIN t1 bf ON t1.cust = bf.cust AND t1.prod = bf.prod AND t1.Q-1 = bf.Q
-- WHERE t1.prod='Bread' and t1.cust='Bloom'
),


taf AS
(
SELECT t1.prod, t1.cust, af.Q, af.avq as afq
FROM t1
LEFT JOIN t1 af ON t1.cust = af.cust AND t1.prod = af.prod AND t1.Q+1 = af.Q
-- WHERE t1.prod='Bread' and t1.cust='Bloom'
)




SELECT ta.prod,  ta.cust,  ta.Q,
-- t1.avq, -- USED for checking
bfq as BEFORE_AVG, afq as AFTER_AVG
FROM t_all_month ta
LEFT JOIN t1 on ta.prod = t1.prod AND ta.cust = t1.cust AND ta.Q = t1.Q  -- keep 200 rows, this is neccessary
LEFT JOIN tbf ON t1.Q = tbf.Q+1 AND t1.cust = tbf.cust AND t1.prod = tbf.prod  -- NEED to add back month difference
LEFT JOIN taf ON t1.Q = taf.Q-1 AND t1.cust = taf.cust AND t1.prod = taf.prod
-- WHERE t1.prod='Bread' and t1.cust='Bloom'
ORDER BY 1,2,3

 * postgresql://postgres:***@127.0.0.1/salesdb
200 rows affected.

[('Bread', 'Bloom', 1, None, Decimal('539')),
 ('Bread', 'Bloom', 2, Decimal('3267'), Decimal('2388')),
 ('Bread', 'Bloom', 3, Decimal('539'), Decimal('1106')),
 ('Bread', 'Bloom', 4, Decimal('2388'), None),
 ('Bread', 'Emily', 1, None, Decimal('1720')),
 ('Bread', 'Emily', 2, Decimal('492'), Decimal('807')),
 ('Bread', 'Emily', 3, Decimal('1720'), Decimal('2318')),
 ('Bread', 'Emily', 4, Decimal('807'), None),
 ('Bread', 'Helen', 1, None, Decimal('2648')),
 ('Bread', 'Helen', 2, Decimal('3530'), None),
 ('Bread', 'Helen', 3, None, None),
 ('Bread', 'Helen', 4, None, None),
 ('Bread', 'Knuth', 1, None, Decimal('3283')),
 ('Bread', 'Knuth', 2, Decimal('3366'), Decimal('1579')),
 ('Bread', 'Knuth', 3, Decimal('3283'), Decimal('1405')),
 ('Bread', 'Knuth', 4, Decimal('1579'), None),
 ('Bread', 'Sam', 1, None, Decimal('2735')),
 ('Bread', 'Sam', 2, Decimal('1378'), Decimal('1622')),
 ('Bread', 'Sam', 3, Decimal('2735'), Decimal('93')),
 ('Bread', 'Sam', 4, Decimal('1622'), None),
 ('Butter', 'Bloom', 1, None, None),
 ('Butter', 'Bloom', 2, None, None),
 ('Butter', 'Bloom', 3, None, Decimal('4279')),
 ('Butter', 'Bloom', 4, Decimal('2386'), None),
 ('Butter', 'Emily', 1, None, Decimal('2869')),
 ('Butter', 'Emily', 2, Decimal('1490'), Decimal('3053')),
 ('Butter', 'Emily', 3, Decimal('2869'), Decimal('2862')),
 ('Butter', 'Emily', 4, Decimal('3053'), None),
 ('Butter', 'Helen', 1, None, Decimal('2886')),
 ('Butter', 'Helen', 2, Decimal('2040'), Decimal('1913')),
 ('Butter', 'Helen', 3, Decimal('2886'), Decimal('907')),
 ('Butter', 'Helen', 4, Decimal('1913'), None),
 ('Butter', 'Knuth', 1, None, Decimal('895')),
 ('Butter', 'Knuth', 2, Decimal('1374'), None),
 ('Butter', 'Knuth', 3, None, None),
 ('Butter', 'Knuth', 4, None, None),
 ('Butter', 'Sam', 1, None, Decimal('4056')),
 ('Butter', 'Sam', 2, Decimal('673'), Decimal('4893')),
 ('Butter', 'Sam', 3, Decimal('4056'), Decimal('1984')),
 ('Butter', 'Sam', 4, Decimal('4893'), None),
 ('Coke', 'Bloom', 1, None, Decimal('2681')),
 ('Coke', 'Bloom', 2, Decimal('1079'), Decimal('2669')),
 ('Coke', 'Bloom', 3, Decimal('2681'), Decimal('2867')),
 ('Coke', 'Bloom', 4, Decimal('2669'), None),
 ('Coke', 'Emily', 1, None, Decimal('3314')),
 ('Coke', 'Emily', 2, Decimal('2398'), Decimal('4379')),
 ('Coke', 'Emily', 3, Decimal('3314'), Decimal('999')),
 ('Coke', 'Emily', 4, Decimal('4379'), None),
 ('Coke', 'Helen', 1, None, Decimal('1999')),
 ('Coke', 'Helen', 2, Decimal('2708'), Decimal('2800')),
 ('Coke', 'Helen', 3, Decimal('1999'), Decimal('3109')),
 ('Coke', 'Helen', 4, Decimal('2800'), None),
 ('Coke', 'Knuth', 1, None, Decimal('2676')),
 ('Coke', 'Knuth', 2, Decimal('3559'), Decimal('1512')),
 ('Coke', 'Knuth', 3, Decimal('2676'), Decimal('2789')),
 ('Coke', 'Knuth', 4, Decimal('1512'), None),
 ('Coke', 'Sam', 1, None, Decimal('1481')),
 ('Coke', 'Sam', 2, Decimal('2670'), Decimal('3053')),
 ('Coke', 'Sam', 3, Decimal('1481'), None),
 ('Coke', 'Sam', 4, None, None),
 ('Cookies', 'Bloom', 1, None, None),
 ('Cookies', 'Bloom', 2, None, Decimal('3287')),
 ('Cookies', 'Bloom', 3, Decimal('2782'), Decimal('2970')),
 ('Cookies', 'Bloom', 4, Decimal('3287'), None),
 ('Cookies', 'Emily', 1, None, Decimal('3760')),
 ('Cookies', 'Emily', 2, Decimal('3131'), Decimal('1716')),
 ('Cookies', 'Emily', 3, Decimal('3760'), Decimal('2421')),
 ('Cookies', 'Emily', 4, Decimal('1716'), None),
 ('Cookies', 'Helen', 1, None, None),
 ('Cookies', 'Helen', 2, None, None),
 ('Cookies', 'Helen', 3, None, Decimal('1179')),
 ('Cookies', 'Helen', 4, Decimal('2180'), None),
 ('Cookies', 'Knuth', 1, None, Decimal('2978')),
 ('Cookies', 'Knuth', 2, Decimal('2363'), Decimal('3709')),
 ('Cookies', 'Knuth', 3, Decimal('2978'), Decimal('1669')),
 ('Cookies', 'Knuth', 4, Decimal('3709'), None),
 ('Cookies', 'Sam', 1, None, Decimal('408')),
 ('Cookies', 'Sam', 2, Decimal('2523'), None),
 ('Cookies', 'Sam', 3, None, None),
 ('Cookies', 'Sam', 4, None, None),
 ('Eggs', 'Bloom', 1, None, Decimal('3597')),
 ('Eggs', 'Bloom', 2, Decimal('2819'), Decimal('2185')),
 ('Eggs', 'Bloom', 3, Decimal('3597'), Decimal('1053')),
 ('Eggs', 'Bloom', 4, Decimal('2185'), None),
 ('Eggs', 'Emily', 1, None, Decimal('2715')),
 ('Eggs', 'Emily', 2, Decimal('4535'), Decimal('3231')),
 ('Eggs', 'Emily', 3, Decimal('2715'), Decimal('2039')),
 ('Eggs', 'Emily', 4, Decimal('3231'), None),
 ('Eggs', 'Helen', 1, None, Decimal('2327')),
 ('Eggs', 'Helen', 2, Decimal('813'), None),
 ('Eggs', 'Helen', 3, None, None),
 ('Eggs', 'Helen', 4, None, None),
 ('Eggs', 'Knuth', 1, None, Decimal('1239')),
 ('Eggs', 'Knuth', 2, Decimal('4051'), Decimal('3532')),
 ('Eggs', 'Knuth', 3, Decimal('1239'), Decimal('2254')),
 ('Eggs', 'Knuth', 4, Decimal('3532'), None),
 ('Eggs', 'Sam', 1, None, Decimal('2239')),
 ('Eggs', 'Sam', 2, Decimal('2482'), Decimal('1191')),
 ('Eggs', 'Sam', 3, Decimal('2239'), Decimal('4674')),
 ('Eggs', 'Sam', 4, Decimal('1191'), None),
 ('Fruits', 'Bloom', 1, None, Decimal('1933')),
 ('Fruits', 'Bloom', 2, Decimal('2243'), Decimal('2994')),
 ('Fruits', 'Bloom', 3, Decimal('1933'), Decimal('2926')),
 ('Fruits', 'Bloom', 4, Decimal('2994'), None),
 ('Fruits', 'Emily', 1, None, Decimal('2243')),
 ('Fruits', 'Emily', 2, Decimal('2919'), Decimal('2750')),
 ('Fruits', 'Emily', 3, Decimal('2243'), Decimal('2873')),
 ('Fruits', 'Emily', 4, Decimal('2750'), None),
 ('Fruits', 'Helen', 1, None, Decimal('2000')),
 ('Fruits', 'Helen', 2, Decimal('1570'), None),
 ('Fruits', 'Helen', 3, None, None),
 ('Fruits', 'Helen', 4, None, None),
 ('Fruits', 'Knuth', 1, None, Decimal('1857')),
 ('Fruits', 'Knuth', 2, Decimal('2758'), Decimal('1175')),
 ('Fruits', 'Knuth', 3, Decimal('1857'), Decimal('2279')),
 ('Fruits', 'Knuth', 4, Decimal('1175'), None),
 ('Fruits', 'Sam', 1, None, None),
 ('Fruits', 'Sam', 2, None, Decimal('3611')),
 ('Fruits', 'Sam', 3, Decimal('3743'), Decimal('3217')),
 ('Fruits', 'Sam', 4, Decimal('3611'), None),
 ('Milk', 'Bloom', 1, None, Decimal('2377')),
 ('Milk', 'Bloom', 2, Decimal('3215'), Decimal('1106')),
 ('Milk', 'Bloom', 3, Decimal('2377'), Decimal('3010')),
 ('Milk', 'Bloom', 4, Decimal('1106'), None),
 ('Milk', 'Emily', 1, None, Decimal('2581')),
 ('Milk', 'Emily', 2, Decimal('2589'), Decimal('1997')),
 ('Milk', 'Emily', 3, Decimal('2581'), Decimal('4986')),
 ('Milk', 'Emily', 4, Decimal('1997'), None),
 ('Milk', 'Helen', 1, None, Decimal('807')),
 ('Milk', 'Helen', 2, Decimal('3312'), Decimal('3314')),
 ('Milk', 'Helen', 3, Decimal('807'), Decimal('981')),
 ('Milk', 'Helen', 4, Decimal('3314'), None),
 ('Milk', 'Knuth', 1, None, Decimal('2424')),
 ('Milk', 'Knuth', 2, Decimal('92'), None),
 ('Milk', 'Knuth', 3, None, None),
 ('Milk', 'Knuth', 4, None, None),
 ('Milk', 'Sam', 1, None, Decimal('598')),
 ('Milk', 'Sam', 2, Decimal('1745'), Decimal('2125')),
 ('Milk', 'Sam', 3, Decimal('598'), Decimal('2431')),
 ('Milk', 'Sam', 4, Decimal('2125'), None),
 ('Pepsi', 'Bloom', 1, None, Decimal('1868')),
 ('Pepsi', 'Bloom', 2, Decimal('526'), Decimal('794')),
 ('Pepsi', 'Bloom', 3, Decimal('1868'), Decimal('4374')),
 ('Pepsi', 'Bloom', 4, Decimal('794'), None),
 ('Pepsi', 'Emily', 1, None, Decimal('2374')),
 ('Pepsi', 'Emily', 2, Decimal('3842'), None),
 ('Pepsi', 'Emily', 3, None, None),
 ('Pepsi', 'Emily', 4, None, None),
 ('Pepsi', 'Helen', 1, None, Decimal('2397')),
 ('Pepsi', 'Helen', 2, Decimal('3130'), Decimal('2768')),
 ('Pepsi', 'Helen', 3, Decimal('2397'), Decimal('2435')),
 ('Pepsi', 'Helen', 4, Decimal('2768'), None),
 ('Pepsi', 'Knuth', 1, None, Decimal('2468')),
 ('Pepsi', 'Knuth', 2, Decimal('3214'), Decimal('2982')),
 ('Pepsi', 'Knuth', 3, Decimal('2468'), Decimal('1596')),
 ('Pepsi', 'Knuth', 4, Decimal('2982'), None),
 ('Pepsi', 'Sam', 1, None, Decimal('2332')),
 ('Pepsi', 'Sam', 2, Decimal('2442'), Decimal('3954')),
 ('Pepsi', 'Sam', 3, Decimal('2332'), Decimal('3166')),
 ('Pepsi', 'Sam', 4, Decimal('3954'), None),
 ('Soap', 'Bloom', 1, None, Decimal('2310')),
 ('Soap', 'Bloom', 2, Decimal('4623'), Decimal('329')),
 ('Soap', 'Bloom', 3, Decimal('2310'), Decimal('4364')),
 ('Soap', 'Bloom', 4, Decimal('329'), None),
 ('Soap', 'Emily', 1, None, Decimal('2549')),
 ('Soap', 'Emily', 2, Decimal('3218'), Decimal('1531')),
 ('Soap', 'Emily', 3, Decimal('2549'), Decimal('2976')),
 ('Soap', 'Emily', 4, Decimal('1531'), None),
 ('Soap', 'Helen', 1, None, None),
 ('Soap', 'Helen', 2, None, None),
 ('Soap', 'Helen', 3, None, Decimal('1209')),
 ('Soap', 'Helen', 4, Decimal('2990'), None),
 ('Soap', 'Knuth', 1, None, Decimal('1519')),
 ('Soap', 'Knuth', 2, Decimal('878'), Decimal('1002')),
 ('Soap', 'Knuth', 3, Decimal('1519'), Decimal('2620')),
 ('Soap', 'Knuth', 4, Decimal('1002'), None),
 ('Soap', 'Sam', 1, None, Decimal('2878')),
 ('Soap', 'Sam', 2, Decimal('1994'), Decimal('3108')),
 ('Soap', 'Sam', 3, Decimal('2878'), Decimal('694')),
 ('Soap', 'Sam', 4, Decimal('3108'), None),
 ('Yogurt', 'Bloom', 1, None, Decimal('2623')),
 ('Yogurt', 'Bloom', 2, Decimal('1660'), Decimal('2398')),
 ('Yogurt', 'Bloom', 3, Decimal('2623'), Decimal('1786')),
 ('Yogurt', 'Bloom', 4, Decimal('2398'), None),
 ('Yogurt', 'Emily', 1, None, Decimal('2650')),
 ('Yogurt', 'Emily', 2, Decimal('3079'), Decimal('2161')),
 ('Yogurt', 'Emily', 3, Decimal('2650'), Decimal('730')),
 ('Yogurt', 'Emily', 4, Decimal('2161'), None),
 ('Yogurt', 'Helen', 1, None, Decimal('3174')),
 ('Yogurt', 'Helen', 2, Decimal('2332'), Decimal('2904')),
 ('Yogurt', 'Helen', 3, Decimal('3174'), Decimal('2247')),
 ('Yogurt', 'Helen', 4, Decimal('2904'), None),
 ('Yogurt', 'Knuth', 1, None, Decimal('1787')),
 ('Yogurt', 'Knuth', 2, Decimal('3903'), Decimal('3705')),
 ('Yogurt', 'Knuth', 3, Decimal('1787'), Decimal('2497')),
 ('Yogurt', 'Knuth', 4, Decimal('3705'), None),
 ('Yogurt', 'Sam', 1, None, Decimal('2735')),
 ('Yogurt', 'Sam', 2, Decimal('2126'), Decimal('2000')),
 ('Yogurt', 'Sam', 3, Decimal('2735'), None),
 ('Yogurt', 'Sam', 4, None, None)]